;; Guest-visible import/export aliases from c-engine-i32-smoke.c:test_extern_aliases.
;; C pointer identity, import binding and teardown checks remain in that gate.
(module $provider
  (memory (export "memory") 1 3)
  (table (export "table") 2 4 funcref)
  (global (export "global") (mut i32) (i32.const 10))
  (func $answer (result i32) i32.const 42)
  (elem (i32.const 0) $answer)
  (func (export "read-global") (result i32) global.get 0)
  (func (export "read-memory") (param i32) (result i32) local.get 0 i32.load)
  (func (export "size") (result i32) memory.size)
  (func (export "table-size") (result i32) table.size 0)
  (func (export "indirect") (result i32) i32.const 0 call_indirect (result i32)))
(register "provider" $provider)
(module $consumer
  (import "provider" "memory" (memory 1 3))
  (import "provider" "table" (table 2 4 funcref))
  (import "provider" "global" (global (mut i32)))
  (export "memory" (memory 0))
  (export "table" (table 0))
  (export "global" (global 0))
  (func (export "set-global") (param i32) (result i32)
    local.get 0 global.set 0 global.get 0)
  (func (export "store") (param i32 i32) (result i32)
    local.get 0 local.get 1 i32.store local.get 0 i32.load)
  (func (export "grow") (param i32) (result i32) local.get 0 memory.grow)
  (func (export "table-grow") (param i32) (result i32)
    ref.null func local.get 0 table.grow 0)
  (func (export "indirect") (result i32) i32.const 0 call_indirect (result i32))
  (func (export "clear-table") i32.const 0 ref.null func table.set 0))
(assert_return (invoke $consumer "set-global" (i32.const 73)) (i32.const 73))
(assert_return (invoke $provider "read-global") (i32.const 73))
(assert_return (invoke $consumer "store" (i32.const 24) (i32.const 0x12345678)) (i32.const 0x12345678))
(assert_return (invoke $provider "read-memory" (i32.const 24)) (i32.const 0x12345678))
(assert_return (invoke $consumer "grow" (i32.const 1)) (i32.const 1))
(assert_return (invoke $provider "size") (i32.const 2))
;; Mutation through re-exported externs must reach the original provider.
(register "reexport" $consumer)
(module $reexport
  (import "reexport" "memory" (memory 1 3))
  (import "reexport" "table" (table 2 4 funcref))
  (import "reexport" "global" (global (mut i32)))
  (func (export "mutate")
    i32.const 99 global.set 0
    i32.const 24 i32.const 123 i32.store)
  (func (export "indirect") (result i32) i32.const 0 call_indirect (result i32)))
(assert_return (invoke $reexport "mutate"))
(assert_return (invoke $provider "read-global") (i32.const 99))
(assert_return (invoke $provider "read-memory" (i32.const 24)) (i32.const 123))
(assert_return (invoke $consumer "indirect") (i32.const 42))
(assert_return (invoke $reexport "indirect") (i32.const 42))
(assert_return (invoke $consumer "table-grow" (i32.const 1)) (i32.const 2))
(assert_return (invoke $provider "table-size") (i32.const 3))
(assert_return (invoke $consumer "clear-table"))
(assert_trap (invoke $provider "indirect") "uninitialized element")
(assert_trap (invoke $reexport "indirect") "uninitialized element")
