;; Guest-visible fresh instance state from c-engine-i32-smoke.c:
;; test_decoded_module_instances. WAST does not expose decode-once ownership,
;; clone page sharing, allocator state or post-disposal C object lifetimes.
(module $first
  (memory 1 2)
  (data (i32.const 8) "\78\56\34\12")
  (global $value (mut i32) (i32.const 5))
  (func (export "store-load") (param i32 i32) (result i32)
    local.get 0 local.get 1 i32.store local.get 0 i32.load)
  (func (export "load-data") (param i32) (result i32) local.get 0 i32.load)
  (func (export "global") (param i32) (result i32)
    local.get 0 global.set $value global.get $value)
  (func (export "read-global") (result i32) global.get $value)
  (func (export "grow") (param i32) (result i32) local.get 0 memory.grow)
  (func (export "size") (result i32) memory.size))
(module $second
  (memory 1 2)
  (data (i32.const 8) "\78\56\34\12")
  (global $value (mut i32) (i32.const 5))
  (func (export "store-load") (param i32 i32) (result i32)
    local.get 0 local.get 1 i32.store local.get 0 i32.load)
  (func (export "load-data") (param i32) (result i32) local.get 0 i32.load)
  (func (export "global") (param i32) (result i32)
    local.get 0 global.set $value global.get $value)
  (func (export "read-global") (result i32) global.get $value)
  (func (export "grow") (param i32) (result i32) local.get 0 memory.grow)
  (func (export "size") (result i32) memory.size))
(assert_return (invoke $first "store-load" (i32.const 16) (i32.const 0x12345678)) (i32.const 0x12345678))
(assert_return (invoke $second "load-data" (i32.const 16)) (i32.const 0))
(assert_return (invoke $first "global" (i32.const 91)) (i32.const 91))
(assert_return (invoke $second "read-global") (i32.const 5))
(assert_return (invoke $first "grow" (i32.const 1)) (i32.const 1))
(assert_return (invoke $first "size") (i32.const 2))
(assert_return (invoke $second "size") (i32.const 1))
(assert_return (invoke $first "load-data" (i32.const 8)) (i32.const 0x12345678))
(assert_return (invoke $second "load-data" (i32.const 8)) (i32.const 0x12345678))
;; Reverse the writer/reader roles to catch accidental current-instance reuse.
(assert_return (invoke $second "store-load" (i32.const 16) (i32.const 22)) (i32.const 22))
(assert_return (invoke $first "load-data" (i32.const 16)) (i32.const 0x12345678))
(assert_return (invoke $second "global" (i32.const 33)) (i32.const 33))
(assert_return (invoke $first "read-global") (i32.const 91))
(assert_return (invoke $second "grow" (i32.const 1)) (i32.const 1))
(assert_return (invoke $first "size") (i32.const 2))
(assert_return (invoke $second "size") (i32.const 2))
