;; Installed shared libc, real guest wrappers, and final-close/reopen lifecycle.
;; Run with the installed VFS mounted in either C runtime.
(module $runtime
  (import "waste_kernel" "dlopen_v1" (func $open (param i32 i32 i32) (result i32)))
  (memory (export "memory") 5)
  (table (export "table") 1 funcref)
  (global (export "__stack_pointer") (mut i32) (i32.const 262144))
  (data (i32.const 1024) "/usr/lib/libc.so.wasm\00")
  (func (export "load") (result i32)
    (i32.ne (call $open (i32.const 1024) (i32.const 21) (i32.const 2)) (i32.const 0))))
(register "waste-runtime" $runtime)
(assert_return (invoke "load") (i32.const 1))
(register "env")
(assert_return (invoke "waste_allocator_init" (i32.const 327680)) (i32.const 1))
(assert_return (invoke "waste_stdio_init" (i32.const 65536)) (i32.const 1))
(module $client
  (import "waste-runtime" "memory" (memory 5))
  (import "waste-runtime" "table" (table 1 funcref))
  (import "waste-runtime" "__stack_pointer" (global $stack (mut i32)))
  (import "libc" "memcpy" (func $memcpy (param i32 i32 i32) (result i32)))
  (import "libc" "strcpy" (func $strcpy (param i32 i32) (result i32)))
  (import "libc" "strcmp" (func $strcmp (param i32 i32) (result i32)))
  (import "libc" "malloc" (func $malloc (param i32) (result i32)))
  (import "libc" "free" (func $free (param i32)))
  (import "libc" "printf" (func $printf (param i32 i32) (result i32)))
  (import "libc" "dlopen" (func $open (param i32 i32) (result i32)))
  (import "libc" "dlsym" (func $symbol (param i32 i32) (result i32)))
  (import "libc" "dlclose" (func $close (param i32) (result i32)))
  (import "libc" "dlerror" (func $error (result i32)))
  (global $handle (mut i32) (i32.const 0))
  (global $symbol_index (mut i32) (i32.const 0))
  (export "__stack_pointer" (global $stack))
  (data (i32.const 2048) "shared libc\00")
  (data (i32.const 2100) "/usr/lib/libncurses.so.wasm\00")
  (data (i32.const 2140) "initscr\00missing_symbol\00")
  (data (i32.const 2200) "__SHARED_LIBC__%s:%d\0a\00")
  (data (i32.const 2256) "\00\08\00\00\2a\00\00\00")
  (data (i32.const 2300) "/missing-library.so.wasm\00")
  (func (export "strings") (result i32)
    (local $p i32)
    (local.set $p (call $malloc (i32.const 64)))
    (if (i32.eqz (local.get $p)) (then (return (i32.const -1))))
    (drop (call $memcpy (local.get $p) (i32.const 2048) (i32.const 12)))
    (drop (call $strcpy (i32.const 2400) (local.get $p)))
    (call $free (local.get $p))
    (call $strcmp (i32.const 2400) (i32.const 2048)))
  (func (export "print") (result i32)
    (call $printf (i32.const 2200) (i32.const 2256)))
  (func (export "missing") (result i32)
    (call $open (i32.const 2300) (i32.const 2)))
  (func (export "error") (result i32) (i32.ne (call $error) (i32.const 0)))
  (func (export "open") (result i32)
    (global.set $handle (call $open (i32.const 2100) (i32.const 2)))
    (i32.ne (global.get $handle) (i32.const 0)))
  (func (export "open-again") (result i32)
    (i32.eq (global.get $handle) (call $open (i32.const 2100) (i32.const 2))))
  (func (export "find") (result i32)
    (global.set $symbol_index (call $symbol (global.get $handle) (i32.const 2140)))
    (i32.ne (global.get $symbol_index) (i32.const 0)))
  (func (export "missing-symbol") (result i32)
    (call $symbol (global.get $handle) (i32.const 2148)))
  (func (export "close") (result i32) (call $close (global.get $handle)))
  (func (export "symbol-null") (result i32)
    (ref.is_null (table.get (global.get $symbol_index)))))
(assert_return (invoke $client "strings") (i32.const 0))
;; The session harness checks the bytes from printf; batch runners may have
;; no stdout descriptor. Pure string/allocator assertions also run there.
(invoke $client "print")
(assert_return (invoke $client "missing") (i32.const 0))
(assert_return (invoke $client "error") (i32.const 1))
(assert_return (invoke $client "error") (i32.const 0))
(assert_return (invoke $client "open") (i32.const 1))
(assert_return (invoke $client "strings") (i32.const 0))
(assert_return (invoke $client "open-again") (i32.const 1))
(assert_return (invoke $client "find") (i32.const 1))
(assert_return (invoke $client "missing-symbol") (i32.const 0))
(assert_return (invoke $client "error") (i32.const 1))
(assert_return (invoke $client "close") (i32.const 0))
(assert_return (invoke $client "symbol-null") (i32.const 0))
(assert_return (invoke $client "close") (i32.const 0))
(assert_return (invoke $client "symbol-null") (i32.const 1))
(assert_return (invoke $client "find") (i32.const 0))
(assert_return (invoke $client "close") (i32.const -1))
(assert_return (invoke $client "error") (i32.const 1))
(assert_return (invoke $client "error") (i32.const 0))
(assert_return (invoke $client "open") (i32.const 1))
(assert_return (invoke $client "find") (i32.const 1))
(assert_return (invoke $client "close") (i32.const 0))
(assert_return (invoke $client "symbol-null") (i32.const 1))
