;; Linked Wasm imports must select the forked process's provider instance.
;; A child write/free through libc used to mutate the canonical parent engine.
(module $provider
  (import "env" "write" (func $write (param i32 i32 i32) (result i32)))
  (memory (export "memory") 1)
  (global $count (export "count") (mut i32) (i32.const 10))
  (func $bump (export "bump") (result i32)
    (global.set $count (i32.add (global.get $count) (i32.const 1)))
    (i32.store (i32.const 64) (global.get $count))
    ;; Host calls use the cached default memory, not the indexed Wasm path.
    (i32.store8 (i32.const 96) (i32.add (global.get $count) (i32.const 54)))
    (drop (call $write (i32.const 1) (i32.const 96) (i32.const 1)))
    (global.get $count))
  (table (export "table") 1 funcref)
  (elem (i32.const 0) $bump))
(register "provider" $provider)
(module $relay
  (import "provider" "bump" (func $bump (result i32)))
  (func (export "bump") (result i32) (call $bump)))
(register "relay" $relay)
(module $client
  (type $callback (func (result i32)))
  (import "provider" "memory" (memory 1))
  (import "provider" "count" (global $count (mut i32)))
  (import "provider" "table" (table 1 funcref))
  (import "relay" "bump" (func $bump (result i32)))
  (import "env" "fork" (func $fork (result i32)))
  (import "env" "exit" (func $exit (param i32)))
  (import "env" "waitpid" (func $wait (param i32 i32 i32) (result i32)))
  (func (export "fork") (result i32) (local $pid i32) (local $before i32)
    (local.set $before (call $bump))
    (local.set $pid (call $fork))
    (if (i32.eqz (local.get $pid)) (then
      (if (i32.ne (call $bump) (i32.add (local.get $before) (i32.const 1)))
        (then unreachable))
      (if (i32.ne (call_indirect (type $callback) (i32.const 0))
                  (i32.add (local.get $before) (i32.const 2)))
        (then unreachable))
      (if (i32.ne (global.get $count) (i32.load (i32.const 64)))
        (then unreachable))
      (call $exit (i32.const 7))))
    (drop (call $wait (local.get $pid) (i32.const 128) (i32.const 0)))
    (if (i32.ne (global.get $count) (local.get $before)) (then unreachable))
    (if (i32.ne (i32.load (i32.const 64)) (local.get $before)) (then unreachable))
    (if (i32.ne (i32.load (i32.const 128)) (i32.const 1792)) (then unreachable))
    (global.get $count)))
(assert_return (invoke $client "fork") (i32.const 11))
(assert_return (invoke $client "fork") (i32.const 12))
(assert_return (invoke $client "fork") (i32.const 13))
