;; Process/foreground groups use real imports; terminal VINTR arrives only at
;; genuine SELECT yields from the shared JSON contract. Private signal queues,
;; input injection and raw kernel interruption remain focused C checks.
(module
  (import "env" "getpgrp" (func $group (result i32)))
  (import "env" "setpgid" (func $set_group (param i32 i32) (result i32)))
  (import "env" "tcgetpgrp" (func $foreground (param i32) (result i32)))
  (import "env" "tcsetpgrp" (func $set_foreground (param i32 i32) (result i32)))
  (import "env" "tcgetattr" (func $get (param i32 i32) (result i32)))
  (import "env" "tcsetattr" (func $set (param i32 i32 i32) (result i32)))
  (import "env" "pselect" (func $select (param i32 i32 i32 i32 i32 i32) (result i32)))
  (import "env" "read" (func $read (param i32 i32 i32) (result i32)))
  (import "env" "write" (func $write (param i32 i32 i32) (result i32)))
  (import "env" "sigaction" (func $action (param i32 i32 i32) (result i32)))
  (import "env" "sigpending" (func $pending (param i32) (result i32)))
  (import "env" "sigemptyset" (func $empty (param i32) (result i32)))
  (import "env" "exit" (func $exit (param i32)))
  (memory 1)
  (data (i32.const 64) "BG\0aMOVE\0aFG\0aRAW\0a")
  (global $calls (mut i32) (i32.const 0))
  (global $caught (mut i32) (i32.const 0))
  ;; Thirteen imports place the first defined handler at function index 13.
  (func $handler (param i32)
    (global.set $calls (i32.add (global.get $calls) (i32.const 1)))
    (global.set $caught (local.get 0)))
  (func (export "__errno_location") (result i32) (i32.const 8))
  (func (export "group") (result i32) (call $group))
  ;; Current env.setpgid returns the new positive group, not POSIX's zero.
  (func (export "set_group") (param i32 i32) (result i32)
    (call $set_group (local.get 0) (local.get 1)))
  (func (export "foreground") (param i32) (result i32) (call $foreground (local.get 0)))
  (func (export "set_foreground") (param i32 i32) (result i32)
    (call $set_foreground (local.get 0) (local.get 1)))
  (func (export "get") (result i32) (call $get (i32.const 0) (i32.const 256)))
  (func (export "mode") (param i32) (result i32)
    (i32.store (i32.const 256) (i32.const 0))
    (i32.store (i32.const 260) (i32.const 0))
    (i32.store (i32.const 268) (local.get 0))
    (i32.store8 (i32.const 273) (i32.const 3))
    (i32.store8 (i32.const 278) (i32.const 0))
    (i32.store8 (i32.const 279) (i32.const 1))
    (call $set (i32.const 0) (i32.const 0) (i32.const 256)))
  (func (export "handler") (result i32)
    (memory.fill (i32.const 384) (i32.const 0) (i32.const 20))
    (i32.store (i32.const 384) (i32.const 13))
    (i32.store (i32.const 388) (i32.const 16384))
    (if (call $empty (i32.const 736)) (then unreachable))
    (call $action (i32.const 2) (i32.const 384) (i32.const 0)))
  (func $prepare
    (memory.fill (i32.const 512) (i32.const 0) (i32.const 128))
    (i32.store (i32.const 512) (i32.const 1)))
  (func (export "input") (param i32 i32) (result i32)
    (if (i32.ne (call $write (i32.const 1) (local.get 0) (local.get 1))
      (local.get 1)) (then unreachable))
    (call $prepare)
    (call $select (i32.const 1) (i32.const 512) (i32.const 0) (i32.const 0)
      (i32.const 0) (i32.const 736)))
  (func (export "poll") (result i32)
    (call $prepare)
    (call $select (i32.const 1) (i32.const 512) (i32.const 0) (i32.const 0)
      (i32.const 704) (i32.const 736)))
  (func (export "read") (result i32)
    (memory.fill (i32.const 1024) (i32.const 165) (i32.const 16))
    (i32.store (i32.const 1020) (i32.const 0x13579bdf))
    (i32.store (i32.const 1040) (i32.const 0x13579bdf))
    (call $read (i32.const 0) (i32.const 1024) (i32.const 16)))
  (func (export "byte") (result i32) (i32.load8_u (i32.const 1024)))
  (func (export "bounds") (result i32) (local $i i32)
    (if (i32.ne (i32.load (i32.const 1020)) (i32.const 0x13579bdf)) (then (return (i32.const 0))))
    (if (i32.ne (i32.load (i32.const 1040)) (i32.const 0x13579bdf)) (then (return (i32.const 0))))
    (local.set $i (i32.const 1))
    (block $done (loop $next
      (br_if $done (i32.eq (local.get $i) (i32.const 16)))
      (if (i32.ne (i32.load8_u (i32.add (i32.const 1024) (local.get $i))) (i32.const 165))
        (then (return (i32.const 0))))
      (local.set $i (i32.add (local.get $i) (i32.const 1))) (br $next)))
    (i32.const 1))
  (func (export "pending") (result i32)
    (if (call $pending (i32.const 768)) (then unreachable))
    (i32.or (i32.or (i32.load (i32.const 768)) (i32.load (i32.const 772)))
      (i32.or (i32.load (i32.const 776)) (i32.load (i32.const 780)))))
  (func (export "calls") (result i32) (global.get $calls))
  (func (export "caught") (result i32) (global.get $caught))
  (func (export "done") (call $exit (i32.const 0))))

;; Initial group, independent foreground group and raw ISIG setup.
(assert_return (invoke "group") (i32.const 1))
(assert_return (invoke "set_group" (i32.const 0) (i32.const 2)) (i32.const 2))
(assert_return (invoke "group") (i32.const 2))
(assert_return (invoke "foreground" (i32.const 0)) (i32.const 1))
(assert_return (invoke "foreground" (i32.const 1)) (i32.const 1))
(assert_return (invoke "foreground" (i32.const 2)) (i32.const 1))
(assert_return (invoke "get") (i32.const 0))
(assert_return (invoke "mode" (i32.const 1)) (i32.const 0))
(assert_return (invoke "handler") (i32.const 0))
;; Invalid group/descriptor changes preserve both group identities.
(assert_return (invoke "set_group" (i32.const -1) (i32.const 2)) (i32.const -22))
(assert_return (invoke "set_group" (i32.const 999) (i32.const 2)) (i32.const -22))
(assert_return (invoke "set_group" (i32.const 0) (i32.const 0)) (i32.const -22))
(assert_return (invoke "set_group" (i32.const 0) (i32.const -1)) (i32.const -22))
(assert_return (invoke "foreground" (i32.const 63)) (i32.const -9))
(assert_return (invoke "foreground" (i32.const -1)) (i32.const -9))
(assert_return (invoke "set_foreground" (i32.const 63) (i32.const 2)) (i32.const -22))
(assert_return (invoke "set_foreground" (i32.const 0) (i32.const 0)) (i32.const -22))
(assert_return (invoke "set_foreground" (i32.const 0) (i32.const -1)) (i32.const -22))
(assert_return (invoke "group") (i32.const 2))
(assert_return (invoke "foreground" (i32.const 0)) (i32.const 1))
;; Background VINTR leaves the wait pending; real x then releases it without SIGINT.
(assert_return (invoke "input" (i32.const 64) (i32.const 3)) (i32.const 1))
(assert_return (invoke "calls") (i32.const 0))
(assert_return (invoke "pending") (i32.const 0))
(assert_return (invoke "read") (i32.const 1))
(assert_return (invoke "byte") (i32.const 120))
(assert_return (invoke "bounds") (i32.const 1))
(assert_return (invoke "set_foreground" (i32.const 0) (i32.const 2)) (i32.const 0))
(assert_return (invoke "foreground" (i32.const 1)) (i32.const 2))
(assert_return (invoke "foreground" (i32.const 2)) (i32.const 2))
(assert_return (invoke "group") (i32.const 2))
;; Poll routes the queued terminal interrupt to the newly foreground group once.
(assert_return (invoke "poll") (i32.const -4))
(assert_return (invoke "calls") (i32.const 1))
(assert_return (invoke "caught") (i32.const 2))
(assert_return (invoke "pending") (i32.const 0))
(assert_return (invoke "poll") (i32.const 0))
(assert_return (invoke "calls") (i32.const 1))
;; A second group change makes this process background without changing the TTY.
(assert_return (invoke "set_group" (i32.const 1) (i32.const 42)) (i32.const 42))
(assert_return (invoke "group") (i32.const 42))
(assert_return (invoke "foreground" (i32.const 0)) (i32.const 2))
(assert_return (invoke "input" (i32.const 67) (i32.const 5)) (i32.const 1))
(assert_return (invoke "calls") (i32.const 1))
(assert_return (invoke "pending") (i32.const 0))
(assert_return (invoke "read") (i32.const 1))
(assert_return (invoke "byte") (i32.const 89))
(assert_return (invoke "bounds") (i32.const 1))
;; Foreground state is shared by the three real terminal descriptors.
(assert_return (invoke "set_foreground" (i32.const 2) (i32.const 42)) (i32.const 0))
(assert_return (invoke "foreground" (i32.const 0)) (i32.const 42))
(assert_return (invoke "group") (i32.const 42))
(assert_return (invoke "poll") (i32.const -4))
(assert_return (invoke "calls") (i32.const 2))
(assert_return (invoke "caught") (i32.const 2))
(assert_return (invoke "pending") (i32.const 0))
(assert_return (invoke "poll") (i32.const 0))
(assert_return (invoke "calls") (i32.const 2))
;; Foreground VINTR interrupts a genuine wait immediately, without a data byte.
(assert_return (invoke "input" (i32.const 72) (i32.const 3)) (i32.const -4))
(assert_return (invoke "calls") (i32.const 3))
(assert_return (invoke "caught") (i32.const 2))
(assert_return (invoke "pending") (i32.const 0))
(assert_return (invoke "poll") (i32.const 0))
(assert_return (invoke "calls") (i32.const 3))
;; With ISIG disabled the same ETX is ordinary data and cannot call the handler.
(assert_return (invoke "mode" (i32.const 0)) (i32.const 0))
(assert_return (invoke "input" (i32.const 75) (i32.const 4)) (i32.const 1))
(assert_return (invoke "read") (i32.const 1))
(assert_return (invoke "byte") (i32.const 3))
(assert_return (invoke "bounds") (i32.const 1))
(assert_return (invoke "calls") (i32.const 3))
(assert_return (invoke "pending") (i32.const 0))
(assert_return (invoke "poll") (i32.const 0))
(assert_return (invoke "group") (i32.const 42))
(assert_return (invoke "foreground" (i32.const 0)) (i32.const 42))
(invoke "done")
