;; C counterpart of the legacy DIY external-SIGINT check. Install the handler
;; during module start, then receive host controls only at a real pselect wait.
;; C sigaction names a function index; the legacy OCaml table slot is not ABI.
(module
  (import "env" "sigaction" (func $action (param i32 i32 i32) (result i32)))
  (import "env" "pselect" (func $select (param i32 i32 i32 i32 i32 i32) (result i32)))
  (import "env" "write" (func $write (param i32 i32 i32) (result i32)))
  (import "env" "exit" (func $exit (param i32)))
  (memory (export "memory") 1)
  (global $installed (mut i32) (i32.const 0))
  (global $calls (mut i32) (i32.const 0))
  (global $seen (mut i32) (i32.const 0))
  (data (i32.const 64) "STARTED")
  ;; Four imports put the handler at function index 4.
  (data (i32.const 128) "\04\00\00\00")
  (func $handler (param $signal i32)
    (global.set $calls (i32.add (global.get $calls) (i32.const 1)))
    (global.set $seen (local.get $signal)))
  (func $install
    (if (call $action (i32.const 2) (i32.const 128) (i32.const 0)) (then unreachable))
    (global.set $installed (i32.add (global.get $installed) (i32.const 1))))
  (start $install)
  (func (export "installed") (result i32) (global.get $installed))
  (func (export "calls") (result i32) (global.get $calls))
  (func (export "seen") (result i32) (global.get $seen))
  (func (export "run") (result i32)
    (if (i32.ne (call $write (i32.const 1) (i32.const 64) (i32.const 7)) (i32.const 7))
      (then unreachable))
    (if (i32.ne (call $select (i32.const 0) (i32.const 0) (i32.const 0)
          (i32.const 0) (i32.const 0) (i32.const 0)) (i32.const -4))
      (then unreachable))
    (global.get $seen))
  (func (export "done") (call $exit (i32.const 0))))
(assert_return (invoke "installed") (i32.const 1))
(assert_return (invoke "calls") (i32.const 0))
(assert_return (invoke "seen") (i32.const 0))
(assert_return (invoke "run") (i32.const 2))
(assert_return (invoke "calls") (i32.const 1))
(assert_return (invoke "installed") (i32.const 1))
(invoke "done")
