"use strict";
// Generated by the normal engine build using the shared packaging reader.
const fs = require("node:fs");
const path = require("node:path");
const config = Object.freeze(JSON.parse(fs.readFileSync(
  path.join(__dirname, "../build/engine/runtime-config.json"), "utf8")));
const withConfig = source => '"use strict";\n' + "globalThis.WASTE_CONFIG = Object.freeze(" +
  JSON.stringify(config) + ");\n" + source;
module.exports = {config, withConfig};
