;; Standard language-test tables are distinct, nullable and sandbox-owned.
;; Reject incompatible imports before changing their size or contents.
(assert_unlinkable (module (table (import "spectest" "table64") 10 20 funcref)) "incompatible import type")
(assert_unlinkable (module (table (import "spectest" "table") i64 10 20 funcref)) "incompatible import type")
(assert_unlinkable (module (table (import "spectest" "table64") i64 11 20 funcref)) "incompatible import type")
(assert_unlinkable (module (table (import "spectest" "table64") i64 10 19 funcref)) "incompatible import type")
(assert_unlinkable (module (table (import "spectest" "table64") i64 10 20 externref)) "incompatible import type")
(assert_unlinkable (module (table (import "spectest" "table64") i64 10 20 (ref func))) "incompatible import type")

(module $writer
  (type $t (func (result i32)))
  (table $wide (import "spectest" "table64") i64 10 20 funcref)
  (table $alias (import "spectest" "table64") i64 0 funcref)
  (table $narrow (import "spectest" "table") 10 20 funcref)
  (func $f (type $t) (i32.const 37))
  (elem declare func $f)
  (func (export "size") (result i64) (table.size $wide))
  (func (export "alias-size") (result i64) (table.size $alias))
  (func (export "narrow-size") (result i32) (table.size $narrow))
  (func (export "null") (param i64) (result i32)
    (ref.is_null (table.get $wide (local.get 0))))
  (func (export "narrow-null") (result i32)
    (ref.is_null (table.get $narrow (i32.const 0))))
  (func (export "set") (table.set $wide (i64.const 0) (ref.func $f)))
  (func (export "call") (param i64) (result i32)
    (call_indirect $alias (type $t) (local.get 0)))
  (func (export "grow") (param i64) (result i64)
    (table.grow $wide (ref.null func) (local.get 0)))
)
(assert_return (invoke $writer "size") (i64.const 10))
(assert_return (invoke $writer "alias-size") (i64.const 10))
(assert_return (invoke $writer "narrow-size") (i32.const 10))
(assert_return (invoke $writer "null" (i64.const 0)) (i32.const 1))
(assert_return (invoke $writer "null" (i64.const 9)) (i32.const 1))
(assert_trap (invoke $writer "null" (i64.const 10)) "out of bounds table access")
(assert_trap (invoke $writer "null" (i64.const 0x1_0000_0000)) "out of bounds table access")
(assert_trap (invoke $writer "null" (i64.const -1)) "out of bounds table access")
(assert_trap (invoke $writer "call" (i64.const 0)) "uninitialized element")
(assert_return (invoke $writer "set"))
(assert_return (invoke $writer "call" (i64.const 0)) (i32.const 37))
(assert_return (invoke $writer "null" (i64.const 0)) (i32.const 0))
(assert_return (invoke $writer "narrow-null") (i32.const 1))
(assert_return (invoke $writer "grow" (i64.const 0)) (i64.const 10))
(assert_return (invoke $writer "grow" (i64.const 2)) (i64.const 10))
(assert_return (invoke $writer "alias-size") (i64.const 12))
(assert_return (invoke $writer "null" (i64.const 11)) (i32.const 1))
(assert_return (invoke $writer "call" (i64.const 0)) (i32.const 37))

;; Another instance shares the same host object and cross-module funcref.
(module $reader
  (table $wide (import "spectest" "table64") i64 12 20 funcref)
  (func (export "size") (result i64) (table.size $wide))
  (func (export "call") (result i32)
    (call_indirect $wide (result i32) (i64.const 0)))
)
(assert_return (invoke $reader "size") (i64.const 12))
(assert_return (invoke $reader "call") (i32.const 37))
(assert_return (invoke $writer "grow" (i64.const 8)) (i64.const 12))
(assert_return (invoke $reader "size") (i64.const 20))
(assert_return (invoke $writer "null" (i64.const 19)) (i32.const 1))
(assert_return (invoke $writer "grow" (i64.const 1)) (i64.const -1))
(assert_return (invoke $writer "grow" (i64.const 0x1_0000_0000)) (i64.const -1))
(assert_return (invoke $writer "grow" (i64.const -1)) (i64.const -1))
(assert_return (invoke $writer "grow" (i64.const 0)) (i64.const 20))
(assert_return (invoke $writer "size") (i64.const 20))
(assert_return (invoke $writer "narrow-size") (i32.const 10))
(assert_return (invoke $reader "call") (i32.const 37))

;; Imports may omit a maximum or require a looser maximum.
(module (table (import "spectest" "table64") i64 0 21 funcref))
