
;; i32 offsets and lengths; both spellings preserve table identity and refs.
(module (type $t (func (result i32)))
  (func $seed (type $t) (i32.const 7))
  (func $f0 (type $t) (i32.const 11))
  (func $f1 (type $t) (i32.const 19))
  (func $f2 (type $t) (i32.const 37))
  (func $f3 (type $t) (i32.const 53))
  (func $f4 (type $t) (i32.const 71))
  (func $fill (type $t) (i32.const 97))
  (func (export "reset")
    (table.fill $target (i32.const 0) (ref.func $seed) (i32.const 5))
    (table.fill $peer (i32.const 0) (ref.func $seed) (i32.const 5))
    (table.init $src $pattern (i32.const 0) (i32.const 0) (i32.const 5)))
  (func (export "seed-target") (table.init $target $pattern (i32.const 0) (i32.const 0) (i32.const 5)))
  (func (export "read0") (param i32) (result i32) (call_indirect 0 (type $t) (local.get 0)))
  (func (export "read1") (param i32) (result i32) (call_indirect 1 (type $t) (local.get 0)))
  (func (export "read2") (param i32) (result i32) (call_indirect 2 (type $t) (local.get 0)))
  (func (export "flat-copy-default") (param i32 i32 i32)
    local.get 0 local.get 1 local.get 2 table.copy
  )
  (func (export "flat-copy-nn") (param i32 i32 i32)
    local.get 0 local.get 1 local.get 2 table.copy 0 1
  )
  (func (export "flat-copy-ni") (param i32 i32 i32)
    local.get 0 local.get 1 local.get 2 table.copy 0 $src
  )
  (func (export "flat-copy-in") (param i32 i32 i32)
    local.get 0 local.get 1 local.get 2 table.copy $target 1
  )
  (func (export "flat-copy-ii") (param i32 i32 i32)
    local.get 0 local.get 1 local.get 2 table.copy $target $src
  )
  (func (export "flat-copy-reverse") (param i32 i32 i32)
    local.get 0 local.get 1 local.get 2 table.copy 1 $target
  )
  (func (export "flat-copy-self") (param i32 i32 i32)
    local.get 0 local.get 1 local.get 2 table.copy 1 1
  )
  (func (export "flat-fill-default") (param i32 i32)
    local.get 0 ref.func $fill local.get 1 table.fill
  )
  (func (export "flat-fill-numeric") (param i32 i32)
    local.get 0 ref.func $fill local.get 1 table.fill 0
  )
  (func (export "flat-fill-named") (param i32 i32)
    local.get 0 ref.func $fill local.get 1 table.fill $target
  )
  (func (export "flat-fill-src-numeric") (param i32 i32)
    local.get 0 ref.func $fill local.get 1 table.fill 1
  )
  (func (export "flat-fill-src-named") (param i32 i32)
    local.get 0 ref.func $fill local.get 1 table.fill $src
  )
  (func (export "flat-null") (param i32 i32)
    local.get 0 ref.null func local.get 1 table.fill 0
  )
  (func (export "fold-copy-default") (param i32 i32 i32)
    (table.copy (local.get 0) (local.get 1) (local.get 2))
  )
  (func (export "fold-copy-nn") (param i32 i32 i32)
    (table.copy 0 1 (local.get 0) (local.get 1) (local.get 2))
  )
  (func (export "fold-copy-ni") (param i32 i32 i32)
    (table.copy 0 $src (local.get 0) (local.get 1) (local.get 2))
  )
  (func (export "fold-copy-in") (param i32 i32 i32)
    (table.copy $target 1 (local.get 0) (local.get 1) (local.get 2))
  )
  (func (export "fold-copy-ii") (param i32 i32 i32)
    (table.copy $target $src (local.get 0) (local.get 1) (local.get 2))
  )
  (func (export "fold-copy-reverse") (param i32 i32 i32)
    (table.copy 1 $target (local.get 0) (local.get 1) (local.get 2))
  )
  (func (export "fold-copy-self") (param i32 i32 i32)
    (table.copy 1 1 (local.get 0) (local.get 1) (local.get 2))
  )
  (func (export "fold-fill-default") (param i32 i32)
    (table.fill (local.get 0) (ref.func $fill) (local.get 1))
  )
  (func (export "fold-fill-numeric") (param i32 i32)
    (table.fill 0 (local.get 0) (ref.func $fill) (local.get 1))
  )
  (func (export "fold-fill-named") (param i32 i32)
    (table.fill $target (local.get 0) (ref.func $fill) (local.get 1))
  )
  (func (export "fold-fill-src-numeric") (param i32 i32)
    (table.fill 1 (local.get 0) (ref.func $fill) (local.get 1))
  )
  (func (export "fold-fill-src-named") (param i32 i32)
    (table.fill $src (local.get 0) (ref.func $fill) (local.get 1))
  )
  (func (export "fold-null") (param i32 i32)
    (table.fill 0 (local.get 0) (ref.null func) (local.get 1))
  )
  (table $target 5 funcref)
  (table $src 5 funcref)
  (table $peer 5 funcref)
  (elem $pattern func $f0 $f1 $f2 $f3 $f4)
  (elem declare func $seed $fill)
)
(assert_return (invoke "reset"))
(assert_return (invoke "seed-target"))
(assert_return (invoke "flat-copy-default" (i32.const 1) (i32.const 0) (i32.const 4)))
(assert_return (invoke "read0" (i32.const 0)) (i32.const 11))
(assert_return (invoke "read0" (i32.const 1)) (i32.const 11))
(assert_return (invoke "read0" (i32.const 2)) (i32.const 19))
(assert_return (invoke "read0" (i32.const 3)) (i32.const 37))
(assert_return (invoke "read0" (i32.const 4)) (i32.const 53))
(assert_return (invoke "read2" (i32.const 0)) (i32.const 7))
(assert_return (invoke "reset"))
(assert_return (invoke "seed-target"))
(assert_return (invoke "flat-copy-default" (i32.const 0) (i32.const 1) (i32.const 4)))
(assert_return (invoke "read0" (i32.const 0)) (i32.const 19))
(assert_return (invoke "read0" (i32.const 1)) (i32.const 37))
(assert_return (invoke "read0" (i32.const 2)) (i32.const 53))
(assert_return (invoke "read0" (i32.const 3)) (i32.const 71))
(assert_return (invoke "read0" (i32.const 4)) (i32.const 71))
(assert_return (invoke "read2" (i32.const 0)) (i32.const 7))
(assert_return (invoke "reset"))
(assert_return (invoke "flat-copy-nn" (i32.const 0) (i32.const 0) (i32.const 5)))
(assert_return (invoke "read0" (i32.const 0)) (i32.const 11))
(assert_return (invoke "read0" (i32.const 4)) (i32.const 71))
(assert_return (invoke "read1" (i32.const 0)) (i32.const 11))
(assert_return (invoke "read2" (i32.const 0)) (i32.const 7))
(assert_return (invoke "reset"))
(assert_return (invoke "flat-copy-ni" (i32.const 0) (i32.const 0) (i32.const 5)))
(assert_return (invoke "read0" (i32.const 0)) (i32.const 11))
(assert_return (invoke "read0" (i32.const 4)) (i32.const 71))
(assert_return (invoke "read1" (i32.const 0)) (i32.const 11))
(assert_return (invoke "read2" (i32.const 0)) (i32.const 7))
(assert_return (invoke "reset"))
(assert_return (invoke "flat-copy-in" (i32.const 0) (i32.const 0) (i32.const 5)))
(assert_return (invoke "read0" (i32.const 0)) (i32.const 11))
(assert_return (invoke "read0" (i32.const 4)) (i32.const 71))
(assert_return (invoke "read1" (i32.const 0)) (i32.const 11))
(assert_return (invoke "read2" (i32.const 0)) (i32.const 7))
(assert_return (invoke "reset"))
(assert_return (invoke "flat-copy-ii" (i32.const 0) (i32.const 0) (i32.const 5)))
(assert_return (invoke "read0" (i32.const 0)) (i32.const 11))
(assert_return (invoke "read0" (i32.const 4)) (i32.const 71))
(assert_return (invoke "read1" (i32.const 0)) (i32.const 11))
(assert_return (invoke "read2" (i32.const 0)) (i32.const 7))
(assert_return (invoke "reset"))
(assert_return (invoke "flat-copy-reverse" (i32.const 0) (i32.const 0) (i32.const 5)))
(assert_return (invoke "read1" (i32.const 0)) (i32.const 7))
(assert_return (invoke "read1" (i32.const 4)) (i32.const 7))
(assert_return (invoke "read0" (i32.const 0)) (i32.const 7))
(assert_return (invoke "read2" (i32.const 0)) (i32.const 7))
(assert_return (invoke "reset"))
(assert_return (invoke "flat-copy-self" (i32.const 1) (i32.const 0) (i32.const 4)))
(assert_return (invoke "read1" (i32.const 0)) (i32.const 11))
(assert_return (invoke "read1" (i32.const 1)) (i32.const 11))
(assert_return (invoke "read1" (i32.const 2)) (i32.const 19))
(assert_return (invoke "read1" (i32.const 3)) (i32.const 37))
(assert_return (invoke "read1" (i32.const 4)) (i32.const 53))
(assert_return (invoke "read2" (i32.const 0)) (i32.const 7))
(assert_return (invoke "reset"))
(assert_return (invoke "flat-copy-self" (i32.const 0) (i32.const 1) (i32.const 4)))
(assert_return (invoke "read1" (i32.const 0)) (i32.const 19))
(assert_return (invoke "read1" (i32.const 1)) (i32.const 37))
(assert_return (invoke "read1" (i32.const 2)) (i32.const 53))
(assert_return (invoke "read1" (i32.const 3)) (i32.const 71))
(assert_return (invoke "read1" (i32.const 4)) (i32.const 71))
(assert_return (invoke "read2" (i32.const 0)) (i32.const 7))
(assert_return (invoke "reset"))
(assert_return (invoke "flat-fill-default" (i32.const 1) (i32.const 3)))
(assert_return (invoke "read0" (i32.const 0)) (i32.const 7))
(assert_return (invoke "read0" (i32.const 1)) (i32.const 97))
(assert_return (invoke "read0" (i32.const 3)) (i32.const 97))
(assert_return (invoke "read0" (i32.const 4)) (i32.const 7))
(assert_return (invoke "read2" (i32.const 0)) (i32.const 7))
(assert_return (invoke "reset"))
(assert_return (invoke "flat-fill-numeric" (i32.const 1) (i32.const 3)))
(assert_return (invoke "read0" (i32.const 0)) (i32.const 7))
(assert_return (invoke "read0" (i32.const 1)) (i32.const 97))
(assert_return (invoke "read0" (i32.const 3)) (i32.const 97))
(assert_return (invoke "read0" (i32.const 4)) (i32.const 7))
(assert_return (invoke "read2" (i32.const 0)) (i32.const 7))
(assert_return (invoke "reset"))
(assert_return (invoke "flat-fill-named" (i32.const 1) (i32.const 3)))
(assert_return (invoke "read0" (i32.const 0)) (i32.const 7))
(assert_return (invoke "read0" (i32.const 1)) (i32.const 97))
(assert_return (invoke "read0" (i32.const 3)) (i32.const 97))
(assert_return (invoke "read0" (i32.const 4)) (i32.const 7))
(assert_return (invoke "read2" (i32.const 0)) (i32.const 7))
(assert_return (invoke "reset"))
(assert_return (invoke "flat-fill-src-numeric" (i32.const 1) (i32.const 3)))
(assert_return (invoke "read1" (i32.const 0)) (i32.const 11))
(assert_return (invoke "read1" (i32.const 1)) (i32.const 97))
(assert_return (invoke "read1" (i32.const 3)) (i32.const 97))
(assert_return (invoke "read1" (i32.const 4)) (i32.const 71))
(assert_return (invoke "read2" (i32.const 0)) (i32.const 7))
(assert_return (invoke "reset"))
(assert_return (invoke "flat-fill-src-named" (i32.const 1) (i32.const 3)))
(assert_return (invoke "read1" (i32.const 0)) (i32.const 11))
(assert_return (invoke "read1" (i32.const 1)) (i32.const 97))
(assert_return (invoke "read1" (i32.const 3)) (i32.const 97))
(assert_return (invoke "read1" (i32.const 4)) (i32.const 71))
(assert_return (invoke "read2" (i32.const 0)) (i32.const 7))
(assert_return (invoke "reset"))
(assert_return (invoke "flat-null" (i32.const 1) (i32.const 3)))
(assert_trap (invoke "read0" (i32.const 1)) "uninitialized element")
(assert_trap (invoke "read0" (i32.const 3)) "uninitialized element")
(assert_return (invoke "read0" (i32.const 0)) (i32.const 7))
(assert_return (invoke "read0" (i32.const 4)) (i32.const 7))
(assert_return (invoke "flat-copy-reverse" (i32.const 0) (i32.const 1) (i32.const 3)))
(assert_trap (invoke "read1" (i32.const 0)) "uninitialized element")
(assert_return (invoke "reset"))
(assert_return (invoke "flat-copy-nn" (i32.const 5) (i32.const 5) (i32.const 0)))
(assert_return (invoke "flat-fill-default" (i32.const 5) (i32.const 0)))
(assert_return (invoke "read0" (i32.const 4)) (i32.const 7))
(assert_trap (invoke "flat-copy-nn" (i32.const 4) (i32.const 0) (i32.const 2)) "out of bounds table access")
(assert_return (invoke "read0" (i32.const 0)) (i32.const 7))
(assert_return (invoke "read0" (i32.const 4)) (i32.const 7))
(assert_trap (invoke "flat-copy-nn" (i32.const 0) (i32.const 4) (i32.const 2)) "out of bounds table access")
(assert_return (invoke "read0" (i32.const 0)) (i32.const 7))
(assert_return (invoke "read0" (i32.const 4)) (i32.const 7))
(assert_trap (invoke "flat-copy-nn" (i32.const 6) (i32.const 0) (i32.const 0)) "out of bounds table access")
(assert_return (invoke "read0" (i32.const 0)) (i32.const 7))
(assert_return (invoke "read0" (i32.const 4)) (i32.const 7))
(assert_trap (invoke "flat-copy-nn" (i32.const 0) (i32.const 6) (i32.const 0)) "out of bounds table access")
(assert_return (invoke "read0" (i32.const 0)) (i32.const 7))
(assert_return (invoke "read0" (i32.const 4)) (i32.const 7))
(assert_trap (invoke "flat-copy-nn" (i32.const -1) (i32.const 0) (i32.const 0)) "out of bounds table access")
(assert_return (invoke "read0" (i32.const 0)) (i32.const 7))
(assert_return (invoke "read0" (i32.const 4)) (i32.const 7))
(assert_trap (invoke "flat-copy-nn" (i32.const 0) (i32.const -1) (i32.const 0)) "out of bounds table access")
(assert_return (invoke "read0" (i32.const 0)) (i32.const 7))
(assert_return (invoke "read0" (i32.const 4)) (i32.const 7))
(assert_trap (invoke "flat-fill-default" (i32.const 4) (i32.const 2)) "out of bounds table access")
(assert_return (invoke "read0" (i32.const 4)) (i32.const 7))
(assert_trap (invoke "flat-fill-default" (i32.const 6) (i32.const 0)) "out of bounds table access")
(assert_return (invoke "read0" (i32.const 4)) (i32.const 7))
(assert_trap (invoke "flat-fill-default" (i32.const -1) (i32.const 0)) "out of bounds table access")
(assert_return (invoke "read0" (i32.const 4)) (i32.const 7))
(assert_return (invoke "reset"))
(assert_return (invoke "seed-target"))
(assert_return (invoke "fold-copy-default" (i32.const 1) (i32.const 0) (i32.const 4)))
(assert_return (invoke "read0" (i32.const 0)) (i32.const 11))
(assert_return (invoke "read0" (i32.const 1)) (i32.const 11))
(assert_return (invoke "read0" (i32.const 2)) (i32.const 19))
(assert_return (invoke "read0" (i32.const 3)) (i32.const 37))
(assert_return (invoke "read0" (i32.const 4)) (i32.const 53))
(assert_return (invoke "read2" (i32.const 0)) (i32.const 7))
(assert_return (invoke "reset"))
(assert_return (invoke "seed-target"))
(assert_return (invoke "fold-copy-default" (i32.const 0) (i32.const 1) (i32.const 4)))
(assert_return (invoke "read0" (i32.const 0)) (i32.const 19))
(assert_return (invoke "read0" (i32.const 1)) (i32.const 37))
(assert_return (invoke "read0" (i32.const 2)) (i32.const 53))
(assert_return (invoke "read0" (i32.const 3)) (i32.const 71))
(assert_return (invoke "read0" (i32.const 4)) (i32.const 71))
(assert_return (invoke "read2" (i32.const 0)) (i32.const 7))
(assert_return (invoke "reset"))
(assert_return (invoke "fold-copy-nn" (i32.const 0) (i32.const 0) (i32.const 5)))
(assert_return (invoke "read0" (i32.const 0)) (i32.const 11))
(assert_return (invoke "read0" (i32.const 4)) (i32.const 71))
(assert_return (invoke "read1" (i32.const 0)) (i32.const 11))
(assert_return (invoke "read2" (i32.const 0)) (i32.const 7))
(assert_return (invoke "reset"))
(assert_return (invoke "fold-copy-ni" (i32.const 0) (i32.const 0) (i32.const 5)))
(assert_return (invoke "read0" (i32.const 0)) (i32.const 11))
(assert_return (invoke "read0" (i32.const 4)) (i32.const 71))
(assert_return (invoke "read1" (i32.const 0)) (i32.const 11))
(assert_return (invoke "read2" (i32.const 0)) (i32.const 7))
(assert_return (invoke "reset"))
(assert_return (invoke "fold-copy-in" (i32.const 0) (i32.const 0) (i32.const 5)))
(assert_return (invoke "read0" (i32.const 0)) (i32.const 11))
(assert_return (invoke "read0" (i32.const 4)) (i32.const 71))
(assert_return (invoke "read1" (i32.const 0)) (i32.const 11))
(assert_return (invoke "read2" (i32.const 0)) (i32.const 7))
(assert_return (invoke "reset"))
(assert_return (invoke "fold-copy-ii" (i32.const 0) (i32.const 0) (i32.const 5)))
(assert_return (invoke "read0" (i32.const 0)) (i32.const 11))
(assert_return (invoke "read0" (i32.const 4)) (i32.const 71))
(assert_return (invoke "read1" (i32.const 0)) (i32.const 11))
(assert_return (invoke "read2" (i32.const 0)) (i32.const 7))
(assert_return (invoke "reset"))
(assert_return (invoke "fold-copy-reverse" (i32.const 0) (i32.const 0) (i32.const 5)))
(assert_return (invoke "read1" (i32.const 0)) (i32.const 7))
(assert_return (invoke "read1" (i32.const 4)) (i32.const 7))
(assert_return (invoke "read0" (i32.const 0)) (i32.const 7))
(assert_return (invoke "read2" (i32.const 0)) (i32.const 7))
(assert_return (invoke "reset"))
(assert_return (invoke "fold-copy-self" (i32.const 1) (i32.const 0) (i32.const 4)))
(assert_return (invoke "read1" (i32.const 0)) (i32.const 11))
(assert_return (invoke "read1" (i32.const 1)) (i32.const 11))
(assert_return (invoke "read1" (i32.const 2)) (i32.const 19))
(assert_return (invoke "read1" (i32.const 3)) (i32.const 37))
(assert_return (invoke "read1" (i32.const 4)) (i32.const 53))
(assert_return (invoke "read2" (i32.const 0)) (i32.const 7))
(assert_return (invoke "reset"))
(assert_return (invoke "fold-copy-self" (i32.const 0) (i32.const 1) (i32.const 4)))
(assert_return (invoke "read1" (i32.const 0)) (i32.const 19))
(assert_return (invoke "read1" (i32.const 1)) (i32.const 37))
(assert_return (invoke "read1" (i32.const 2)) (i32.const 53))
(assert_return (invoke "read1" (i32.const 3)) (i32.const 71))
(assert_return (invoke "read1" (i32.const 4)) (i32.const 71))
(assert_return (invoke "read2" (i32.const 0)) (i32.const 7))
(assert_return (invoke "reset"))
(assert_return (invoke "fold-fill-default" (i32.const 1) (i32.const 3)))
(assert_return (invoke "read0" (i32.const 0)) (i32.const 7))
(assert_return (invoke "read0" (i32.const 1)) (i32.const 97))
(assert_return (invoke "read0" (i32.const 3)) (i32.const 97))
(assert_return (invoke "read0" (i32.const 4)) (i32.const 7))
(assert_return (invoke "read2" (i32.const 0)) (i32.const 7))
(assert_return (invoke "reset"))
(assert_return (invoke "fold-fill-numeric" (i32.const 1) (i32.const 3)))
(assert_return (invoke "read0" (i32.const 0)) (i32.const 7))
(assert_return (invoke "read0" (i32.const 1)) (i32.const 97))
(assert_return (invoke "read0" (i32.const 3)) (i32.const 97))
(assert_return (invoke "read0" (i32.const 4)) (i32.const 7))
(assert_return (invoke "read2" (i32.const 0)) (i32.const 7))
(assert_return (invoke "reset"))
(assert_return (invoke "fold-fill-named" (i32.const 1) (i32.const 3)))
(assert_return (invoke "read0" (i32.const 0)) (i32.const 7))
(assert_return (invoke "read0" (i32.const 1)) (i32.const 97))
(assert_return (invoke "read0" (i32.const 3)) (i32.const 97))
(assert_return (invoke "read0" (i32.const 4)) (i32.const 7))
(assert_return (invoke "read2" (i32.const 0)) (i32.const 7))
(assert_return (invoke "reset"))
(assert_return (invoke "fold-fill-src-numeric" (i32.const 1) (i32.const 3)))
(assert_return (invoke "read1" (i32.const 0)) (i32.const 11))
(assert_return (invoke "read1" (i32.const 1)) (i32.const 97))
(assert_return (invoke "read1" (i32.const 3)) (i32.const 97))
(assert_return (invoke "read1" (i32.const 4)) (i32.const 71))
(assert_return (invoke "read2" (i32.const 0)) (i32.const 7))
(assert_return (invoke "reset"))
(assert_return (invoke "fold-fill-src-named" (i32.const 1) (i32.const 3)))
(assert_return (invoke "read1" (i32.const 0)) (i32.const 11))
(assert_return (invoke "read1" (i32.const 1)) (i32.const 97))
(assert_return (invoke "read1" (i32.const 3)) (i32.const 97))
(assert_return (invoke "read1" (i32.const 4)) (i32.const 71))
(assert_return (invoke "read2" (i32.const 0)) (i32.const 7))
(assert_return (invoke "reset"))
(assert_return (invoke "fold-null" (i32.const 1) (i32.const 3)))
(assert_trap (invoke "read0" (i32.const 1)) "uninitialized element")
(assert_trap (invoke "read0" (i32.const 3)) "uninitialized element")
(assert_return (invoke "read0" (i32.const 0)) (i32.const 7))
(assert_return (invoke "read0" (i32.const 4)) (i32.const 7))
(assert_return (invoke "fold-copy-reverse" (i32.const 0) (i32.const 1) (i32.const 3)))
(assert_trap (invoke "read1" (i32.const 0)) "uninitialized element")
(assert_return (invoke "reset"))
(assert_return (invoke "fold-copy-nn" (i32.const 5) (i32.const 5) (i32.const 0)))
(assert_return (invoke "fold-fill-default" (i32.const 5) (i32.const 0)))
(assert_return (invoke "read0" (i32.const 4)) (i32.const 7))
(assert_trap (invoke "fold-copy-nn" (i32.const 4) (i32.const 0) (i32.const 2)) "out of bounds table access")
(assert_return (invoke "read0" (i32.const 0)) (i32.const 7))
(assert_return (invoke "read0" (i32.const 4)) (i32.const 7))
(assert_trap (invoke "fold-copy-nn" (i32.const 0) (i32.const 4) (i32.const 2)) "out of bounds table access")
(assert_return (invoke "read0" (i32.const 0)) (i32.const 7))
(assert_return (invoke "read0" (i32.const 4)) (i32.const 7))
(assert_trap (invoke "fold-copy-nn" (i32.const 6) (i32.const 0) (i32.const 0)) "out of bounds table access")
(assert_return (invoke "read0" (i32.const 0)) (i32.const 7))
(assert_return (invoke "read0" (i32.const 4)) (i32.const 7))
(assert_trap (invoke "fold-copy-nn" (i32.const 0) (i32.const 6) (i32.const 0)) "out of bounds table access")
(assert_return (invoke "read0" (i32.const 0)) (i32.const 7))
(assert_return (invoke "read0" (i32.const 4)) (i32.const 7))
(assert_trap (invoke "fold-copy-nn" (i32.const -1) (i32.const 0) (i32.const 0)) "out of bounds table access")
(assert_return (invoke "read0" (i32.const 0)) (i32.const 7))
(assert_return (invoke "read0" (i32.const 4)) (i32.const 7))
(assert_trap (invoke "fold-copy-nn" (i32.const 0) (i32.const -1) (i32.const 0)) "out of bounds table access")
(assert_return (invoke "read0" (i32.const 0)) (i32.const 7))
(assert_return (invoke "read0" (i32.const 4)) (i32.const 7))
(assert_trap (invoke "fold-fill-default" (i32.const 4) (i32.const 2)) "out of bounds table access")
(assert_return (invoke "read0" (i32.const 4)) (i32.const 7))
(assert_trap (invoke "fold-fill-default" (i32.const 6) (i32.const 0)) "out of bounds table access")
(assert_return (invoke "read0" (i32.const 4)) (i32.const 7))
(assert_trap (invoke "fold-fill-default" (i32.const -1) (i32.const 0)) "out of bounds table access")
(assert_return (invoke "read0" (i32.const 4)) (i32.const 7))

;; i64 offsets and lengths; both spellings preserve table identity and refs.
(module (type $t (func (result i32)))
  (func $seed (type $t) (i32.const 7))
  (func $f0 (type $t) (i32.const 11))
  (func $f1 (type $t) (i32.const 19))
  (func $f2 (type $t) (i32.const 37))
  (func $f3 (type $t) (i32.const 53))
  (func $f4 (type $t) (i32.const 71))
  (func $fill (type $t) (i32.const 97))
  (func (export "reset")
    (table.fill $target (i64.const 0) (ref.func $seed) (i64.const 5))
    (table.fill $peer (i64.const 0) (ref.func $seed) (i64.const 5))
    (table.init $src $pattern (i64.const 0) (i32.const 0) (i32.const 5)))
  (func (export "seed-target") (table.init $target $pattern (i64.const 0) (i32.const 0) (i32.const 5)))
  (func (export "read0") (param i64) (result i32) (call_indirect 0 (type $t) (local.get 0)))
  (func (export "read1") (param i64) (result i32) (call_indirect 1 (type $t) (local.get 0)))
  (func (export "read2") (param i64) (result i32) (call_indirect 2 (type $t) (local.get 0)))
  (func (export "flat-copy-default") (param i64 i64 i64)
    local.get 0 local.get 1 local.get 2 table.copy
  )
  (func (export "flat-copy-nn") (param i64 i64 i64)
    local.get 0 local.get 1 local.get 2 table.copy 0 1
  )
  (func (export "flat-copy-ni") (param i64 i64 i64)
    local.get 0 local.get 1 local.get 2 table.copy 0 $src
  )
  (func (export "flat-copy-in") (param i64 i64 i64)
    local.get 0 local.get 1 local.get 2 table.copy $target 1
  )
  (func (export "flat-copy-ii") (param i64 i64 i64)
    local.get 0 local.get 1 local.get 2 table.copy $target $src
  )
  (func (export "flat-copy-reverse") (param i64 i64 i64)
    local.get 0 local.get 1 local.get 2 table.copy 1 $target
  )
  (func (export "flat-copy-self") (param i64 i64 i64)
    local.get 0 local.get 1 local.get 2 table.copy 1 1
  )
  (func (export "flat-fill-default") (param i64 i64)
    local.get 0 ref.func $fill local.get 1 table.fill
  )
  (func (export "flat-fill-numeric") (param i64 i64)
    local.get 0 ref.func $fill local.get 1 table.fill 0
  )
  (func (export "flat-fill-named") (param i64 i64)
    local.get 0 ref.func $fill local.get 1 table.fill $target
  )
  (func (export "flat-fill-src-numeric") (param i64 i64)
    local.get 0 ref.func $fill local.get 1 table.fill 1
  )
  (func (export "flat-fill-src-named") (param i64 i64)
    local.get 0 ref.func $fill local.get 1 table.fill $src
  )
  (func (export "flat-null") (param i64 i64)
    local.get 0 ref.null func local.get 1 table.fill 0
  )
  (func (export "fold-copy-default") (param i64 i64 i64)
    (table.copy (local.get 0) (local.get 1) (local.get 2))
  )
  (func (export "fold-copy-nn") (param i64 i64 i64)
    (table.copy 0 1 (local.get 0) (local.get 1) (local.get 2))
  )
  (func (export "fold-copy-ni") (param i64 i64 i64)
    (table.copy 0 $src (local.get 0) (local.get 1) (local.get 2))
  )
  (func (export "fold-copy-in") (param i64 i64 i64)
    (table.copy $target 1 (local.get 0) (local.get 1) (local.get 2))
  )
  (func (export "fold-copy-ii") (param i64 i64 i64)
    (table.copy $target $src (local.get 0) (local.get 1) (local.get 2))
  )
  (func (export "fold-copy-reverse") (param i64 i64 i64)
    (table.copy 1 $target (local.get 0) (local.get 1) (local.get 2))
  )
  (func (export "fold-copy-self") (param i64 i64 i64)
    (table.copy 1 1 (local.get 0) (local.get 1) (local.get 2))
  )
  (func (export "fold-fill-default") (param i64 i64)
    (table.fill (local.get 0) (ref.func $fill) (local.get 1))
  )
  (func (export "fold-fill-numeric") (param i64 i64)
    (table.fill 0 (local.get 0) (ref.func $fill) (local.get 1))
  )
  (func (export "fold-fill-named") (param i64 i64)
    (table.fill $target (local.get 0) (ref.func $fill) (local.get 1))
  )
  (func (export "fold-fill-src-numeric") (param i64 i64)
    (table.fill 1 (local.get 0) (ref.func $fill) (local.get 1))
  )
  (func (export "fold-fill-src-named") (param i64 i64)
    (table.fill $src (local.get 0) (ref.func $fill) (local.get 1))
  )
  (func (export "fold-null") (param i64 i64)
    (table.fill 0 (local.get 0) (ref.null func) (local.get 1))
  )
  (table $target i64 5 funcref)
  (table $src i64 5 funcref)
  (table $peer i64 5 funcref)
  (elem $pattern func $f0 $f1 $f2 $f3 $f4)
  (elem declare func $seed $fill)
)
(assert_return (invoke "reset"))
(assert_return (invoke "seed-target"))
(assert_return (invoke "flat-copy-default" (i64.const 1) (i64.const 0) (i64.const 4)))
(assert_return (invoke "read0" (i64.const 0)) (i32.const 11))
(assert_return (invoke "read0" (i64.const 1)) (i32.const 11))
(assert_return (invoke "read0" (i64.const 2)) (i32.const 19))
(assert_return (invoke "read0" (i64.const 3)) (i32.const 37))
(assert_return (invoke "read0" (i64.const 4)) (i32.const 53))
(assert_return (invoke "read2" (i64.const 0)) (i32.const 7))
(assert_return (invoke "reset"))
(assert_return (invoke "seed-target"))
(assert_return (invoke "flat-copy-default" (i64.const 0) (i64.const 1) (i64.const 4)))
(assert_return (invoke "read0" (i64.const 0)) (i32.const 19))
(assert_return (invoke "read0" (i64.const 1)) (i32.const 37))
(assert_return (invoke "read0" (i64.const 2)) (i32.const 53))
(assert_return (invoke "read0" (i64.const 3)) (i32.const 71))
(assert_return (invoke "read0" (i64.const 4)) (i32.const 71))
(assert_return (invoke "read2" (i64.const 0)) (i32.const 7))
(assert_return (invoke "reset"))
(assert_return (invoke "flat-copy-nn" (i64.const 0) (i64.const 0) (i64.const 5)))
(assert_return (invoke "read0" (i64.const 0)) (i32.const 11))
(assert_return (invoke "read0" (i64.const 4)) (i32.const 71))
(assert_return (invoke "read1" (i64.const 0)) (i32.const 11))
(assert_return (invoke "read2" (i64.const 0)) (i32.const 7))
(assert_return (invoke "reset"))
(assert_return (invoke "flat-copy-ni" (i64.const 0) (i64.const 0) (i64.const 5)))
(assert_return (invoke "read0" (i64.const 0)) (i32.const 11))
(assert_return (invoke "read0" (i64.const 4)) (i32.const 71))
(assert_return (invoke "read1" (i64.const 0)) (i32.const 11))
(assert_return (invoke "read2" (i64.const 0)) (i32.const 7))
(assert_return (invoke "reset"))
(assert_return (invoke "flat-copy-in" (i64.const 0) (i64.const 0) (i64.const 5)))
(assert_return (invoke "read0" (i64.const 0)) (i32.const 11))
(assert_return (invoke "read0" (i64.const 4)) (i32.const 71))
(assert_return (invoke "read1" (i64.const 0)) (i32.const 11))
(assert_return (invoke "read2" (i64.const 0)) (i32.const 7))
(assert_return (invoke "reset"))
(assert_return (invoke "flat-copy-ii" (i64.const 0) (i64.const 0) (i64.const 5)))
(assert_return (invoke "read0" (i64.const 0)) (i32.const 11))
(assert_return (invoke "read0" (i64.const 4)) (i32.const 71))
(assert_return (invoke "read1" (i64.const 0)) (i32.const 11))
(assert_return (invoke "read2" (i64.const 0)) (i32.const 7))
(assert_return (invoke "reset"))
(assert_return (invoke "flat-copy-reverse" (i64.const 0) (i64.const 0) (i64.const 5)))
(assert_return (invoke "read1" (i64.const 0)) (i32.const 7))
(assert_return (invoke "read1" (i64.const 4)) (i32.const 7))
(assert_return (invoke "read0" (i64.const 0)) (i32.const 7))
(assert_return (invoke "read2" (i64.const 0)) (i32.const 7))
(assert_return (invoke "reset"))
(assert_return (invoke "flat-copy-self" (i64.const 1) (i64.const 0) (i64.const 4)))
(assert_return (invoke "read1" (i64.const 0)) (i32.const 11))
(assert_return (invoke "read1" (i64.const 1)) (i32.const 11))
(assert_return (invoke "read1" (i64.const 2)) (i32.const 19))
(assert_return (invoke "read1" (i64.const 3)) (i32.const 37))
(assert_return (invoke "read1" (i64.const 4)) (i32.const 53))
(assert_return (invoke "read2" (i64.const 0)) (i32.const 7))
(assert_return (invoke "reset"))
(assert_return (invoke "flat-copy-self" (i64.const 0) (i64.const 1) (i64.const 4)))
(assert_return (invoke "read1" (i64.const 0)) (i32.const 19))
(assert_return (invoke "read1" (i64.const 1)) (i32.const 37))
(assert_return (invoke "read1" (i64.const 2)) (i32.const 53))
(assert_return (invoke "read1" (i64.const 3)) (i32.const 71))
(assert_return (invoke "read1" (i64.const 4)) (i32.const 71))
(assert_return (invoke "read2" (i64.const 0)) (i32.const 7))
(assert_return (invoke "reset"))
(assert_return (invoke "flat-fill-default" (i64.const 1) (i64.const 3)))
(assert_return (invoke "read0" (i64.const 0)) (i32.const 7))
(assert_return (invoke "read0" (i64.const 1)) (i32.const 97))
(assert_return (invoke "read0" (i64.const 3)) (i32.const 97))
(assert_return (invoke "read0" (i64.const 4)) (i32.const 7))
(assert_return (invoke "read2" (i64.const 0)) (i32.const 7))
(assert_return (invoke "reset"))
(assert_return (invoke "flat-fill-numeric" (i64.const 1) (i64.const 3)))
(assert_return (invoke "read0" (i64.const 0)) (i32.const 7))
(assert_return (invoke "read0" (i64.const 1)) (i32.const 97))
(assert_return (invoke "read0" (i64.const 3)) (i32.const 97))
(assert_return (invoke "read0" (i64.const 4)) (i32.const 7))
(assert_return (invoke "read2" (i64.const 0)) (i32.const 7))
(assert_return (invoke "reset"))
(assert_return (invoke "flat-fill-named" (i64.const 1) (i64.const 3)))
(assert_return (invoke "read0" (i64.const 0)) (i32.const 7))
(assert_return (invoke "read0" (i64.const 1)) (i32.const 97))
(assert_return (invoke "read0" (i64.const 3)) (i32.const 97))
(assert_return (invoke "read0" (i64.const 4)) (i32.const 7))
(assert_return (invoke "read2" (i64.const 0)) (i32.const 7))
(assert_return (invoke "reset"))
(assert_return (invoke "flat-fill-src-numeric" (i64.const 1) (i64.const 3)))
(assert_return (invoke "read1" (i64.const 0)) (i32.const 11))
(assert_return (invoke "read1" (i64.const 1)) (i32.const 97))
(assert_return (invoke "read1" (i64.const 3)) (i32.const 97))
(assert_return (invoke "read1" (i64.const 4)) (i32.const 71))
(assert_return (invoke "read2" (i64.const 0)) (i32.const 7))
(assert_return (invoke "reset"))
(assert_return (invoke "flat-fill-src-named" (i64.const 1) (i64.const 3)))
(assert_return (invoke "read1" (i64.const 0)) (i32.const 11))
(assert_return (invoke "read1" (i64.const 1)) (i32.const 97))
(assert_return (invoke "read1" (i64.const 3)) (i32.const 97))
(assert_return (invoke "read1" (i64.const 4)) (i32.const 71))
(assert_return (invoke "read2" (i64.const 0)) (i32.const 7))
(assert_return (invoke "reset"))
(assert_return (invoke "flat-null" (i64.const 1) (i64.const 3)))
(assert_trap (invoke "read0" (i64.const 1)) "uninitialized element")
(assert_trap (invoke "read0" (i64.const 3)) "uninitialized element")
(assert_return (invoke "read0" (i64.const 0)) (i32.const 7))
(assert_return (invoke "read0" (i64.const 4)) (i32.const 7))
(assert_return (invoke "flat-copy-reverse" (i64.const 0) (i64.const 1) (i64.const 3)))
(assert_trap (invoke "read1" (i64.const 0)) "uninitialized element")
(assert_return (invoke "reset"))
(assert_return (invoke "flat-copy-nn" (i64.const 5) (i64.const 5) (i64.const 0)))
(assert_return (invoke "flat-fill-default" (i64.const 5) (i64.const 0)))
(assert_return (invoke "read0" (i64.const 4)) (i32.const 7))
(assert_trap (invoke "flat-copy-nn" (i64.const 4) (i64.const 0) (i64.const 2)) "out of bounds table access")
(assert_return (invoke "read0" (i64.const 0)) (i32.const 7))
(assert_return (invoke "read0" (i64.const 4)) (i32.const 7))
(assert_trap (invoke "flat-copy-nn" (i64.const 0) (i64.const 4) (i64.const 2)) "out of bounds table access")
(assert_return (invoke "read0" (i64.const 0)) (i32.const 7))
(assert_return (invoke "read0" (i64.const 4)) (i32.const 7))
(assert_trap (invoke "flat-copy-nn" (i64.const 6) (i64.const 0) (i64.const 0)) "out of bounds table access")
(assert_return (invoke "read0" (i64.const 0)) (i32.const 7))
(assert_return (invoke "read0" (i64.const 4)) (i32.const 7))
(assert_trap (invoke "flat-copy-nn" (i64.const 0) (i64.const 6) (i64.const 0)) "out of bounds table access")
(assert_return (invoke "read0" (i64.const 0)) (i32.const 7))
(assert_return (invoke "read0" (i64.const 4)) (i32.const 7))
(assert_trap (invoke "flat-copy-nn" (i64.const -1) (i64.const 0) (i64.const 0)) "out of bounds table access")
(assert_return (invoke "read0" (i64.const 0)) (i32.const 7))
(assert_return (invoke "read0" (i64.const 4)) (i32.const 7))
(assert_trap (invoke "flat-copy-nn" (i64.const 0) (i64.const -1) (i64.const 0)) "out of bounds table access")
(assert_return (invoke "read0" (i64.const 0)) (i32.const 7))
(assert_return (invoke "read0" (i64.const 4)) (i32.const 7))
(assert_trap (invoke "flat-fill-default" (i64.const 4) (i64.const 2)) "out of bounds table access")
(assert_return (invoke "read0" (i64.const 4)) (i32.const 7))
(assert_trap (invoke "flat-fill-default" (i64.const 6) (i64.const 0)) "out of bounds table access")
(assert_return (invoke "read0" (i64.const 4)) (i32.const 7))
(assert_trap (invoke "flat-fill-default" (i64.const -1) (i64.const 0)) "out of bounds table access")
(assert_return (invoke "read0" (i64.const 4)) (i32.const 7))
(assert_trap (invoke "flat-copy-nn" (i64.const 4294967296) (i64.const 0) (i64.const 0)) "out of bounds table access")
(assert_trap (invoke "flat-copy-nn" (i64.const 0) (i64.const 4294967296) (i64.const 0)) "out of bounds table access")
(assert_trap (invoke "flat-copy-nn" (i64.const 0) (i64.const 0) (i64.const 4294967296)) "out of bounds table access")
(assert_trap (invoke "flat-fill-default" (i64.const 0) (i64.const 4294967296)) "out of bounds table access")
(assert_return (invoke "reset"))
(assert_return (invoke "seed-target"))
(assert_return (invoke "fold-copy-default" (i64.const 1) (i64.const 0) (i64.const 4)))
(assert_return (invoke "read0" (i64.const 0)) (i32.const 11))
(assert_return (invoke "read0" (i64.const 1)) (i32.const 11))
(assert_return (invoke "read0" (i64.const 2)) (i32.const 19))
(assert_return (invoke "read0" (i64.const 3)) (i32.const 37))
(assert_return (invoke "read0" (i64.const 4)) (i32.const 53))
(assert_return (invoke "read2" (i64.const 0)) (i32.const 7))
(assert_return (invoke "reset"))
(assert_return (invoke "seed-target"))
(assert_return (invoke "fold-copy-default" (i64.const 0) (i64.const 1) (i64.const 4)))
(assert_return (invoke "read0" (i64.const 0)) (i32.const 19))
(assert_return (invoke "read0" (i64.const 1)) (i32.const 37))
(assert_return (invoke "read0" (i64.const 2)) (i32.const 53))
(assert_return (invoke "read0" (i64.const 3)) (i32.const 71))
(assert_return (invoke "read0" (i64.const 4)) (i32.const 71))
(assert_return (invoke "read2" (i64.const 0)) (i32.const 7))
(assert_return (invoke "reset"))
(assert_return (invoke "fold-copy-nn" (i64.const 0) (i64.const 0) (i64.const 5)))
(assert_return (invoke "read0" (i64.const 0)) (i32.const 11))
(assert_return (invoke "read0" (i64.const 4)) (i32.const 71))
(assert_return (invoke "read1" (i64.const 0)) (i32.const 11))
(assert_return (invoke "read2" (i64.const 0)) (i32.const 7))
(assert_return (invoke "reset"))
(assert_return (invoke "fold-copy-ni" (i64.const 0) (i64.const 0) (i64.const 5)))
(assert_return (invoke "read0" (i64.const 0)) (i32.const 11))
(assert_return (invoke "read0" (i64.const 4)) (i32.const 71))
(assert_return (invoke "read1" (i64.const 0)) (i32.const 11))
(assert_return (invoke "read2" (i64.const 0)) (i32.const 7))
(assert_return (invoke "reset"))
(assert_return (invoke "fold-copy-in" (i64.const 0) (i64.const 0) (i64.const 5)))
(assert_return (invoke "read0" (i64.const 0)) (i32.const 11))
(assert_return (invoke "read0" (i64.const 4)) (i32.const 71))
(assert_return (invoke "read1" (i64.const 0)) (i32.const 11))
(assert_return (invoke "read2" (i64.const 0)) (i32.const 7))
(assert_return (invoke "reset"))
(assert_return (invoke "fold-copy-ii" (i64.const 0) (i64.const 0) (i64.const 5)))
(assert_return (invoke "read0" (i64.const 0)) (i32.const 11))
(assert_return (invoke "read0" (i64.const 4)) (i32.const 71))
(assert_return (invoke "read1" (i64.const 0)) (i32.const 11))
(assert_return (invoke "read2" (i64.const 0)) (i32.const 7))
(assert_return (invoke "reset"))
(assert_return (invoke "fold-copy-reverse" (i64.const 0) (i64.const 0) (i64.const 5)))
(assert_return (invoke "read1" (i64.const 0)) (i32.const 7))
(assert_return (invoke "read1" (i64.const 4)) (i32.const 7))
(assert_return (invoke "read0" (i64.const 0)) (i32.const 7))
(assert_return (invoke "read2" (i64.const 0)) (i32.const 7))
(assert_return (invoke "reset"))
(assert_return (invoke "fold-copy-self" (i64.const 1) (i64.const 0) (i64.const 4)))
(assert_return (invoke "read1" (i64.const 0)) (i32.const 11))
(assert_return (invoke "read1" (i64.const 1)) (i32.const 11))
(assert_return (invoke "read1" (i64.const 2)) (i32.const 19))
(assert_return (invoke "read1" (i64.const 3)) (i32.const 37))
(assert_return (invoke "read1" (i64.const 4)) (i32.const 53))
(assert_return (invoke "read2" (i64.const 0)) (i32.const 7))
(assert_return (invoke "reset"))
(assert_return (invoke "fold-copy-self" (i64.const 0) (i64.const 1) (i64.const 4)))
(assert_return (invoke "read1" (i64.const 0)) (i32.const 19))
(assert_return (invoke "read1" (i64.const 1)) (i32.const 37))
(assert_return (invoke "read1" (i64.const 2)) (i32.const 53))
(assert_return (invoke "read1" (i64.const 3)) (i32.const 71))
(assert_return (invoke "read1" (i64.const 4)) (i32.const 71))
(assert_return (invoke "read2" (i64.const 0)) (i32.const 7))
(assert_return (invoke "reset"))
(assert_return (invoke "fold-fill-default" (i64.const 1) (i64.const 3)))
(assert_return (invoke "read0" (i64.const 0)) (i32.const 7))
(assert_return (invoke "read0" (i64.const 1)) (i32.const 97))
(assert_return (invoke "read0" (i64.const 3)) (i32.const 97))
(assert_return (invoke "read0" (i64.const 4)) (i32.const 7))
(assert_return (invoke "read2" (i64.const 0)) (i32.const 7))
(assert_return (invoke "reset"))
(assert_return (invoke "fold-fill-numeric" (i64.const 1) (i64.const 3)))
(assert_return (invoke "read0" (i64.const 0)) (i32.const 7))
(assert_return (invoke "read0" (i64.const 1)) (i32.const 97))
(assert_return (invoke "read0" (i64.const 3)) (i32.const 97))
(assert_return (invoke "read0" (i64.const 4)) (i32.const 7))
(assert_return (invoke "read2" (i64.const 0)) (i32.const 7))
(assert_return (invoke "reset"))
(assert_return (invoke "fold-fill-named" (i64.const 1) (i64.const 3)))
(assert_return (invoke "read0" (i64.const 0)) (i32.const 7))
(assert_return (invoke "read0" (i64.const 1)) (i32.const 97))
(assert_return (invoke "read0" (i64.const 3)) (i32.const 97))
(assert_return (invoke "read0" (i64.const 4)) (i32.const 7))
(assert_return (invoke "read2" (i64.const 0)) (i32.const 7))
(assert_return (invoke "reset"))
(assert_return (invoke "fold-fill-src-numeric" (i64.const 1) (i64.const 3)))
(assert_return (invoke "read1" (i64.const 0)) (i32.const 11))
(assert_return (invoke "read1" (i64.const 1)) (i32.const 97))
(assert_return (invoke "read1" (i64.const 3)) (i32.const 97))
(assert_return (invoke "read1" (i64.const 4)) (i32.const 71))
(assert_return (invoke "read2" (i64.const 0)) (i32.const 7))
(assert_return (invoke "reset"))
(assert_return (invoke "fold-fill-src-named" (i64.const 1) (i64.const 3)))
(assert_return (invoke "read1" (i64.const 0)) (i32.const 11))
(assert_return (invoke "read1" (i64.const 1)) (i32.const 97))
(assert_return (invoke "read1" (i64.const 3)) (i32.const 97))
(assert_return (invoke "read1" (i64.const 4)) (i32.const 71))
(assert_return (invoke "read2" (i64.const 0)) (i32.const 7))
(assert_return (invoke "reset"))
(assert_return (invoke "fold-null" (i64.const 1) (i64.const 3)))
(assert_trap (invoke "read0" (i64.const 1)) "uninitialized element")
(assert_trap (invoke "read0" (i64.const 3)) "uninitialized element")
(assert_return (invoke "read0" (i64.const 0)) (i32.const 7))
(assert_return (invoke "read0" (i64.const 4)) (i32.const 7))
(assert_return (invoke "fold-copy-reverse" (i64.const 0) (i64.const 1) (i64.const 3)))
(assert_trap (invoke "read1" (i64.const 0)) "uninitialized element")
(assert_return (invoke "reset"))
(assert_return (invoke "fold-copy-nn" (i64.const 5) (i64.const 5) (i64.const 0)))
(assert_return (invoke "fold-fill-default" (i64.const 5) (i64.const 0)))
(assert_return (invoke "read0" (i64.const 4)) (i32.const 7))
(assert_trap (invoke "fold-copy-nn" (i64.const 4) (i64.const 0) (i64.const 2)) "out of bounds table access")
(assert_return (invoke "read0" (i64.const 0)) (i32.const 7))
(assert_return (invoke "read0" (i64.const 4)) (i32.const 7))
(assert_trap (invoke "fold-copy-nn" (i64.const 0) (i64.const 4) (i64.const 2)) "out of bounds table access")
(assert_return (invoke "read0" (i64.const 0)) (i32.const 7))
(assert_return (invoke "read0" (i64.const 4)) (i32.const 7))
(assert_trap (invoke "fold-copy-nn" (i64.const 6) (i64.const 0) (i64.const 0)) "out of bounds table access")
(assert_return (invoke "read0" (i64.const 0)) (i32.const 7))
(assert_return (invoke "read0" (i64.const 4)) (i32.const 7))
(assert_trap (invoke "fold-copy-nn" (i64.const 0) (i64.const 6) (i64.const 0)) "out of bounds table access")
(assert_return (invoke "read0" (i64.const 0)) (i32.const 7))
(assert_return (invoke "read0" (i64.const 4)) (i32.const 7))
(assert_trap (invoke "fold-copy-nn" (i64.const -1) (i64.const 0) (i64.const 0)) "out of bounds table access")
(assert_return (invoke "read0" (i64.const 0)) (i32.const 7))
(assert_return (invoke "read0" (i64.const 4)) (i32.const 7))
(assert_trap (invoke "fold-copy-nn" (i64.const 0) (i64.const -1) (i64.const 0)) "out of bounds table access")
(assert_return (invoke "read0" (i64.const 0)) (i32.const 7))
(assert_return (invoke "read0" (i64.const 4)) (i32.const 7))
(assert_trap (invoke "fold-fill-default" (i64.const 4) (i64.const 2)) "out of bounds table access")
(assert_return (invoke "read0" (i64.const 4)) (i32.const 7))
(assert_trap (invoke "fold-fill-default" (i64.const 6) (i64.const 0)) "out of bounds table access")
(assert_return (invoke "read0" (i64.const 4)) (i32.const 7))
(assert_trap (invoke "fold-fill-default" (i64.const -1) (i64.const 0)) "out of bounds table access")
(assert_return (invoke "read0" (i64.const 4)) (i32.const 7))
(assert_trap (invoke "fold-copy-nn" (i64.const 4294967296) (i64.const 0) (i64.const 0)) "out of bounds table access")
(assert_trap (invoke "fold-copy-nn" (i64.const 0) (i64.const 4294967296) (i64.const 0)) "out of bounds table access")
(assert_trap (invoke "fold-copy-nn" (i64.const 0) (i64.const 0) (i64.const 4294967296)) "out of bounds table access")
(assert_trap (invoke "fold-fill-default" (i64.const 0) (i64.const 4294967296)) "out of bounds table access")

;; Mixed address widths retain an i32 count in either copy direction.
(module (func $a (result i32) (i32.const 11)) (func $b (result i32) (i32.const 29))
  (func $c (result i32) (i32.const 53)) (func $d (result i32) (i32.const 71))
  (table $small 2 funcref) (table $wide i64 2 funcref)
  (elem $small-data func $a $b) (elem $wide-data func $c $d)
  (func (export "reset") (table.init $small $small-data (i32.const 0) (i32.const 0) (i32.const 2))
    (table.init $wide $wide-data (i64.const 0) (i32.const 0) (i32.const 2)))
  (func (export "flat-to-small") (i32.const 0) (i64.const 1) (i32.const 1) table.copy 0 $wide)
  (func (export "flat-to-wide") (i64.const 0) (i32.const 1) (i32.const 1) table.copy $wide 0)
  (func (export "fold-to-small") (table.copy 0 $wide (i32.const 0) (i64.const 1) (i32.const 1)))
  (func (export "fold-to-wide") (table.copy $wide 0 (i64.const 0) (i32.const 1) (i32.const 1)))
  (func (export "small") (result i32) (call_indirect $small (result i32) (i32.const 0)))
  (func (export "wide") (result i32) (call_indirect $wide (result i32) (i64.const 0)))
)
(assert_return (invoke "reset"))
(assert_return (invoke "flat-to-small"))
(assert_return (invoke "small") (i32.const 71))
(assert_return (invoke "wide") (i32.const 53))
(assert_return (invoke "reset"))
(assert_return (invoke "flat-to-wide"))
(assert_return (invoke "wide") (i32.const 29))
(assert_return (invoke "small") (i32.const 11))
(assert_return (invoke "reset"))
(assert_return (invoke "fold-to-small"))
(assert_return (invoke "small") (i32.const 71))
(assert_return (invoke "wide") (i32.const 53))
(assert_return (invoke "reset"))
(assert_return (invoke "fold-to-wide"))
(assert_return (invoke "wide") (i32.const 29))
(assert_return (invoke "small") (i32.const 11))

;; Externref fill and copy preserve identity, including null replacements.
(module (table $e 2 externref)
  (func (export "fill") (param externref) i32.const 0 local.get 0 i32.const 2 table.fill)
  (func (export "null") (table.fill 0 (i32.const 1) (ref.null extern) (i32.const 1)))
  (func (export "copy") i32.const 1 i32.const 0 i32.const 1 table.copy 0 0)
  (func (export "get") (param i32) (result externref) (table.get $e (local.get 0)))
)
(assert_return (invoke "fill" (ref.extern 17)))
(assert_return (invoke "get" (i32.const 0)) (ref.extern 17))
(assert_return (invoke "get" (i32.const 1)) (ref.extern 17))
(assert_return (invoke "null"))
(assert_return (invoke "get" (i32.const 0)) (ref.extern 17))
(assert_return (invoke "get" (i32.const 1)) (ref.null extern))
(assert_return (invoke "copy"))
(assert_return (invoke "get" (i32.const 1)) (ref.extern 17))

;; Non-null tables accept non-null fill and compatible copies.
(module (func $f (result i32) (i32.const 11)) (func $g (result i32) (i32.const 29))
  (table $n 2 (ref func) (ref.func $f)) (elem declare func $g)
  (func (export "fill") i32.const 0 ref.func $g i32.const 1 table.fill $n)
  (func (export "copy") (table.copy 0 0 (i32.const 1) (i32.const 0) (i32.const 1)))
  (func (export "call") (param i32) (result i32) (call_indirect $n (result i32) (local.get 0)))
)
(assert_return (invoke "fill"))
(assert_return (invoke "call" (i32.const 0)) (i32.const 29))
(assert_return (invoke "call" (i32.const 1)) (i32.const 11))
(assert_return (invoke "copy"))
(assert_return (invoke "call" (i32.const 1)) (i32.const 29))

;; Foreign function owners survive copy, and fill can publish a consumer ref.
(module $provider (func $f (result i32) (i32.const 29))
  (table 1 funcref) (export "source" (table 0)) (elem (i32.const 0) $f)
  (func (export "call") (result i32) (call_indirect (result i32) (i32.const 0))))
(register "copy-provider")
(module $consumer (table $source (import "copy-provider" "source") 1 funcref)
  (func $own (result i32) (i32.const 97)) (table $target 1 funcref) (elem (table $target) (i32.const 0) func $own)
  (func (export "copy") i32.const 0 i32.const 0 i32.const 1 table.copy $target $source)
  (func (export "fill") i32.const 0 ref.func $own i32.const 1 table.fill $source)
  (func (export "call") (result i32) (call_indirect $target (result i32) (i32.const 0))))
(assert_return (invoke "call") (i32.const 97))
(assert_return (invoke "copy"))
(assert_return (invoke "call") (i32.const 29))
(assert_return (invoke "fill"))
(assert_return (invoke $provider "call") (i32.const 97))

;; Invalid modules and malformed text must reject without losing an operator.
(assert_invalid (module (table $t 1 funcref) (func (i32.const 0) (i32.const 0) (i32.const 0) table.copy 2 0)) "unknown table")
(assert_invalid (module (table $t 1 funcref) (func (i32.const 0) (i32.const 0) (i32.const 0) table.copy 0 2)) "unknown table")
(assert_invalid (module (table $t 1 funcref) (func (i32.const 0) (ref.null func) (i32.const 0) table.fill 2)) "unknown table")
(assert_invalid (module (table $t 1 funcref) (func (i32.const 0) (ref.null extern) (i32.const 0) table.fill 0)) "type mismatch")
(assert_invalid (module (table $t 1 funcref) (func  table.copy 0 0)) "type mismatch")
(assert_invalid (module (table $t 1 funcref) (func  table.fill 0)) "type mismatch")
(assert_invalid (module (table $t 1 funcref) (func  table.fill $t)) "type mismatch")
(assert_invalid (module (table i64 1 funcref) (func (i64.const 0) (i64.const 0) (i32.const 0) table.copy 0 0)) "type mismatch")
(assert_invalid (module (table i64 1 funcref) (func (i32.const 0) (ref.null func) (i64.const 0) table.fill 0)) "type mismatch")
(assert_invalid (module (table i64 1 funcref) (func (i64.const 0) (ref.null func) (i32.const 0) table.fill 0)) "type mismatch")
(assert_invalid (module (table 1 funcref) (table i64 1 funcref) (func (i32.const 0) (i64.const 0) (i64.const 0) table.copy 0 1)) "type mismatch")
(assert_invalid (module (func $f) (table $n 1 (ref func) (ref.func $f)) (table $p 1 funcref) (func (i32.const 0) (i32.const 0) (i32.const 0) table.copy $n $p)) "type mismatch")
(assert_invalid (module (func $f) (table $n 1 (ref func) (ref.func $f)) (func (i32.const 0) (ref.null func) (i32.const 0) table.fill $n)) "type mismatch")
(assert_invalid (module (table $t 1 funcref) (func (table.copy 2 0 (i32.const 0) (i32.const 0) (i32.const 0)))) "unknown table")
(assert_invalid (module (table $t 1 funcref) (func (table.copy 0 2 (i32.const 0) (i32.const 0) (i32.const 0)))) "unknown table")
(assert_invalid (module (table $t 1 funcref) (func (table.fill 2 (i32.const 0) (ref.null func) (i32.const 0)))) "unknown table")
(assert_invalid (module (table $t 1 funcref) (func (table.fill 0 (i32.const 0) (ref.null extern) (i32.const 0)))) "type mismatch")
(assert_invalid (module (table $t 1 funcref) (func (table.copy 0 0 ))) "type mismatch")
(assert_invalid (module (table $t 1 funcref) (func (table.fill 0 ))) "type mismatch")
(assert_invalid (module (table $t 1 funcref) (func (table.fill $t ))) "type mismatch")
(assert_invalid (module (table i64 1 funcref) (func (table.copy 0 0 (i64.const 0) (i64.const 0) (i32.const 0)))) "type mismatch")
(assert_invalid (module (table i64 1 funcref) (func (table.fill 0 (i32.const 0) (ref.null func) (i64.const 0)))) "type mismatch")
(assert_invalid (module (table i64 1 funcref) (func (table.fill 0 (i64.const 0) (ref.null func) (i32.const 0)))) "type mismatch")
(assert_invalid (module (table 1 funcref) (table i64 1 funcref) (func (table.copy 0 1 (i32.const 0) (i64.const 0) (i64.const 0)))) "type mismatch")
(assert_invalid (module (func $f) (table $n 1 (ref func) (ref.func $f)) (table $p 1 funcref) (func (table.copy $n $p (i32.const 0) (i32.const 0) (i32.const 0)))) "type mismatch")
(assert_invalid (module (func $f) (table $n 1 (ref func) (ref.func $f)) (func (table.fill $n (i32.const 0) (ref.null func) (i32.const 0)))) "type mismatch")
(assert_malformed (module quote "(module (table 1 funcref) (func table.copy 0))") "unexpected token")
(assert_malformed (module quote "(module (table 1 funcref) (func table.copy $absent 0))") "unknown table")
(assert_malformed (module quote "(module (table 1 funcref) (func table.fill $absent))") "unknown table")
