(module $provider
  (type $result (func (result i32)))
  (func $eleven (type $result) (i32.const 11))
  (func $twenty_two (type $result) (i32.const 22))
  (table $narrow (export "narrow") funcref (elem $eleven $twenty_two))
  (table $wide (export "wide") i64 funcref (elem $twenty_two))
  (func (export "call-narrow") (param i32) (result i32)
    (call_indirect $narrow (type $result) (local.get 0)))
  (func (export "call-wide") (param i64) (result i32)
    (call_indirect $wide (type $result) (local.get 0))))
(register "provider")
(module $consumer
  (type $result (func (result i32)))
  (table $alias (import "provider" "narrow") 2 funcref)
  (func (export "call") (param i32) (result i32)
    (call_indirect $alias (type $result) (local.get 0))))
(assert_return (invoke $provider "call-narrow" (i32.const 0)) (i32.const 11))
(assert_return (invoke $provider "call-narrow" (i32.const 1)) (i32.const 22))
(assert_return (invoke $provider "call-wide" (i64.const 0)) (i32.const 22))
(assert_return (invoke $consumer "call" (i32.const 1)) (i32.const 22))
