;; Plain/folded bulk instructions must preserve both index spaces and drops.

;; i32 table and memory addressing; segment/source/count indices stay i32.
(module
  (type $t (func (result i32)))
  (table $base 2 funcref)
  (table $other 2 funcref)
  (memory 1)
  (func $seed (type $t) (i32.const 7))
  (func $f (type $t) (i32.const 11))
  (func $g (type $t) (i32.const 29))
  (func (export "reset")
    (table.set $base (i32.const 0) (ref.func $seed))
    (table.set $other (i32.const 0) (ref.func $seed))
  )
  (func (export "call0") (result i32) (call_indirect 0 (type $t) (i32.const 0)))
  (func (export "call1") (result i32) (call_indirect 1 (type $t) (i32.const 0)))
  (func (export "flat-numeric")
    i32.const 0 i32.const 0 i32.const 1 table.init 0
  )
  (func (export "flat-named")
    i32.const 0 i32.const 0 i32.const 1 table.init $a
  )
  (func (export "flat-nn")
    i32.const 0 i32.const 0 i32.const 1 table.init 1 0
  )
  (func (export "flat-ni")
    i32.const 0 i32.const 0 i32.const 1 table.init 1 $a
  )
  (func (export "flat-in")
    i32.const 0 i32.const 0 i32.const 1 table.init $other 0
  )
  (func (export "flat-ii")
    i32.const 0 i32.const 0 i32.const 1 table.init $other $a
  )
  (func (export "flat-second")
    i32.const 0 i32.const 0 i32.const 1 table.init $b
  )
  (func (export "flat-second-nn")
    i32.const 0 i32.const 0 i32.const 1 table.init 1 1
  )
  (func (export "fold-numeric")
    (table.init 0 (i32.const 0) (i32.const 0) (i32.const 1))
  )
  (func (export "fold-named")
    (table.init $a (i32.const 0) (i32.const 0) (i32.const 1))
  )
  (func (export "fold-nn")
    (table.init 1 0 (i32.const 0) (i32.const 0) (i32.const 1))
  )
  (func (export "fold-ni")
    (table.init 1 $a (i32.const 0) (i32.const 0) (i32.const 1))
  )
  (func (export "fold-in")
    (table.init $other 0 (i32.const 0) (i32.const 0) (i32.const 1))
  )
  (func (export "fold-ii")
    (table.init $other $a (i32.const 0) (i32.const 0) (i32.const 1))
  )
  (func (export "fold-second")
    (table.init $b (i32.const 0) (i32.const 0) (i32.const 1))
  )
  (func (export "fold-second-nn")
    (table.init 1 1 (i32.const 0) (i32.const 0) (i32.const 1))
  )
  (func (export "data-a-flat") data.drop 0)
  (func (export "data-a-fold") (data.drop $d0))
  (func (export "data-b-flat") data.drop $d1)
  (func (export "data-b-fold") (data.drop 1))
  (func (export "elem-a-flat") elem.drop 0)
  (func (export "elem-a-fold") (elem.drop $a))
  (func (export "elem-b-flat") elem.drop $b)
  (func (export "elem-b-fold") (elem.drop 1))
  (func (export "data-init0") (result i32)
    i32.const 0 i32.const 0 i32.const 1 memory.init 0
    (i32.load8_u (i32.const 0)))
  (func (export "data-zero0") i32.const 0 i32.const 0 i32.const 0 memory.init 0)
  (func (export "elem-zero0") i32.const 0 i32.const 0 i32.const 0 table.init 0)
  (func (export "data-init1") (result i32)
    i32.const 0 i32.const 0 i32.const 1 memory.init 1
    (i32.load8_u (i32.const 0)))
  (func (export "data-zero1") i32.const 0 i32.const 0 i32.const 0 memory.init 1)
  (func (export "elem-zero1") i32.const 0 i32.const 0 i32.const 0 table.init 1)
  (elem $a func $f)
  (elem $b func $g)
  (elem declare func $seed)
  (data $d0 "x")
  (data $d1 "Y")
)
(assert_return (invoke "reset"))
(assert_return (invoke "flat-numeric"))
(assert_return (invoke "call0") (i32.const 11))
(assert_return (invoke "call1") (i32.const 7))
(assert_return (invoke "reset"))
(assert_return (invoke "flat-named"))
(assert_return (invoke "call0") (i32.const 11))
(assert_return (invoke "call1") (i32.const 7))
(assert_return (invoke "reset"))
(assert_return (invoke "flat-nn"))
(assert_return (invoke "call1") (i32.const 11))
(assert_return (invoke "call0") (i32.const 7))
(assert_return (invoke "reset"))
(assert_return (invoke "flat-ni"))
(assert_return (invoke "call1") (i32.const 11))
(assert_return (invoke "call0") (i32.const 7))
(assert_return (invoke "reset"))
(assert_return (invoke "flat-in"))
(assert_return (invoke "call1") (i32.const 11))
(assert_return (invoke "call0") (i32.const 7))
(assert_return (invoke "reset"))
(assert_return (invoke "flat-ii"))
(assert_return (invoke "call1") (i32.const 11))
(assert_return (invoke "call0") (i32.const 7))
(assert_return (invoke "reset"))
(assert_return (invoke "flat-second"))
(assert_return (invoke "call0") (i32.const 29))
(assert_return (invoke "call1") (i32.const 7))
(assert_return (invoke "reset"))
(assert_return (invoke "flat-second-nn"))
(assert_return (invoke "call1") (i32.const 29))
(assert_return (invoke "call0") (i32.const 7))
(assert_return (invoke "reset"))
(assert_return (invoke "fold-numeric"))
(assert_return (invoke "call0") (i32.const 11))
(assert_return (invoke "call1") (i32.const 7))
(assert_return (invoke "reset"))
(assert_return (invoke "fold-named"))
(assert_return (invoke "call0") (i32.const 11))
(assert_return (invoke "call1") (i32.const 7))
(assert_return (invoke "reset"))
(assert_return (invoke "fold-nn"))
(assert_return (invoke "call1") (i32.const 11))
(assert_return (invoke "call0") (i32.const 7))
(assert_return (invoke "reset"))
(assert_return (invoke "fold-ni"))
(assert_return (invoke "call1") (i32.const 11))
(assert_return (invoke "call0") (i32.const 7))
(assert_return (invoke "reset"))
(assert_return (invoke "fold-in"))
(assert_return (invoke "call1") (i32.const 11))
(assert_return (invoke "call0") (i32.const 7))
(assert_return (invoke "reset"))
(assert_return (invoke "fold-ii"))
(assert_return (invoke "call1") (i32.const 11))
(assert_return (invoke "call0") (i32.const 7))
(assert_return (invoke "reset"))
(assert_return (invoke "fold-second"))
(assert_return (invoke "call0") (i32.const 29))
(assert_return (invoke "call1") (i32.const 7))
(assert_return (invoke "reset"))
(assert_return (invoke "fold-second-nn"))
(assert_return (invoke "call1") (i32.const 29))
(assert_return (invoke "call0") (i32.const 7))
(assert_return (invoke "data-init0") (i32.const 120))
(assert_return (invoke "data-init1") (i32.const 89))
(assert_return (invoke "data-a-flat"))
(assert_return (invoke "data-a-fold"))
(assert_trap (invoke "data-init0") "out of bounds memory access")
(assert_return (invoke "data-zero0"))
(assert_return (invoke "data-b-flat"))
(assert_return (invoke "data-b-fold"))
(assert_trap (invoke "data-init1") "out of bounds memory access")
(assert_return (invoke "data-zero1"))
(assert_return (invoke "elem-a-flat"))
(assert_return (invoke "elem-a-fold"))
(assert_trap (invoke "flat-numeric") "out of bounds table access")
(assert_return (invoke "elem-zero0"))
(assert_return (invoke "elem-b-flat"))
(assert_return (invoke "elem-b-fold"))
(assert_trap (invoke "flat-second") "out of bounds table access")
(assert_return (invoke "elem-zero1"))

;; i64 table and memory addressing; segment/source/count indices stay i32.
(module
  (type $t (func (result i32)))
  (table $base i64 2 funcref)
  (table $other i64 2 funcref)
  (memory i64 1)
  (func $seed (type $t) (i32.const 7))
  (func $f (type $t) (i32.const 11))
  (func $g (type $t) (i32.const 29))
  (func (export "reset")
    (table.set $base (i64.const 0) (ref.func $seed))
    (table.set $other (i64.const 0) (ref.func $seed))
  )
  (func (export "call0") (result i32) (call_indirect 0 (type $t) (i64.const 0)))
  (func (export "call1") (result i32) (call_indirect 1 (type $t) (i64.const 0)))
  (func (export "flat-numeric")
    i64.const 0 i32.const 0 i32.const 1 table.init 0
  )
  (func (export "flat-named")
    i64.const 0 i32.const 0 i32.const 1 table.init $a
  )
  (func (export "flat-nn")
    i64.const 0 i32.const 0 i32.const 1 table.init 1 0
  )
  (func (export "flat-ni")
    i64.const 0 i32.const 0 i32.const 1 table.init 1 $a
  )
  (func (export "flat-in")
    i64.const 0 i32.const 0 i32.const 1 table.init $other 0
  )
  (func (export "flat-ii")
    i64.const 0 i32.const 0 i32.const 1 table.init $other $a
  )
  (func (export "flat-second")
    i64.const 0 i32.const 0 i32.const 1 table.init $b
  )
  (func (export "flat-second-nn")
    i64.const 0 i32.const 0 i32.const 1 table.init 1 1
  )
  (func (export "fold-numeric")
    (table.init 0 (i64.const 0) (i32.const 0) (i32.const 1))
  )
  (func (export "fold-named")
    (table.init $a (i64.const 0) (i32.const 0) (i32.const 1))
  )
  (func (export "fold-nn")
    (table.init 1 0 (i64.const 0) (i32.const 0) (i32.const 1))
  )
  (func (export "fold-ni")
    (table.init 1 $a (i64.const 0) (i32.const 0) (i32.const 1))
  )
  (func (export "fold-in")
    (table.init $other 0 (i64.const 0) (i32.const 0) (i32.const 1))
  )
  (func (export "fold-ii")
    (table.init $other $a (i64.const 0) (i32.const 0) (i32.const 1))
  )
  (func (export "fold-second")
    (table.init $b (i64.const 0) (i32.const 0) (i32.const 1))
  )
  (func (export "fold-second-nn")
    (table.init 1 1 (i64.const 0) (i32.const 0) (i32.const 1))
  )
  (func (export "data-a-flat") data.drop 0)
  (func (export "data-a-fold") (data.drop $d0))
  (func (export "data-b-flat") data.drop $d1)
  (func (export "data-b-fold") (data.drop 1))
  (func (export "elem-a-flat") elem.drop 0)
  (func (export "elem-a-fold") (elem.drop $a))
  (func (export "elem-b-flat") elem.drop $b)
  (func (export "elem-b-fold") (elem.drop 1))
  (func (export "data-init0") (result i32)
    i64.const 0 i32.const 0 i32.const 1 memory.init 0
    (i32.load8_u (i64.const 0)))
  (func (export "data-zero0") i64.const 0 i32.const 0 i32.const 0 memory.init 0)
  (func (export "elem-zero0") i64.const 0 i32.const 0 i32.const 0 table.init 0)
  (func (export "data-init1") (result i32)
    i64.const 0 i32.const 0 i32.const 1 memory.init 1
    (i32.load8_u (i64.const 0)))
  (func (export "data-zero1") i64.const 0 i32.const 0 i32.const 0 memory.init 1)
  (func (export "elem-zero1") i64.const 0 i32.const 0 i32.const 0 table.init 1)
  (elem $a func $f)
  (elem $b func $g)
  (elem declare func $seed)
  (data $d0 "x")
  (data $d1 "Y")
)
(assert_return (invoke "reset"))
(assert_return (invoke "flat-numeric"))
(assert_return (invoke "call0") (i32.const 11))
(assert_return (invoke "call1") (i32.const 7))
(assert_return (invoke "reset"))
(assert_return (invoke "flat-named"))
(assert_return (invoke "call0") (i32.const 11))
(assert_return (invoke "call1") (i32.const 7))
(assert_return (invoke "reset"))
(assert_return (invoke "flat-nn"))
(assert_return (invoke "call1") (i32.const 11))
(assert_return (invoke "call0") (i32.const 7))
(assert_return (invoke "reset"))
(assert_return (invoke "flat-ni"))
(assert_return (invoke "call1") (i32.const 11))
(assert_return (invoke "call0") (i32.const 7))
(assert_return (invoke "reset"))
(assert_return (invoke "flat-in"))
(assert_return (invoke "call1") (i32.const 11))
(assert_return (invoke "call0") (i32.const 7))
(assert_return (invoke "reset"))
(assert_return (invoke "flat-ii"))
(assert_return (invoke "call1") (i32.const 11))
(assert_return (invoke "call0") (i32.const 7))
(assert_return (invoke "reset"))
(assert_return (invoke "flat-second"))
(assert_return (invoke "call0") (i32.const 29))
(assert_return (invoke "call1") (i32.const 7))
(assert_return (invoke "reset"))
(assert_return (invoke "flat-second-nn"))
(assert_return (invoke "call1") (i32.const 29))
(assert_return (invoke "call0") (i32.const 7))
(assert_return (invoke "reset"))
(assert_return (invoke "fold-numeric"))
(assert_return (invoke "call0") (i32.const 11))
(assert_return (invoke "call1") (i32.const 7))
(assert_return (invoke "reset"))
(assert_return (invoke "fold-named"))
(assert_return (invoke "call0") (i32.const 11))
(assert_return (invoke "call1") (i32.const 7))
(assert_return (invoke "reset"))
(assert_return (invoke "fold-nn"))
(assert_return (invoke "call1") (i32.const 11))
(assert_return (invoke "call0") (i32.const 7))
(assert_return (invoke "reset"))
(assert_return (invoke "fold-ni"))
(assert_return (invoke "call1") (i32.const 11))
(assert_return (invoke "call0") (i32.const 7))
(assert_return (invoke "reset"))
(assert_return (invoke "fold-in"))
(assert_return (invoke "call1") (i32.const 11))
(assert_return (invoke "call0") (i32.const 7))
(assert_return (invoke "reset"))
(assert_return (invoke "fold-ii"))
(assert_return (invoke "call1") (i32.const 11))
(assert_return (invoke "call0") (i32.const 7))
(assert_return (invoke "reset"))
(assert_return (invoke "fold-second"))
(assert_return (invoke "call0") (i32.const 29))
(assert_return (invoke "call1") (i32.const 7))
(assert_return (invoke "reset"))
(assert_return (invoke "fold-second-nn"))
(assert_return (invoke "call1") (i32.const 29))
(assert_return (invoke "call0") (i32.const 7))
(assert_return (invoke "data-init0") (i32.const 120))
(assert_return (invoke "data-init1") (i32.const 89))
(assert_return (invoke "data-a-flat"))
(assert_return (invoke "data-a-fold"))
(assert_trap (invoke "data-init0") "out of bounds memory access")
(assert_return (invoke "data-zero0"))
(assert_return (invoke "data-b-flat"))
(assert_return (invoke "data-b-fold"))
(assert_trap (invoke "data-init1") "out of bounds memory access")
(assert_return (invoke "data-zero1"))
(assert_return (invoke "elem-a-flat"))
(assert_return (invoke "elem-a-fold"))
(assert_trap (invoke "flat-numeric") "out of bounds table access")
(assert_return (invoke "elem-zero0"))
(assert_return (invoke "elem-b-flat"))
(assert_return (invoke "elem-b-fold"))
(assert_trap (invoke "flat-second") "out of bounds table access")
(assert_return (invoke "elem-zero1"))
(assert_invalid (module (data "") (func data.drop 1)) "unknown data segment")
(assert_invalid (module (elem func) (func elem.drop 1)) "unknown elem segment")
(assert_invalid (module (table 1 funcref) (elem func) (func (i32.const 0) (i32.const 0) (i32.const 0) table.init 0 3)) "unknown elem segment")
(assert_invalid (module (table 1 funcref) (elem func) (func (i32.const 0) (i32.const 0) (i32.const 0) table.init 3 0)) "unknown table")
(assert_invalid (module (table 1 funcref) (elem $e func) (func table.init 0)) "type mismatch")
(assert_invalid (module (table 1 funcref) (elem $e func) (func table.init $e)) "type mismatch")
(assert_invalid (module (table i64 1 funcref) (elem func) (func i32.const 0 i32.const 0 i32.const 0 table.init 0)) "type mismatch")
(assert_invalid (module (data "") (func (data.drop 1))) "unknown data segment")
(assert_invalid (module (elem func) (func (elem.drop 1))) "unknown elem segment")
(assert_invalid (module (table 1 funcref) (elem func) (func (table.init 0 3 (i32.const 0) (i32.const 0) (i32.const 0)))) "unknown elem segment")
(assert_invalid (module (table 1 funcref) (elem func) (func (table.init 3 0 (i32.const 0) (i32.const 0) (i32.const 0)))) "unknown table")
(assert_invalid (module (table 1 funcref) (elem $e func) (func (table.init 0))) "type mismatch")
(assert_invalid (module (table 1 funcref) (elem $e func) (func (table.init $e))) "type mismatch")
(assert_invalid (module (table i64 1 funcref) (elem func) (func (table.init 0 (i32.const 0) (i32.const 0) (i32.const 0)))) "type mismatch")

;; Flat instructions retain the highest supported segment index, 127.
(module (memory 1) (table 1 funcref) (func $f (result i32) (i32.const 42))
  (data "") (elem func)
  (data "") (elem func)
  (data "") (elem func)
  (data "") (elem func)
  (data "") (elem func)
  (data "") (elem func)
  (data "") (elem func)
  (data "") (elem func)
  (data "") (elem func)
  (data "") (elem func)
  (data "") (elem func)
  (data "") (elem func)
  (data "") (elem func)
  (data "") (elem func)
  (data "") (elem func)
  (data "") (elem func)
  (data "") (elem func)
  (data "") (elem func)
  (data "") (elem func)
  (data "") (elem func)
  (data "") (elem func)
  (data "") (elem func)
  (data "") (elem func)
  (data "") (elem func)
  (data "") (elem func)
  (data "") (elem func)
  (data "") (elem func)
  (data "") (elem func)
  (data "") (elem func)
  (data "") (elem func)
  (data "") (elem func)
  (data "") (elem func)
  (data "") (elem func)
  (data "") (elem func)
  (data "") (elem func)
  (data "") (elem func)
  (data "") (elem func)
  (data "") (elem func)
  (data "") (elem func)
  (data "") (elem func)
  (data "") (elem func)
  (data "") (elem func)
  (data "") (elem func)
  (data "") (elem func)
  (data "") (elem func)
  (data "") (elem func)
  (data "") (elem func)
  (data "") (elem func)
  (data "") (elem func)
  (data "") (elem func)
  (data "") (elem func)
  (data "") (elem func)
  (data "") (elem func)
  (data "") (elem func)
  (data "") (elem func)
  (data "") (elem func)
  (data "") (elem func)
  (data "") (elem func)
  (data "") (elem func)
  (data "") (elem func)
  (data "") (elem func)
  (data "") (elem func)
  (data "") (elem func)
  (data "") (elem func)
  (data "") (elem func)
  (data "") (elem func)
  (data "") (elem func)
  (data "") (elem func)
  (data "") (elem func)
  (data "") (elem func)
  (data "") (elem func)
  (data "") (elem func)
  (data "") (elem func)
  (data "") (elem func)
  (data "") (elem func)
  (data "") (elem func)
  (data "") (elem func)
  (data "") (elem func)
  (data "") (elem func)
  (data "") (elem func)
  (data "") (elem func)
  (data "") (elem func)
  (data "") (elem func)
  (data "") (elem func)
  (data "") (elem func)
  (data "") (elem func)
  (data "") (elem func)
  (data "") (elem func)
  (data "") (elem func)
  (data "") (elem func)
  (data "") (elem func)
  (data "") (elem func)
  (data "") (elem func)
  (data "") (elem func)
  (data "") (elem func)
  (data "") (elem func)
  (data "") (elem func)
  (data "") (elem func)
  (data "") (elem func)
  (data "") (elem func)
  (data "") (elem func)
  (data "") (elem func)
  (data "") (elem func)
  (data "") (elem func)
  (data "") (elem func)
  (data "") (elem func)
  (data "") (elem func)
  (data "") (elem func)
  (data "") (elem func)
  (data "") (elem func)
  (data "") (elem func)
  (data "") (elem func)
  (data "") (elem func)
  (data "") (elem func)
  (data "") (elem func)
  (data "") (elem func)
  (data "") (elem func)
  (data "") (elem func)
  (data "") (elem func)
  (data "") (elem func)
  (data "") (elem func)
  (data "") (elem func)
  (data "") (elem func)
  (data "") (elem func)
  (data "") (elem func)
  (data "") (elem func)
  (data "") (elem func)
  (data "T") (elem func $f)
  (func (export "init") i32.const 0 i32.const 0 i32.const 1 memory.init 127
    i32.const 0 i32.const 0 i32.const 1 table.init 127)
  (func (export "read") (result i32) (i32.load8_u (i32.const 0)))
  (func (export "call") (result i32) (call_indirect (result i32) (i32.const 0)))
  (func (export "drop") data.drop 127 elem.drop 127)
)
(assert_return (invoke "init"))
(assert_return (invoke "read") (i32.const 84))
(assert_return (invoke "call") (i32.const 42))
(assert_return (invoke "drop"))
(assert_return (invoke "drop"))
(assert_trap (invoke "init") "out of bounds memory access")

;; Required immediates and unresolved symbolic references are malformed text.
(assert_malformed (module quote "(module (table 1 funcref) (elem func) (func table.init))\n") "unexpected token")
(assert_malformed (module quote "(module (data \"owned parser payload\") (elem func) (func data.drop))\n") "unexpected token")
(assert_malformed (module quote "(module (data \"owned parser payload\") (elem func) (func elem.drop))\n") "unexpected token")
(assert_malformed (module quote "(module (table 1 funcref) (elem func) (func table.init $absent))\n") "unknown elem")
(assert_malformed (module quote "(module (data \"owned parser payload\") (elem func) (func data.drop $absent))\n") "unknown data")
(assert_malformed (module quote "(module (data \"owned parser payload\") (elem func) (func elem.drop $absent))\n") "unknown elem")
