;; Actions following module assertions must still use the current instance.
(module $provider
  (global (export "value") (mut i32) (i32.const 42))
  (func (export "answer") (result i32) global.get 0))
(module
  (global (export "value") (mut i32) (i32.const 7))
  (func (export "answer") (result i32) global.get 0)
  (func (export "bump") i32.const 8 global.set 0))
(assert_return (invoke "answer") (i32.const 7))
(register "provider" $provider)
(assert_unlinkable (module (import "absent" "f" (func))) "unknown import")
(invoke "bump")
(assert_return (get "value") (i32.const 8))
(assert_return (invoke $provider "answer") (i32.const 42))
(assert_invalid (module (func (result i32))) "type mismatch")
(assert_return (invoke "answer") (i32.const 8))
(assert_malformed (module binary "\00") "unexpected end")
(assert_return (get "value") (i32.const 8))
(assert_trap (module (func $start unreachable) (start $start)) "unreachable")
(assert_return (invoke "answer") (i32.const 8))
;; Registration affects subsequent imports, without changing the current module.
(module (import "provider" "answer" (func $answer (result i32)))
  (func (export "answer") (result i32) call $answer))
(assert_return (invoke "answer") (i32.const 42))
;; Registered anonymous instances and definition metadata survive replacement.
(register "alias")
(module definition $template (func (export "answer") (result i32) i32.const 9))
(module instance $instance $template)
(assert_return (invoke "answer") (i32.const 9))
(assert_return (invoke $provider "answer") (i32.const 42))
(module (import "alias" "answer" (func $answer (result i32)))
  (func (export "answer") (result i32) call $answer))
(assert_return (invoke "answer") (i32.const 42))
(assert_invalid (module (func (result i64) i32.const 0)) "type mismatch")
(assert_return (invoke $instance "answer") (i32.const 9))
(assert_return (invoke "answer") (i32.const 42))
