;; Startup probe: resources are supplied by C, not a launcher module.
(module
  (import "env" "memory" (memory 2))
  (import "env" "__indirect_function_table" (table 1 funcref))
  (import "env" "__stack_pointer" (global $stack (mut i32)))
  (import "waste_kernel" "startup_v1" (func $startup (result i32)))
  (global $initialized (export "initialized") (mut i32) (i32.const 0))
  (global $constructed (export "constructed") (mut i32) (i32.const 0))
  (func $constructor (global.set $constructed (i32.add (global.get $constructed) (i32.const 1))))
  (start $constructor)
  (func (export "waste_allocator_init") (param i32) (result i32)
    (global.set $initialized (i32.add (global.get $initialized) (i32.const 1))) (i32.const 1))
  (func (export "waste_environ_set") (param i32)
    (global.set $initialized (i32.add (global.get $initialized) (i32.const 2))))
  (func (export "waste_stdio_init") (param i32) (result i32)
    (global.set $initialized (i32.add (global.get $initialized) (i32.const 4))) (i32.const 1))
  (func $main (export "_start")
    (if (i32.ne (global.get $initialized) (i32.const 7)) (then unreachable))
    (if (i32.ne (global.get $constructed) (i32.const 1)) (then unreachable))
    (if (i32.ne (i32.load (call $startup)) (i32.const 1)) (then unreachable))
    (if (i32.le_s (global.get $stack) (i32.const 0)) (then unreachable)))
  (func (export "probe") (call $main)))
