;; The child spins on a nonblocking pipe readiness query. Only a time slice
;; can give its parent the chance to write the byte that ends that spin.
(module
  (import "env" "pipe" (func $pipe (param i32) (result i32)))
  (import "env" "fork" (func $fork (result i32)))
  (import "env" "exit" (func $exit (param i32)))
  (import "env" "waitpid" (func $wait (param i32 i32 i32) (result i32)))
  (import "env" "select" (func $select (param i32 i32 i32 i32 i32) (result i32)))
  (import "env" "write" (func $write (param i32 i32 i32) (result i32)))
  (import "env" "read" (func $read (param i32 i32 i32) (result i32)))
  (import "env" "close" (func $close (param i32) (result i32)))
  (memory 1)
  (data (i32.const 64) "X")
  (func (export "fair_cpu") (result i32) (local $pid i32) (local $reader i32)
    (if (call $pipe (i32.const 128)) (then unreachable))
    (local.set $reader (i32.load (i32.const 128)))
    (local.set $pid (call $fork))
    (if (i32.eqz (local.get $pid)) (then
      (loop $spin
        (i32.store (i32.const 160) (i32.shl (i32.const 1) (local.get $reader)))
        (br_if $spin (i32.eqz (call $select (i32.add (local.get $reader) (i32.const 1))
          (i32.const 160) (i32.const 0) (i32.const 0) (i32.const 256)))))
      (if (i32.ne (call $read (local.get $reader) (i32.const 65) (i32.const 1)) (i32.const 1))
        (then unreachable))
      (if (i32.ne (i32.load8_u (i32.const 65)) (i32.const 88)) (then unreachable))
      (call $exit (i32.const 7))))
    (if (i32.ne (call $write (i32.load (i32.const 132)) (i32.const 64) (i32.const 1)) (i32.const 1))
      (then unreachable))
    (if (i32.ne (call $wait (local.get $pid) (i32.const 192) (i32.const 0)) (local.get $pid))
      (then unreachable))
    (if (i32.ne (i32.load (i32.const 192)) (i32.const 1792)) (then unreachable))
    (i32.const 1))
  ;; Transfer more than a pipe can hold. Full writes and empty reads must
  ;; suspend their processes so the peer can drain/refill the shared pipe.
  (func (export "backpressure") (result i32)
    (local $pid i32) (local $offset i32) (local $count i32) (local $total i32)
    (if (call $pipe (i32.const 128)) (then unreachable))
    (memory.fill (i32.const 256) (i32.const 90) (i32.const 8192))
    (local.set $pid (call $fork))
    (if (i32.eqz (local.get $pid)) (then
      (drop (call $close (i32.load (i32.const 128))))
      (loop $send
        (local.set $count (call $write (i32.load (i32.const 132))
          (i32.add (i32.const 256) (local.get $offset))
          (i32.sub (i32.const 8192) (local.get $offset))))
        (if (i32.le_s (local.get $count) (i32.const 0)) (then unreachable))
        (local.set $offset (i32.add (local.get $offset) (local.get $count)))
        (br_if $send (i32.lt_u (local.get $offset) (i32.const 8192))))
      (call $exit (i32.const 7))))
    (drop (call $close (i32.load (i32.const 132))))
    (block $eof
      (loop $receive
        (local.set $count (call $read (i32.load (i32.const 128)) (i32.const 256) (i32.const 8192)))
        (br_if $eof (i32.eqz (local.get $count)))
        (if (i32.lt_s (local.get $count) (i32.const 0)) (then unreachable))
        (if (i32.ne (i32.load8_u (i32.const 256)) (i32.const 90)) (then unreachable))
        (if (i32.ne (i32.load8_u (i32.add (i32.const 255) (local.get $count))) (i32.const 90))
          (then unreachable))
        (local.set $total (i32.add (local.get $total) (local.get $count)))
        (br $receive)))
    (drop (call $close (i32.load (i32.const 128))))
    (if (i32.ne (call $wait (local.get $pid) (i32.const 192) (i32.const 0)) (local.get $pid))
      (then unreachable))
    (if (i32.ne (i32.load (i32.const 192)) (i32.const 1792)) (then unreachable))
    (local.get $total)))
(assert_return (invoke "fair_cpu") (i32.const 1))
(assert_return (invoke "backpressure") (i32.const 8192))
