(module
  (type $result (func (result i32)))
  (memory 1)
  (data $bytes "ABCDEFGH")
  (table 8 funcref)
  (func $eleven (type $result) (i32.const 11))
  (func $twenty_two (type $result) (i32.const 22))
  (elem $functions func $eleven $twenty_two)

  (func (export "memory_init")
    (memory.init $bytes (i32.const 0) (i32.const 0) (i32.const 8)))
  (func (export "memory_copy")
    (memory.copy (i32.const 2) (i32.const 0) (i32.const 6)))
  (func (export "memory_fill")
    (memory.fill (i32.const 0) (i32.const 0xaa) (i32.const 8)))
  (func (export "load8") (param $address i32) (result i32)
    (i32.load8_u (local.get $address)))

  (func (export "table_init")
    (table.init $functions (i32.const 0) (i32.const 0) (i32.const 2)))
  (func (export "table_fill")
    (table.fill (i32.const 2) (ref.func $eleven) (i32.const 2)))
  (func (export "table_copy")
    (table.copy (i32.const 4) (i32.const 0) (i32.const 4)))
  (func (export "call") (param $index i32) (result i32)
    (call_indirect (type $result) (local.get $index))))

(invoke "memory_init")
(assert_return (invoke "load8" (i32.const 0)) (i32.const 65))
(assert_return (invoke "load8" (i32.const 7)) (i32.const 72))
(invoke "memory_copy")
(assert_return (invoke "load8" (i32.const 2)) (i32.const 65))
(assert_return (invoke "load8" (i32.const 7)) (i32.const 70))
(invoke "memory_fill")
(assert_return (invoke "load8" (i32.const 0)) (i32.const 170))
(assert_return (invoke "load8" (i32.const 7)) (i32.const 170))

(invoke "table_init")
(invoke "table_fill")
(invoke "table_copy")
(assert_return (invoke "call" (i32.const 0)) (i32.const 11))
(assert_return (invoke "call" (i32.const 1)) (i32.const 22))
(assert_return (invoke "call" (i32.const 2)) (i32.const 11))
(assert_return (invoke "call" (i32.const 3)) (i32.const 11))
(assert_return (invoke "call" (i32.const 4)) (i32.const 11))
(assert_return (invoke "call" (i32.const 5)) (i32.const 22))
(assert_return (invoke "call" (i32.const 6)) (i32.const 11))
(assert_return (invoke "call" (i32.const 7)) (i32.const 11))
