#!/usr/bin/awk -f
# gen-dispatch.awk — reads opcodes.tab, emits dispatch_gen.h and dispatch_gen.c
#
# Usage:
#   awk -v outdir=build/engine/gen -f gen-dispatch.awk opcodes.tab
# Writes: dispatch_gen.h and dispatch_gen.c into outdir (default: current dir)

BEGIN {
    FS = "|"
    if (outdir == "") outdir = "."
    header = outdir "/dispatch_gen.h"
    source = outdir "/dispatch_gen.c"
    n = 0  # entry count
}

# Skip comments and blank lines
/^#/ || /^[[:space:]]*$/ { next }

{
    # Trim whitespace from each field
    for (i = 1; i <= NF; i++) {
        gsub(/^[[:space:]]+|[[:space:]]+$/, "", $i)
    }

    prefix[n]   = $1
    sub_op[n]   = $2
    name[n]     = $3
    template[n] = $4
    validate[n] = $5
    # Fields 6+ are template parameters.
    # Rejoin into a single string first (recovers C "|" operators
    # that were split by the pipe field separator), then split on
    # semicolons for templates that take multiple parameters.
    joined = ""
    for (i = 6; i <= NF; i++) {
        gsub(/^[[:space:]]+|[[:space:]]+$/, "", $i)
        if (i > 6) joined = joined "|"
        joined = joined $i
    }
    nparam = split(joined, _parts, ";")
    for (i = 1; i <= nparam; i++) {
        gsub(/^[[:space:]]+|[[:space:]]+$/, "", _parts[i])
        params[n, i - 1] = _parts[i]
    }
    if (nparam == 0 && joined != "") {
        params[n, 0] = joined
        nparam = 1
    }
    param_count[n] = nparam
    n++
}

END {
    emit_header()
    emit_source()
}

function emit_header() {
    print "/* Generated by gen-dispatch.awk — do not edit */" > header
    print "#ifndef WASTE_DISPATCH_GEN_H" > header
    print "#define WASTE_DISPATCH_GEN_H" > header
    print "" > header
    print "#include \"op/validate.h\"" > header
    print "" > header
    print "/* ---- Dispatch table types ---- */" > header
    print "" > header
    print "typedef wasm_validation_status (*wasm_validate_handler)(" > header
    print "    wasm_validate_context *ctx, const exec_instr *instr);" > header
    print "" > header
    print "typedef int (*wasm_exec_handler)(waste_exec_context *ctx," > header
    print "                                 const exec_instr *instr);" > header
    print "" > header
    print "typedef struct {" > header
    print "    wasm_exec_handler execute;" > header
    print "    wasm_validate_handler validate;" > header
    print "} wasm_opcode_dispatch;" > header
    print "" > header
    print "/* Lookup: resolves single or multi-byte opcodes */" > header
    print "const wasm_opcode_dispatch *wasm_opcode_get_dispatch(const exec_instr *instr);" > header
    print "" > header

    # Collect unique handler names
    delete seen_exec
    delete seen_validate
    delete exec_names
    delete validate_names
    nexec = 0
    nvalidate = 0

    for (i = 0; i < n; i++) {
        if (template[i] == "CUSTOM") {
            ename = params[i, 0]
        } else {
            ename = "execute_op_" name[i]
        }
        if (!(ename in seen_exec)) {
            seen_exec[ename] = 1
            exec_names[nexec++] = ename
        }
        vname = validate[i]
        if (!(vname in seen_validate)) {
            seen_validate[vname] = 1
            validate_names[nvalidate++] = vname
        }
    }

    print "/* ---- Validate handler declarations ---- */" > header
    print "" > header
    for (i = 0; i < nvalidate; i++) {
        printf "wasm_validation_status %s(wasm_validate_context *ctx, const exec_instr *instr);\n", validate_names[i] > header
    }

    print "" > header
    print "/* ---- Execute handler declarations ---- */" > header
    print "" > header
    for (i = 0; i < nexec; i++) {
        printf "int %s(waste_exec_context *ctx, const exec_instr *instr);\n", exec_names[i] > header
    }

    print "" > header
    print "#endif" > header
    close(header)
}

function emit_source() {
    print "/* Generated by gen-dispatch.awk — do not edit */" > source
    print "#include \"dispatch_gen.h\"" > source
    print "" > source
    print "" > source
    print "#include <limits.h>" > source
    print "#include <math.h>" > source
    print "#include <string.h>" > source
    print "" > source

    # Emit helper functions needed by generated code
    emit_helpers()

    # Emit generated handler functions
    for (i = 0; i < n; i++) {
        if (template[i] != "CUSTOM") {
            emit_handler(i)
        }
    }

    # Emit dispatch table
    emit_dispatch_table()
}

function emit_helpers() {
    print "/* ---- Rotate helpers ---- */" > source
    print "" > source
    print "static uint32_t gen_rotl32(uint32_t v, uint32_t c) {" > source
    print "    c &= 31u; return c ? (v << c) | (v >> (32u - c)) : v;" > source
    print "}" > source
    print "static uint32_t gen_rotr32(uint32_t v, uint32_t c) {" > source
    print "    c &= 31u; return c ? (v >> c) | (v << (32u - c)) : v;" > source
    print "}" > source
    print "" > source
}

function emit_handler(i,    t, nm, expr) {
    t = template[i]
    nm = name[i]
    expr = params[i, 0]

    if (t == "I32_BIN")      emit_i32_bin(nm, expr)
    else if (t == "I32_UN")  emit_i32_un(nm, expr)
    else if (t == "I64_BIN") emit_i64_bin(nm, expr)
    else if (t == "I64_UN")  emit_i64_un(nm, expr)
    else if (t == "I64_CMP") emit_i64_cmp(nm, expr)
    else if (t == "I64_TEST") emit_i64_test(nm, expr)
    else if (t == "F32_BIN") emit_f32_bin(nm, expr)
    else if (t == "F32_UN")  emit_f32_un(nm, expr)
    else if (t == "F32_CMP") emit_f32_cmp(nm, expr)
    else if (t == "F64_BIN") emit_f64_bin(nm, expr)
    else if (t == "F64_UN")  emit_f64_un(nm, expr)
    else if (t == "F64_CMP") emit_f64_cmp(nm, expr)
    else if (t == "I32_DIV_S") emit_i32_div_s(nm)
    else if (t == "I32_DIV_U") emit_i32_div_u(nm)
    else if (t == "I32_REM_S") emit_i32_rem_s(nm)
    else if (t == "I32_REM_U") emit_i32_rem_u(nm)
    else if (t == "I64_DIV_S") emit_i64_div_s(nm)
    else if (t == "I64_DIV_U") emit_i64_div_u(nm)
    else if (t == "I64_REM_S") emit_i64_rem_s(nm)
    else if (t == "I64_REM_U") emit_i64_rem_u(nm)
    else if (t == "I32_ROTL") emit_i32_rot(nm, "gen_rotl32")
    else if (t == "I32_ROTR") emit_i32_rot(nm, "gen_rotr32")
    else if (t == "I64_ROTL") emit_i64_rot(nm, "l")
    else if (t == "I64_ROTR") emit_i64_rot(nm, "r")
    else if (t == "F32_MIN")  emit_f_minmax(nm, "f32", "float", 4, "min")
    else if (t == "F32_MAX")  emit_f_minmax(nm, "f32", "float", 4, "max")
    else if (t == "F32_COPYSIGN") emit_f_copysign(nm, "f32", "float", 4, "uint32_t", "0x7fffffffu", "0x80000000u")
    else if (t == "F64_MIN")  emit_f_minmax(nm, "f64", "double", 8, "min")
    else if (t == "F64_MAX")  emit_f_minmax(nm, "f64", "double", 8, "max")
    else if (t == "F64_COPYSIGN") emit_f_copysign(nm, "f64", "double", 8, "uint64_t", "UINT64_C(0x7fffffffffffffff)", "UINT64_C(0x8000000000000000)")
    else if (t == "CONST_I32") emit_const_i32(nm)
    else if (t == "CONST_I64") emit_const_i64(nm)
    else if (t == "CONST_F32") emit_const_f32(nm)
    else if (t == "CONST_F64") emit_const_f64(nm)
    else if (t == "CONV")      emit_conv(nm, i)
    else if (t == "CONV_F")    emit_conv_float(nm, i)
    else if (t == "CONV_DEMOTE")  emit_conv_demote(nm)
    else if (t == "CONV_PROMOTE") emit_conv_promote(nm)
    else if (t == "TRUNC")     emit_trunc(nm, i)
    else if (t == "REINTERPRET") emit_reinterpret(nm, i)
}

# ---- i32 binary: pop 2 i32, push i32 ----
function emit_i32_bin(nm, expr) {
    printf "int execute_op_%s(waste_exec_context *ctx, const exec_instr *instr) {\n", nm > source
    print  "    (void)instr;" > source
    print  "    wasm_value right, left;" > source
    print  "    if (!stack_pop(ctx->operand_stack, &right) || right.type != WASM_VALTYPE_I32 ||" > source
    print  "        !stack_pop(ctx->operand_stack, &left) || left.type != WASM_VALTYPE_I32)" > source
    print  "        return exec_fail(ctx->error, EXEC_ERROR_TRAP, \"i32 operands missing\");" > source
    print  "    uint32_t a = (uint32_t)left.i32, b = (uint32_t)right.i32;" > source
    printf "    if (!stack_push(ctx->operand_stack, i32_value(%s)))\n", expr > source
    print  "        return exec_fail(ctx->error, EXEC_ERROR_TRAP, \"stack overflow\");" > source
    print  "    return EXEC_OK;" > source
    print  "}" > source
    print  "" > source
}

# ---- i32 unary: pop 1 i32, push i32 ----
function emit_i32_un(nm, expr) {
    printf "int execute_op_%s(waste_exec_context *ctx, const exec_instr *instr) {\n", nm > source
    print  "    (void)instr;" > source
    print  "    wasm_value val;" > source
    print  "    if (!stack_pop(ctx->operand_stack, &val) || val.type != WASM_VALTYPE_I32)" > source
    print  "        return exec_fail(ctx->error, EXEC_ERROR_TRAP, \"i32 operand missing\");" > source
    print  "    uint32_t b = (uint32_t)val.i32;" > source
    printf "    if (!stack_push(ctx->operand_stack, i32_value(%s)))\n", expr > source
    print  "        return exec_fail(ctx->error, EXEC_ERROR_TRAP, \"stack overflow\");" > source
    print  "    return EXEC_OK;" > source
    print  "}" > source
    print  "" > source
}

# ---- i64 binary: pop 2 i64, push i64 ----
function emit_i64_bin(nm, expr) {
    printf "int execute_op_%s(waste_exec_context *ctx, const exec_instr *instr) {\n", nm > source
    print  "    (void)instr;" > source
    print  "    wasm_value right, left;" > source
    print  "    if (!stack_pop(ctx->operand_stack, &right) || right.type != WASM_VALTYPE_I64 ||" > source
    print  "        !stack_pop(ctx->operand_stack, &left) || left.type != WASM_VALTYPE_I64)" > source
    print  "        return exec_fail(ctx->error, EXEC_ERROR_TRAP, \"i64 operands missing\");" > source
    print  "    uint64_t a = (uint64_t)left.i64, b = (uint64_t)right.i64;" > source
    print  "    wasm_value out; memset(&out, 0, sizeof(out));" > source
    printf "    out.type = WASM_VALTYPE_I64; out.i64 = (int64_t)(%s);\n", expr > source
    print  "    if (!stack_push(ctx->operand_stack, out))" > source
    print  "        return exec_fail(ctx->error, EXEC_ERROR_TRAP, \"stack overflow\");" > source
    print  "    return EXEC_OK;" > source
    print  "}" > source
    print  "" > source
}

# ---- i64 unary: pop 1 i64, push i64 ----
function emit_i64_un(nm, expr) {
    printf "int execute_op_%s(waste_exec_context *ctx, const exec_instr *instr) {\n", nm > source
    print  "    (void)instr;" > source
    print  "    wasm_value val;" > source
    print  "    if (!stack_pop(ctx->operand_stack, &val) || val.type != WASM_VALTYPE_I64)" > source
    print  "        return exec_fail(ctx->error, EXEC_ERROR_TRAP, \"i64 operand missing\");" > source
    print  "    uint64_t b = (uint64_t)val.i64;" > source
    print  "    wasm_value out; memset(&out, 0, sizeof(out));" > source
    printf "    out.type = WASM_VALTYPE_I64; out.i64 = (int64_t)(%s);\n", expr > source
    print  "    if (!stack_push(ctx->operand_stack, out))" > source
    print  "        return exec_fail(ctx->error, EXEC_ERROR_TRAP, \"stack overflow\");" > source
    print  "    return EXEC_OK;" > source
    print  "}" > source
    print  "" > source
}

# ---- i64 binary comparison: pop 2 i64, push i32 ----
function emit_i64_cmp(nm, expr) {
    printf "int execute_op_%s(waste_exec_context *ctx, const exec_instr *instr) {\n", nm > source
    print  "    (void)instr;" > source
    print  "    wasm_value right, left;" > source
    print  "    if (!stack_pop(ctx->operand_stack, &right) || right.type != WASM_VALTYPE_I64 ||" > source
    print  "        !stack_pop(ctx->operand_stack, &left) || left.type != WASM_VALTYPE_I64)" > source
    print  "        return exec_fail(ctx->error, EXEC_ERROR_TRAP, \"i64 operands missing\");" > source
    print  "    uint64_t a = (uint64_t)left.i64, b = (uint64_t)right.i64;" > source
    printf "    if (!stack_push(ctx->operand_stack, i32_value(%s)))\n", expr > source
    print  "        return exec_fail(ctx->error, EXEC_ERROR_TRAP, \"stack overflow\");" > source
    print  "    return EXEC_OK;" > source
    print  "}" > source
    print  "" > source
}

# ---- i64 unary test: pop 1 i64, push i32 ----
function emit_i64_test(nm, expr) {
    printf "int execute_op_%s(waste_exec_context *ctx, const exec_instr *instr) {\n", nm > source
    print  "    (void)instr;" > source
    print  "    wasm_value val;" > source
    print  "    if (!stack_pop(ctx->operand_stack, &val) || val.type != WASM_VALTYPE_I64)" > source
    print  "        return exec_fail(ctx->error, EXEC_ERROR_TRAP, \"i64 operand missing\");" > source
    print  "    uint64_t b = (uint64_t)val.i64;" > source
    printf "    if (!stack_push(ctx->operand_stack, i32_value(%s)))\n", expr > source
    print  "        return exec_fail(ctx->error, EXEC_ERROR_TRAP, \"stack overflow\");" > source
    print  "    return EXEC_OK;" > source
    print  "}" > source
    print  "" > source
}

# ---- f32 binary: pop 2 f32, push f32 ----
function emit_f32_bin(nm, expr) {
    printf "int execute_op_%s(waste_exec_context *ctx, const exec_instr *instr) {\n", nm > source
    print  "    (void)instr;" > source
    print  "    wasm_value right, left; float a, b;" > source
    print  "    if (!stack_pop(ctx->operand_stack, &right) || right.type != WASM_VALTYPE_F32 ||" > source
    print  "        !stack_pop(ctx->operand_stack, &left) || left.type != WASM_VALTYPE_F32)" > source
    print  "        return exec_fail(ctx->error, EXEC_ERROR_TRAP, \"f32 operands missing\");" > source
    print  "    memcpy(&a, &left.f32, 4); memcpy(&b, &right.f32, 4);" > source
    printf "    float result = %s;\n", expr > source
    print  "    wasm_value out; memset(&out, 0, sizeof(out));" > source
    print  "    out.type = WASM_VALTYPE_F32; memcpy(&out.f32, &result, 4);" > source
    print  "    if (!stack_push(ctx->operand_stack, out))" > source
    print  "        return exec_fail(ctx->error, EXEC_ERROR_TRAP, \"stack overflow\");" > source
    print  "    return EXEC_OK;" > source
    print  "}" > source
    print  "" > source
}

# ---- f32 unary: pop 1 f32, push f32 ----
function emit_f32_un(nm, expr) {
    printf "int execute_op_%s(waste_exec_context *ctx, const exec_instr *instr) {\n", nm > source
    print  "    (void)instr;" > source
    print  "    wasm_value val; float b;" > source
    print  "    if (!stack_pop(ctx->operand_stack, &val) || val.type != WASM_VALTYPE_F32)" > source
    print  "        return exec_fail(ctx->error, EXEC_ERROR_TRAP, \"f32 operand missing\");" > source
    print  "    memcpy(&b, &val.f32, 4);" > source
    printf "    float result = %s;\n", expr > source
    print  "    wasm_value out; memset(&out, 0, sizeof(out));" > source
    print  "    out.type = WASM_VALTYPE_F32; memcpy(&out.f32, &result, 4);" > source
    print  "    if (!stack_push(ctx->operand_stack, out))" > source
    print  "        return exec_fail(ctx->error, EXEC_ERROR_TRAP, \"stack overflow\");" > source
    print  "    return EXEC_OK;" > source
    print  "}" > source
    print  "" > source
}

# ---- f32 comparison: pop 2 f32, push i32 ----
function emit_f32_cmp(nm, expr) {
    printf "int execute_op_%s(waste_exec_context *ctx, const exec_instr *instr) {\n", nm > source
    print  "    (void)instr;" > source
    print  "    wasm_value right, left; float a, b;" > source
    print  "    if (!stack_pop(ctx->operand_stack, &right) || right.type != WASM_VALTYPE_F32 ||" > source
    print  "        !stack_pop(ctx->operand_stack, &left) || left.type != WASM_VALTYPE_F32)" > source
    print  "        return exec_fail(ctx->error, EXEC_ERROR_TRAP, \"f32 operands missing\");" > source
    print  "    memcpy(&a, &left.f32, 4); memcpy(&b, &right.f32, 4);" > source
    printf "    if (!stack_push(ctx->operand_stack, i32_value(%s)))\n", expr > source
    print  "        return exec_fail(ctx->error, EXEC_ERROR_TRAP, \"stack overflow\");" > source
    print  "    return EXEC_OK;" > source
    print  "}" > source
    print  "" > source
}

# ---- f64 binary: pop 2 f64, push f64 ----
function emit_f64_bin(nm, expr) {
    printf "int execute_op_%s(waste_exec_context *ctx, const exec_instr *instr) {\n", nm > source
    print  "    (void)instr;" > source
    print  "    wasm_value right, left; double a, b;" > source
    print  "    if (!stack_pop(ctx->operand_stack, &right) || right.type != WASM_VALTYPE_F64 ||" > source
    print  "        !stack_pop(ctx->operand_stack, &left) || left.type != WASM_VALTYPE_F64)" > source
    print  "        return exec_fail(ctx->error, EXEC_ERROR_TRAP, \"f64 operands missing\");" > source
    print  "    memcpy(&a, &left.f64, 8); memcpy(&b, &right.f64, 8);" > source
    printf "    double result = %s;\n", expr > source
    print  "    wasm_value out; memset(&out, 0, sizeof(out));" > source
    print  "    out.type = WASM_VALTYPE_F64; memcpy(&out.f64, &result, 8);" > source
    print  "    if (!stack_push(ctx->operand_stack, out))" > source
    print  "        return exec_fail(ctx->error, EXEC_ERROR_TRAP, \"stack overflow\");" > source
    print  "    return EXEC_OK;" > source
    print  "}" > source
    print  "" > source
}

# ---- f64 unary: pop 1 f64, push f64 ----
function emit_f64_un(nm, expr) {
    printf "int execute_op_%s(waste_exec_context *ctx, const exec_instr *instr) {\n", nm > source
    print  "    (void)instr;" > source
    print  "    wasm_value val; double b;" > source
    print  "    if (!stack_pop(ctx->operand_stack, &val) || val.type != WASM_VALTYPE_F64)" > source
    print  "        return exec_fail(ctx->error, EXEC_ERROR_TRAP, \"f64 operand missing\");" > source
    print  "    memcpy(&b, &val.f64, 8);" > source
    printf "    double result = %s;\n", expr > source
    print  "    wasm_value out; memset(&out, 0, sizeof(out));" > source
    print  "    out.type = WASM_VALTYPE_F64; memcpy(&out.f64, &result, 8);" > source
    print  "    if (!stack_push(ctx->operand_stack, out))" > source
    print  "        return exec_fail(ctx->error, EXEC_ERROR_TRAP, \"stack overflow\");" > source
    print  "    return EXEC_OK;" > source
    print  "}" > source
    print  "" > source
}

# ---- f64 comparison: pop 2 f64, push i32 ----
function emit_f64_cmp(nm, expr) {
    printf "int execute_op_%s(waste_exec_context *ctx, const exec_instr *instr) {\n", nm > source
    print  "    (void)instr;" > source
    print  "    wasm_value right, left; double a, b;" > source
    print  "    if (!stack_pop(ctx->operand_stack, &right) || right.type != WASM_VALTYPE_F64 ||" > source
    print  "        !stack_pop(ctx->operand_stack, &left) || left.type != WASM_VALTYPE_F64)" > source
    print  "        return exec_fail(ctx->error, EXEC_ERROR_TRAP, \"f64 operands missing\");" > source
    print  "    memcpy(&a, &left.f64, 8); memcpy(&b, &right.f64, 8);" > source
    printf "    if (!stack_push(ctx->operand_stack, i32_value(%s)))\n", expr > source
    print  "        return exec_fail(ctx->error, EXEC_ERROR_TRAP, \"stack overflow\");" > source
    print  "    return EXEC_OK;" > source
    print  "}" > source
    print  "" > source
}

# ---- i32 division/remainder specials ----
function emit_i32_div_s(nm) {
    printf "int execute_op_%s(waste_exec_context *ctx, const exec_instr *instr) {\n", nm > source
    print  "    (void)instr;" > source
    print  "    wasm_value right, left;" > source
    print  "    if (!stack_pop(ctx->operand_stack, &right) || right.type != WASM_VALTYPE_I32 ||" > source
    print  "        !stack_pop(ctx->operand_stack, &left) || left.type != WASM_VALTYPE_I32)" > source
    print  "        return exec_fail(ctx->error, EXEC_ERROR_TRAP, \"i32 operands missing\");" > source
    print  "    uint32_t a = (uint32_t)left.i32, b = (uint32_t)right.i32;" > source
    print  "    if (!b) return exec_fail(ctx->error, EXEC_ERROR_TRAP, \"integer divide by zero\");" > source
    print  "    if (a == 0x80000000u && b == UINT32_MAX)" > source
    print  "        return exec_fail(ctx->error, EXEC_ERROR_TRAP, \"integer overflow\");" > source
    print  "    if (!stack_push(ctx->operand_stack, i32_value((uint32_t)((int32_t)a / (int32_t)b))))" > source
    print  "        return exec_fail(ctx->error, EXEC_ERROR_TRAP, \"stack overflow\");" > source
    print  "    return EXEC_OK;" > source
    print  "}" > source
    print  "" > source
}

function emit_i32_div_u(nm) {
    printf "int execute_op_%s(waste_exec_context *ctx, const exec_instr *instr) {\n", nm > source
    print  "    (void)instr;" > source
    print  "    wasm_value right, left;" > source
    print  "    if (!stack_pop(ctx->operand_stack, &right) || right.type != WASM_VALTYPE_I32 ||" > source
    print  "        !stack_pop(ctx->operand_stack, &left) || left.type != WASM_VALTYPE_I32)" > source
    print  "        return exec_fail(ctx->error, EXEC_ERROR_TRAP, \"i32 operands missing\");" > source
    print  "    uint32_t a = (uint32_t)left.i32, b = (uint32_t)right.i32;" > source
    print  "    if (!b) return exec_fail(ctx->error, EXEC_ERROR_TRAP, \"integer divide by zero\");" > source
    print  "    if (!stack_push(ctx->operand_stack, i32_value(a / b)))" > source
    print  "        return exec_fail(ctx->error, EXEC_ERROR_TRAP, \"stack overflow\");" > source
    print  "    return EXEC_OK;" > source
    print  "}" > source
    print  "" > source
}

function emit_i32_rem_s(nm) {
    printf "int execute_op_%s(waste_exec_context *ctx, const exec_instr *instr) {\n", nm > source
    print  "    (void)instr;" > source
    print  "    wasm_value right, left;" > source
    print  "    if (!stack_pop(ctx->operand_stack, &right) || right.type != WASM_VALTYPE_I32 ||" > source
    print  "        !stack_pop(ctx->operand_stack, &left) || left.type != WASM_VALTYPE_I32)" > source
    print  "        return exec_fail(ctx->error, EXEC_ERROR_TRAP, \"i32 operands missing\");" > source
    print  "    uint32_t a = (uint32_t)left.i32, b = (uint32_t)right.i32;" > source
    print  "    if (!b) return exec_fail(ctx->error, EXEC_ERROR_TRAP, \"integer divide by zero\");" > source
    print  "    uint32_t result = (a == 0x80000000u && b == UINT32_MAX) ? 0 : (uint32_t)((int32_t)a % (int32_t)b);" > source
    print  "    if (!stack_push(ctx->operand_stack, i32_value(result)))" > source
    print  "        return exec_fail(ctx->error, EXEC_ERROR_TRAP, \"stack overflow\");" > source
    print  "    return EXEC_OK;" > source
    print  "}" > source
    print  "" > source
}

function emit_i32_rem_u(nm) {
    printf "int execute_op_%s(waste_exec_context *ctx, const exec_instr *instr) {\n", nm > source
    print  "    (void)instr;" > source
    print  "    wasm_value right, left;" > source
    print  "    if (!stack_pop(ctx->operand_stack, &right) || right.type != WASM_VALTYPE_I32 ||" > source
    print  "        !stack_pop(ctx->operand_stack, &left) || left.type != WASM_VALTYPE_I32)" > source
    print  "        return exec_fail(ctx->error, EXEC_ERROR_TRAP, \"i32 operands missing\");" > source
    print  "    uint32_t a = (uint32_t)left.i32, b = (uint32_t)right.i32;" > source
    print  "    if (!b) return exec_fail(ctx->error, EXEC_ERROR_TRAP, \"integer divide by zero\");" > source
    print  "    if (!stack_push(ctx->operand_stack, i32_value(a % b)))" > source
    print  "        return exec_fail(ctx->error, EXEC_ERROR_TRAP, \"stack overflow\");" > source
    print  "    return EXEC_OK;" > source
    print  "}" > source
    print  "" > source
}

# ---- i64 division/remainder specials ----
function emit_i64_div_s(nm) {
    printf "int execute_op_%s(waste_exec_context *ctx, const exec_instr *instr) {\n", nm > source
    print  "    (void)instr;" > source
    print  "    wasm_value right, left;" > source
    print  "    if (!stack_pop(ctx->operand_stack, &right) || right.type != WASM_VALTYPE_I64 ||" > source
    print  "        !stack_pop(ctx->operand_stack, &left) || left.type != WASM_VALTYPE_I64)" > source
    print  "        return exec_fail(ctx->error, EXEC_ERROR_TRAP, \"i64 operands missing\");" > source
    print  "    uint64_t a = (uint64_t)left.i64, b = (uint64_t)right.i64;" > source
    print  "    if (!b) return exec_fail(ctx->error, EXEC_ERROR_TRAP, \"integer divide by zero\");" > source
    print  "    if (a == (uint64_t)INT64_MIN && b == UINT64_MAX)" > source
    print  "        return exec_fail(ctx->error, EXEC_ERROR_TRAP, \"integer overflow\");" > source
    print  "    wasm_value out; memset(&out, 0, sizeof(out));" > source
    print  "    out.type = WASM_VALTYPE_I64; out.i64 = (int64_t)((int64_t)a / (int64_t)b);" > source
    print  "    if (!stack_push(ctx->operand_stack, out))" > source
    print  "        return exec_fail(ctx->error, EXEC_ERROR_TRAP, \"stack overflow\");" > source
    print  "    return EXEC_OK;" > source
    print  "}" > source
    print  "" > source
}

function emit_i64_div_u(nm) {
    printf "int execute_op_%s(waste_exec_context *ctx, const exec_instr *instr) {\n", nm > source
    print  "    (void)instr;" > source
    print  "    wasm_value right, left;" > source
    print  "    if (!stack_pop(ctx->operand_stack, &right) || right.type != WASM_VALTYPE_I64 ||" > source
    print  "        !stack_pop(ctx->operand_stack, &left) || left.type != WASM_VALTYPE_I64)" > source
    print  "        return exec_fail(ctx->error, EXEC_ERROR_TRAP, \"i64 operands missing\");" > source
    print  "    uint64_t a = (uint64_t)left.i64, b = (uint64_t)right.i64;" > source
    print  "    if (!b) return exec_fail(ctx->error, EXEC_ERROR_TRAP, \"integer divide by zero\");" > source
    print  "    wasm_value out; memset(&out, 0, sizeof(out));" > source
    print  "    out.type = WASM_VALTYPE_I64; out.i64 = (int64_t)(a / b);" > source
    print  "    if (!stack_push(ctx->operand_stack, out))" > source
    print  "        return exec_fail(ctx->error, EXEC_ERROR_TRAP, \"stack overflow\");" > source
    print  "    return EXEC_OK;" > source
    print  "}" > source
    print  "" > source
}

function emit_i64_rem_s(nm) {
    printf "int execute_op_%s(waste_exec_context *ctx, const exec_instr *instr) {\n", nm > source
    print  "    (void)instr;" > source
    print  "    wasm_value right, left;" > source
    print  "    if (!stack_pop(ctx->operand_stack, &right) || right.type != WASM_VALTYPE_I64 ||" > source
    print  "        !stack_pop(ctx->operand_stack, &left) || left.type != WASM_VALTYPE_I64)" > source
    print  "        return exec_fail(ctx->error, EXEC_ERROR_TRAP, \"i64 operands missing\");" > source
    print  "    uint64_t a = (uint64_t)left.i64, b = (uint64_t)right.i64;" > source
    print  "    if (!b) return exec_fail(ctx->error, EXEC_ERROR_TRAP, \"integer divide by zero\");" > source
    print  "    uint64_t result = (a == (uint64_t)INT64_MIN && b == UINT64_MAX) ? 0 : (uint64_t)((int64_t)a % (int64_t)b);" > source
    print  "    wasm_value out; memset(&out, 0, sizeof(out));" > source
    print  "    out.type = WASM_VALTYPE_I64; out.i64 = (int64_t)result;" > source
    print  "    if (!stack_push(ctx->operand_stack, out))" > source
    print  "        return exec_fail(ctx->error, EXEC_ERROR_TRAP, \"stack overflow\");" > source
    print  "    return EXEC_OK;" > source
    print  "}" > source
    print  "" > source
}

function emit_i64_rem_u(nm) {
    printf "int execute_op_%s(waste_exec_context *ctx, const exec_instr *instr) {\n", nm > source
    print  "    (void)instr;" > source
    print  "    wasm_value right, left;" > source
    print  "    if (!stack_pop(ctx->operand_stack, &right) || right.type != WASM_VALTYPE_I64 ||" > source
    print  "        !stack_pop(ctx->operand_stack, &left) || left.type != WASM_VALTYPE_I64)" > source
    print  "        return exec_fail(ctx->error, EXEC_ERROR_TRAP, \"i64 operands missing\");" > source
    print  "    uint64_t a = (uint64_t)left.i64, b = (uint64_t)right.i64;" > source
    print  "    if (!b) return exec_fail(ctx->error, EXEC_ERROR_TRAP, \"integer divide by zero\");" > source
    print  "    wasm_value out; memset(&out, 0, sizeof(out));" > source
    print  "    out.type = WASM_VALTYPE_I64; out.i64 = (int64_t)(a % b);" > source
    print  "    if (!stack_push(ctx->operand_stack, out))" > source
    print  "        return exec_fail(ctx->error, EXEC_ERROR_TRAP, \"stack overflow\");" > source
    print  "    return EXEC_OK;" > source
    print  "}" > source
    print  "" > source
}

# ---- i32 rotate ----
function emit_i32_rot(nm, fn) {
    printf "int execute_op_%s(waste_exec_context *ctx, const exec_instr *instr) {\n", nm > source
    print  "    (void)instr;" > source
    print  "    wasm_value right, left;" > source
    print  "    if (!stack_pop(ctx->operand_stack, &right) || right.type != WASM_VALTYPE_I32 ||" > source
    print  "        !stack_pop(ctx->operand_stack, &left) || left.type != WASM_VALTYPE_I32)" > source
    print  "        return exec_fail(ctx->error, EXEC_ERROR_TRAP, \"i32 operands missing\");" > source
    printf "    if (!stack_push(ctx->operand_stack, i32_value(%s((uint32_t)left.i32, (uint32_t)right.i32))))\n", fn > source
    print  "        return exec_fail(ctx->error, EXEC_ERROR_TRAP, \"stack overflow\");" > source
    print  "    return EXEC_OK;" > source
    print  "}" > source
    print  "" > source
}

# ---- i64 rotate ----
function emit_i64_rot(nm, dir) {
    printf "int execute_op_%s(waste_exec_context *ctx, const exec_instr *instr) {\n", nm > source
    print  "    (void)instr;" > source
    print  "    wasm_value right, left;" > source
    print  "    if (!stack_pop(ctx->operand_stack, &right) || right.type != WASM_VALTYPE_I64 ||" > source
    print  "        !stack_pop(ctx->operand_stack, &left) || left.type != WASM_VALTYPE_I64)" > source
    print  "        return exec_fail(ctx->error, EXEC_ERROR_TRAP, \"i64 operands missing\");" > source
    print  "    uint64_t a = (uint64_t)left.i64;" > source
    print  "    uint32_t c = (uint32_t)((uint64_t)right.i64 & 63u);" > source
    if (dir == "l") {
        print  "    uint64_t result = c ? (a << c) | (a >> (64u - c)) : a;" > source
    } else {
        print  "    uint64_t result = c ? (a >> c) | (a << (64u - c)) : a;" > source
    }
    print  "    wasm_value out; memset(&out, 0, sizeof(out));" > source
    print  "    out.type = WASM_VALTYPE_I64; out.i64 = (int64_t)result;" > source
    print  "    if (!stack_push(ctx->operand_stack, out))" > source
    print  "        return exec_fail(ctx->error, EXEC_ERROR_TRAP, \"stack overflow\");" > source
    print  "    return EXEC_OK;" > source
    print  "}" > source
    print  "" > source
}

# ---- float min/max with Wasm NaN/zero semantics ----
function emit_f_minmax(nm, vt, ct, sz, op,    sign_mask, exp_mask, frac_mask, canon) {
    if (sz == 4) {
        sign_mask = "0x80000000u"
        exp_mask  = "0x7F800000u"
        frac_mask = "0x007FFFFFu"
        canon     = "0x7FC00000u"
    } else {
        sign_mask = "UINT64_C(0x8000000000000000)"
        exp_mask  = "UINT64_C(0x7FF0000000000000)"
        frac_mask = "UINT64_C(0x000FFFFFFFFFFFFF)"
        canon     = "UINT64_C(0x7FF8000000000000)"
    }
    printf "int execute_op_%s(waste_exec_context *ctx, const exec_instr *instr) {\n", nm > source
    print  "    (void)instr;" > source
    printf "    wasm_value right, left; %s a, b;\n", ct > source
    printf "    if (!stack_pop(ctx->operand_stack, &right) || right.type != WASM_VALTYPE_%s ||\n", toupper(vt) > source
    printf "        !stack_pop(ctx->operand_stack, &left) || left.type != WASM_VALTYPE_%s)\n", toupper(vt) > source
    printf "        return exec_fail(ctx->error, EXEC_ERROR_TRAP, \"%s operands missing\");\n", vt > source
    printf "    memcpy(&a, &left.%s, %d); memcpy(&b, &right.%s, %d);\n", vt, sz, vt, sz > source
    if (sz == 4) {
        print  "    uint32_t ai, bi;" > source
        printf "    memcpy(&ai, &a, %d); memcpy(&bi, &b, %d);\n", sz, sz > source
        printf "    int a_nan = ((ai & %s) == %s) && (ai & %s);\n", exp_mask, exp_mask, frac_mask > source
        printf "    int b_nan = ((bi & %s) == %s) && (bi & %s);\n", exp_mask, exp_mask, frac_mask > source
    } else {
        print  "    uint64_t ai, bi;" > source
        printf "    memcpy(&ai, &a, %d); memcpy(&bi, &b, %d);\n", sz, sz > source
        printf "    int a_nan = ((ai & %s) == %s) && (ai & %s);\n", exp_mask, exp_mask, frac_mask > source
        printf "    int b_nan = ((bi & %s) == %s) && (bi & %s);\n", exp_mask, exp_mask, frac_mask > source
    }
    printf "    %s result;\n", ct > source
    if (sz == 4) {
        printf "    if (a_nan || b_nan) { uint32_t r = %s; memcpy(&result, &r, %d); }\n", canon, sz > source
    } else {
        printf "    if (a_nan || b_nan) { uint64_t r = %s; memcpy(&result, &r, %d); }\n", canon, sz > source
    }
    if (op == "min") {
        if (sz == 4) {
            printf "    else if (a == 0.0f && b == 0.0f) { uint32_t r = ai | bi; memcpy(&result, &r, %d); }\n", sz > source
        } else {
            printf "    else if (a == 0.0 && b == 0.0) { uint64_t r = ai | bi; memcpy(&result, &r, %d); }\n", sz > source
        }
        print  "    else result = a < b ? a : b;" > source
    } else {
        if (sz == 4) {
            printf "    else if (a == 0.0f && b == 0.0f) { uint32_t r = ai & bi; memcpy(&result, &r, %d); }\n", sz > source
        } else {
            printf "    else if (a == 0.0 && b == 0.0) { uint64_t r = ai & bi; memcpy(&result, &r, %d); }\n", sz > source
        }
        print  "    else result = a > b ? a : b;" > source
    }
    print  "    wasm_value out; memset(&out, 0, sizeof(out));" > source
    printf "    out.type = WASM_VALTYPE_%s; memcpy(&out.%s, &result, %d);\n", toupper(vt), vt, sz > source
    print  "    if (!stack_push(ctx->operand_stack, out))" > source
    print  "        return exec_fail(ctx->error, EXEC_ERROR_TRAP, \"stack overflow\");" > source
    print  "    return EXEC_OK;" > source
    print  "}" > source
    print  "" > source
}

# ---- float copysign ----
function emit_f_copysign(nm, vt, ct, sz, uint_t, abs_mask, sign_mask) {
    printf "int execute_op_%s(waste_exec_context *ctx, const exec_instr *instr) {\n", nm > source
    print  "    (void)instr;" > source
    printf "    wasm_value right, left; %s a, b;\n", ct > source
    printf "    if (!stack_pop(ctx->operand_stack, &right) || right.type != WASM_VALTYPE_%s ||\n", toupper(vt) > source
    printf "        !stack_pop(ctx->operand_stack, &left) || left.type != WASM_VALTYPE_%s)\n", toupper(vt) > source
    printf "        return exec_fail(ctx->error, EXEC_ERROR_TRAP, \"%s operands missing\");\n", vt > source
    printf "    memcpy(&a, &left.%s, %d); memcpy(&b, &right.%s, %d);\n", vt, sz, vt, sz > source
    printf "    %s ai, bi;\n", uint_t > source
    printf "    memcpy(&ai, &a, %d); memcpy(&bi, &b, %d);\n", sz, sz > source
    printf "    %s ri = (ai & %s) | (bi & %s);\n", uint_t, abs_mask, sign_mask > source
    printf "    %s result; memcpy(&result, &ri, %d);\n", ct, sz > source
    print  "    wasm_value out; memset(&out, 0, sizeof(out));" > source
    printf "    out.type = WASM_VALTYPE_%s; memcpy(&out.%s, &result, %d);\n", toupper(vt), vt, sz > source
    print  "    if (!stack_push(ctx->operand_stack, out))" > source
    print  "        return exec_fail(ctx->error, EXEC_ERROR_TRAP, \"stack overflow\");" > source
    print  "    return EXEC_OK;" > source
    print  "}" > source
    print  "" > source
}

# ---- Constants ----
function emit_const_i32(nm) {
    printf "int execute_op_%s(waste_exec_context *ctx, const exec_instr *instr) {\n", nm > source
    print  "    if (!stack_push(ctx->operand_stack, i32_value(instr->u32_imm)))" > source
    print  "        return exec_fail(ctx->error, EXEC_ERROR_TRAP, \"stack overflow\");" > source
    print  "    return EXEC_OK;" > source
    print  "}" > source
    print  "" > source
}

function emit_const_i64(nm) {
    printf "int execute_op_%s(waste_exec_context *ctx, const exec_instr *instr) {\n", nm > source
    print  "    wasm_value v; memset(&v, 0, sizeof(v));" > source
    print  "    v.type = WASM_VALTYPE_I64; memcpy(&v.i64, instr->v128_imm.bytes, 8);" > source
    print  "    if (!stack_push(ctx->operand_stack, v))" > source
    print  "        return exec_fail(ctx->error, EXEC_ERROR_TRAP, \"stack overflow\");" > source
    print  "    return EXEC_OK;" > source
    print  "}" > source
    print  "" > source
}

function emit_const_f32(nm) {
    printf "int execute_op_%s(waste_exec_context *ctx, const exec_instr *instr) {\n", nm > source
    print  "    wasm_value v; memset(&v, 0, sizeof(v));" > source
    print  "    v.type = WASM_VALTYPE_F32; memcpy(&v.f32, instr->v128_imm.bytes, 4);" > source
    print  "    if (!stack_push(ctx->operand_stack, v))" > source
    print  "        return exec_fail(ctx->error, EXEC_ERROR_TRAP, \"stack overflow\");" > source
    print  "    return EXEC_OK;" > source
    print  "}" > source
    print  "" > source
}

function emit_const_f64(nm) {
    printf "int execute_op_%s(waste_exec_context *ctx, const exec_instr *instr) {\n", nm > source
    print  "    wasm_value v; memset(&v, 0, sizeof(v));" > source
    print  "    v.type = WASM_VALTYPE_F64; memcpy(&v.f64, instr->v128_imm.bytes, 8);" > source
    print  "    if (!stack_push(ctx->operand_stack, v))" > source
    print  "        return exec_fail(ctx->error, EXEC_ERROR_TRAP, \"stack overflow\");" > source
    print  "    return EXEC_OK;" > source
    print  "}" > source
    print  "" > source
}

# ---- Simple conversions (integer cast) ----
# params: src_field | dst_field | assignment_expr
function emit_conv(nm, idx,    src, dst, expr) {
    src  = params[idx, 0]
    dst  = params[idx, 1]
    expr = params[idx, 2]
    printf "int execute_op_%s(waste_exec_context *ctx, const exec_instr *instr) {\n", nm > source
    print  "    (void)instr;" > source
    print  "    wasm_value v;" > source
    printf "    if (!stack_pop(ctx->operand_stack, &v) || v.type != WASM_VALTYPE_%s)\n", toupper(src) > source
    printf "        return exec_fail(ctx->error, EXEC_ERROR_TRAP, \"conversion operand missing\");\n" > source
    print  "    wasm_value out; memset(&out, 0, sizeof(out));" > source
    printf "    out.type = WASM_VALTYPE_%s; %s;\n", toupper(dst), expr > source
    print  "    if (!stack_push(ctx->operand_stack, out))" > source
    print  "        return exec_fail(ctx->error, EXEC_ERROR_TRAP, \"stack overflow\");" > source
    print  "    return EXEC_OK;" > source
    print  "}" > source
    print  "" > source
}

# ---- Float conversion (int->float): needs memcpy for result ----
# params: src_field | dst_field | float_type | cast_expr
function emit_conv_float(nm, idx,    src, dst, ft, expr) {
    src  = params[idx, 0]
    dst  = params[idx, 1]
    ft   = params[idx, 2]
    expr = params[idx, 3]
    printf "int execute_op_%s(waste_exec_context *ctx, const exec_instr *instr) {\n", nm > source
    print  "    (void)instr;" > source
    print  "    wasm_value v;" > source
    printf "    if (!stack_pop(ctx->operand_stack, &v) || v.type != WASM_VALTYPE_%s)\n", toupper(src) > source
    printf "        return exec_fail(ctx->error, EXEC_ERROR_TRAP, \"conversion operand missing\");\n" > source
    printf "    %s r = %s;\n", ft, expr > source
    print  "    wasm_value out; memset(&out, 0, sizeof(out));" > source
    printf "    out.type = WASM_VALTYPE_%s; memcpy(&out.%s, &r, sizeof(r));\n", toupper(dst), dst > source
    print  "    if (!stack_push(ctx->operand_stack, out))" > source
    print  "        return exec_fail(ctx->error, EXEC_ERROR_TRAP, \"stack overflow\");" > source
    print  "    return EXEC_OK;" > source
    print  "}" > source
    print  "" > source
}

# ---- f32.demote_f64 ----
function emit_conv_demote(nm) {
    printf "int execute_op_%s(waste_exec_context *ctx, const exec_instr *instr) {\n", nm > source
    print  "    (void)instr;" > source
    print  "    wasm_value v;" > source
    print  "    if (!stack_pop(ctx->operand_stack, &v) || v.type != WASM_VALTYPE_F64)" > source
    print  "        return exec_fail(ctx->error, EXEC_ERROR_TRAP, \"conversion operand missing\");" > source
    print  "    double d; memcpy(&d, &v.f64, 8);" > source
    print  "    float r = (float)d;" > source
    print  "    wasm_value out; memset(&out, 0, sizeof(out));" > source
    print  "    out.type = WASM_VALTYPE_F32; memcpy(&out.f32, &r, 4);" > source
    print  "    if (!stack_push(ctx->operand_stack, out))" > source
    print  "        return exec_fail(ctx->error, EXEC_ERROR_TRAP, \"stack overflow\");" > source
    print  "    return EXEC_OK;" > source
    print  "}" > source
    print  "" > source
}

# ---- f64.promote_f32 ----
function emit_conv_promote(nm) {
    printf "int execute_op_%s(waste_exec_context *ctx, const exec_instr *instr) {\n", nm > source
    print  "    (void)instr;" > source
    print  "    wasm_value v;" > source
    print  "    if (!stack_pop(ctx->operand_stack, &v) || v.type != WASM_VALTYPE_F32)" > source
    print  "        return exec_fail(ctx->error, EXEC_ERROR_TRAP, \"conversion operand missing\");" > source
    print  "    float f; memcpy(&f, &v.f32, 4);" > source
    print  "    double r = (double)f;" > source
    print  "    wasm_value out; memset(&out, 0, sizeof(out));" > source
    print  "    out.type = WASM_VALTYPE_F64; memcpy(&out.f64, &r, 8);" > source
    print  "    if (!stack_push(ctx->operand_stack, out))" > source
    print  "        return exec_fail(ctx->error, EXEC_ERROR_TRAP, \"stack overflow\");" > source
    print  "    return EXEC_OK;" > source
    print  "}" > source
    print  "" > source
}

# ---- Truncation with range check (trapping) ----
# params: src_field ; dst_field ; min_bound ; max_bound ; lo_op ; assign_expr
function emit_trunc(nm, idx,    src, dst, lo, hi, lo_op, expr, ft, sz) {
    src   = params[idx, 0]
    dst   = params[idx, 1]
    lo    = params[idx, 2]
    hi    = params[idx, 3]
    lo_op = params[idx, 4]
    expr  = params[idx, 5]
    if (src == "f32") { ft = "float"; sz = 4 }
    else              { ft = "double"; sz = 8 }
    printf "int execute_op_%s(waste_exec_context *ctx, const exec_instr *instr) {\n", nm > source
    print  "    (void)instr;" > source
    print  "    wasm_value v;" > source
    printf "    if (!stack_pop(ctx->operand_stack, &v) || v.type != WASM_VALTYPE_%s)\n", toupper(src) > source
    print  "        return exec_fail(ctx->error, EXEC_ERROR_TRAP, \"conversion operand missing\");" > source
    printf "    %s f; memcpy(&f, &v.%s, %d);\n", ft, src, sz > source
    printf "    if (f != f || f %s %s || f >= %s)\n", lo_op, lo, hi > source
    print  "        return exec_fail(ctx->error, EXEC_ERROR_TRAP, \"invalid conversion to integer\");" > source
    print  "    wasm_value out; memset(&out, 0, sizeof(out));" > source
    printf "    out.type = WASM_VALTYPE_%s; %s;\n", toupper(dst), expr > source
    print  "    if (!stack_push(ctx->operand_stack, out))" > source
    print  "        return exec_fail(ctx->error, EXEC_ERROR_TRAP, \"stack overflow\");" > source
    print  "    return EXEC_OK;" > source
    print  "}" > source
    print  "" > source
}

# ---- Reinterpret (memcpy between fields) ----
# params: src_field | dst_field | byte_width
function emit_reinterpret(nm, idx,    src, dst, sz, src_int, dst_int) {
    src = params[idx, 0]
    dst = params[idx, 1]
    sz  = params[idx, 2]
    if (sz == 4) { src_int = "uint32_t"; dst_int = "uint32_t" }
    else         { src_int = "uint64_t"; dst_int = "uint64_t" }
    printf "int execute_op_%s(waste_exec_context *ctx, const exec_instr *instr) {\n", nm > source
    print  "    (void)instr;" > source
    print  "    wasm_value v;" > source
    printf "    if (!stack_pop(ctx->operand_stack, &v) || v.type != WASM_VALTYPE_%s)\n", toupper(src) > source
    print  "        return exec_fail(ctx->error, EXEC_ERROR_TRAP, \"reinterpret operand missing\");" > source
    print  "    wasm_value out; memset(&out, 0, sizeof(out));" > source
    printf "    out.type = WASM_VALTYPE_%s;\n", toupper(dst) > source
    # Determine field accessors based on type
    if (src == "f32" && dst == "i32") {
        printf "    %s tmp; memcpy(&tmp, &v.f32, %s); out.i32 = (int32_t)tmp;\n", src_int, sz > source
    } else if (src == "f64" && dst == "i64") {
        printf "    %s tmp; memcpy(&tmp, &v.f64, %s); out.i64 = (int64_t)tmp;\n", src_int, sz > source
    } else if (src == "i32" && dst == "f32") {
        printf "    %s tmp = (uint32_t)v.i32; memcpy(&out.f32, &tmp, %s);\n", src_int, sz > source
    } else if (src == "i64" && dst == "f64") {
        printf "    %s tmp = (uint64_t)v.i64; memcpy(&out.f64, &tmp, %s);\n", src_int, sz > source
    }
    print  "    if (!stack_push(ctx->operand_stack, out))" > source
    print  "        return exec_fail(ctx->error, EXEC_ERROR_TRAP, \"stack overflow\");" > source
    print  "    return EXEC_OK;" > source
    print  "}" > source
    print  "" > source
}

# ---- Dispatch table emission ----
function emit_dispatch_table(    i, opcode, exec_name) {
    print "/* ---- Main dispatch table ---- */" > source
    print "" > source
    print "static const wasm_opcode_dispatch dispatch_table[256] = {" > source
    for (i = 0; i < n; i++) {
        if (prefix[i] != "-") continue
        opcode = sub_op[i]
        if (template[i] == "CUSTOM") {
            exec_name = params[i, 0]
        } else {
            exec_name = "execute_op_" name[i]
        }
        printf "    [%s] = { %s, %s },\n", opcode, exec_name, validate[i] > source
    }
    print "};" > source
    print "" > source

    # Lookup function
    print "const wasm_opcode_dispatch *wasm_opcode_get_dispatch(const exec_instr *instr) {" > source
    print "    if (instr->opcode > 0xff) return NULL;" > source
    print "    const wasm_opcode_dispatch *entry = &dispatch_table[instr->opcode];" > source
    print "    if (!entry->execute && !entry->validate) return NULL;" > source
    print "    return entry;" > source
    print "}" > source
}
