(module
  (import "waste_kernel" "startup_v1" (func $startup (result i32)))
  (memory 1)
  (func (export "_start") (local $argv i32) (local $argument i32)
    (if (i32.ne (i32.load (call $startup)) (i32.const 5)) (then unreachable))
    (local.set $argv (i32.load offset=4 (call $startup)))
    (local.set $argument (i32.load offset=4 (local.get $argv)))
    (if (i64.ne (i64.load (local.get $argument)) (i64.const 0x64726f77206f7774)) (then unreachable))
    (if (i32.ne (i32.load8_u offset=8 (local.get $argument)) (i32.const 115)) (then unreachable))
    (if (i32.load8_u offset=9 (local.get $argument)) (then unreachable))
    (local.set $argument (i32.load offset=8 (local.get $argv)))
    (if (i32.ne (i32.load (local.get $argument)) (i32.const 0x6e652d2d)) (then unreachable))
    (if (i32.ne (i32.load8_u offset=4 (local.get $argument)) (i32.const 118)) (then unreachable))
    (if (i32.load8_u offset=5 (local.get $argument)) (then unreachable))
    (if (i32.load8_u (i32.load offset=16 (local.get $argv))) (then unreachable))))
