;; Three sleepers must arm at the same clock value. A parent waiting for the
;; longest sleeper must not prevent its shorter siblings from becoming ready.
(module
  (import "env" "fork" (func $fork (result i32)))
  (import "env" "exit" (func $exit (param i32)))
  (import "env" "waitpid" (func $wait (param i32 i32 i32) (result i32)))
  (import "env" "select" (func $select (param i32 i32 i32 i32 i32) (result i32)))
  (import "env" "write" (func $write (param i32 i32 i32) (result i32)))
  (import "env" "setpgid" (func $setpgid (param i32 i32) (result i32)))
  (import "env" "kill" (func $kill (param i32 i32) (result i32)))
  (memory 1)
  (data (i32.const 64) "ARMED\0aONE\0aTWO\0aTHREE\0aGROUP\0a")
  (func $sleep (param $us i32) (param $offset i32) (param $length i32) (param $code i32)
    (i64.store (i32.const 128) (i64.const 0))
    (i32.store (i32.const 136) (local.get $us))
    (if (call $select (i32.const 0) (i32.const 0) (i32.const 0) (i32.const 0) (i32.const 128))
      (then unreachable))
    (drop (call $write (i32.const 1) (local.get $offset) (local.get $length)))
    (call $exit (local.get $code)))
  (func $reap (param $pid i32) (param $code i32)
    (if (i32.ne (call $wait (local.get $pid) (i32.const 160) (i32.const 0)) (local.get $pid))
      (then unreachable))
    (if (i32.ne (i32.load (i32.const 160)) (i32.shl (local.get $code) (i32.const 8)))
      (then unreachable)))
  (func (export "overlap") (result i32)
    (local $long i32) (local $middle i32) (local $short i32)
    (local.set $long (call $fork))
    (if (i32.eqz (local.get $long)) (then (call $sleep (i32.const 300000) (i32.const 78) (i32.const 6) (i32.const 3))))
    (local.set $middle (call $fork))
    (if (i32.eqz (local.get $middle)) (then (call $sleep (i32.const 200000) (i32.const 74) (i32.const 4) (i32.const 2))))
    (local.set $short (call $fork))
    (if (i32.eqz (local.get $short)) (then (call $sleep (i32.const 100000) (i32.const 70) (i32.const 4) (i32.const 1))))
    ;; WNOHANG must report live children without modifying the status buffer.
    (i32.store (i32.const 160) (i32.const 12345))
    (if (call $wait (i32.const -1) (i32.const 160) (i32.const 1)) (then unreachable))
    (if (i32.ne (i32.load (i32.const 160)) (i32.const 12345)) (then unreachable))
    (drop (call $write (i32.const 1) (i32.const 64) (i32.const 6)))
    (call $reap (local.get $long) (i32.const 3))
    (call $reap (local.get $middle) (i32.const 2))
    (call $reap (local.get $short) (i32.const 1))
    (i32.const 3))
  ;; Parent and child coexist while the parent configures the job's group,
  ;; sleeps, terminates that group, and reaps the signal wait status.
  (func (export "group_kill") (result i32) (local $pid i32)
    (local.set $pid (call $fork))
    (if (i32.eqz (local.get $pid)) (then
      (drop (call $select (i32.const 0) (i32.const 0) (i32.const 0) (i32.const 0) (i32.const 0)))
      unreachable))
    ;; The legacy env adapter reports the resulting pgid; libc normalizes it.
    (if (i32.ne (call $setpgid (local.get $pid) (local.get $pid)) (local.get $pid))
      (then unreachable))
    (i64.store (i32.const 128) (i64.const 0))
    (i32.store (i32.const 136) (i32.const 100000))
    (drop (call $write (i32.const 1) (i32.const 84) (i32.const 6)))
    (drop (call $select (i32.const 0) (i32.const 0) (i32.const 0) (i32.const 0) (i32.const 128)))
    (if (call $kill (i32.sub (i32.const 0) (local.get $pid)) (i32.const 15)) (then unreachable))
    (if (i32.ne (call $wait (local.get $pid) (i32.const 160) (i32.const 0)) (local.get $pid))
      (then unreachable))
    (i32.load (i32.const 160))))
(assert_return (invoke "overlap") (i32.const 3))
(assert_return (invoke "group_kill") (i32.const 15))
