;; Guest counterparts of c-engine-continuation.c. A positive timed select
;; supplies the real engine wait/resume boundary; no synthetic host.pause import.
;; Explicit C snapshot capture/restore and replay counters remain private gates.
(module $provider
  (type $nullary (func (result i32)))
  (import "env" "select" (func $select (param i32 i32 i32 i32 i32) (result i32)))
  (import "env" "sigsetjmp" (func $setjmp (param i32) (result i32)))
  (import "env" "siglongjmp" (func $longjmp (param i32 i32)))
  (memory 1)
  (global $started (mut i32) (i32.const 0))
  (global $completed (mut i32) (i32.const 0))
  (table 1 funcref)
  (elem (i32.const 0) $pause)
  (func $pause (result i32)
    (global.set $started (i32.add (global.get $started) (i32.const 1)))
    (i64.store (i32.const 256) (i64.const 0))
    (i64.store (i32.const 264) (i64.const 30000))
    (if (call $select (i32.const 0) (i32.const 0) (i32.const 0) (i32.const 0) (i32.const 256))
      (then unreachable))
    (global.set $completed (i32.add (global.get $completed) (i32.const 1)))
    (i32.const 41))
  (func (export "run") (result i32) (i32.add (call $pause) (i32.const 1)))
  (func (export "run_indirect") (result i32)
    (i32.add (call_indirect (type $nullary) (i32.const 0)) (i32.const 2)))
  (func (export "run_jump") (result i32) (call $jump (i32.const 7)))
  (func $jump (export "jump_value") (param $value i32) (result i32) (local $jump i32)
    (local.set $jump (call $setjmp (i32.const 64)))
    (if (result i32) (i32.eqz (local.get $jump))
      (then
        (drop (call $pause))
        (call $longjmp (i32.const 64) (local.get $value))
        (i32.const -1))
      (else (local.get $jump))))
  (func (export "counts") (result i32 i32) (global.get $started) (global.get $completed)))
(register "provider" $provider)
(module $consumer
  (import "provider" "run" (func $run (result i32)))
  (memory 1)
  ;; Wrong caller memory would supply an invalid timeout, and overwrite this canary.
  (data (i32.const 256) "\ff\ff\ff\ff\ff\ff\ff\ff")
  (func (export "run_consumer") (result i32) (i32.add (call $run) (i32.const 3)))
  (func (export "canary") (result i64) (i64.load (i32.const 256))))
(module $memoryless
  (import "provider" "run" (func $run (result i32)))
  (func (export "run_consumer") (result i32) (i32.add (call $run) (i32.const 3))))
(assert_return (invoke $provider "run") (i32.const 42))
(assert_return (invoke $provider "counts") (i32.const 1) (i32.const 1))
(assert_return (invoke $provider "run") (i32.const 42))
(assert_return (invoke $provider "counts") (i32.const 2) (i32.const 2))
(assert_return (invoke $provider "run_indirect") (i32.const 43))
(assert_return (invoke $provider "counts") (i32.const 3) (i32.const 3))
(assert_return (invoke $provider "run_indirect") (i32.const 43))
(assert_return (invoke $provider "counts") (i32.const 4) (i32.const 4))
(assert_return (invoke $provider "run_jump") (i32.const 7))
(assert_return (invoke $provider "counts") (i32.const 5) (i32.const 5))
(assert_return (invoke $provider "run_jump") (i32.const 7))
(assert_return (invoke $provider "counts") (i32.const 6) (i32.const 6))
(assert_return (invoke $consumer "run_consumer") (i32.const 45))
(assert_return (invoke $provider "counts") (i32.const 7) (i32.const 7))
(assert_return (invoke $consumer "run_consumer") (i32.const 45))
(assert_return (invoke $provider "counts") (i32.const 8) (i32.const 8))
(assert_return (invoke $memoryless "run_consumer") (i32.const 45))
(assert_return (invoke $provider "counts") (i32.const 9) (i32.const 9))
(assert_return (invoke $consumer "canary") (i64.const -1))
(assert_return (invoke $provider "jump_value" (i32.const 0)) (i32.const 1))
(assert_return (invoke $provider "counts") (i32.const 10) (i32.const 10))
(assert_return (invoke $provider "jump_value" (i32.const -9)) (i32.const -9))
(assert_return (invoke $provider "counts") (i32.const 11) (i32.const 11))
