;; Guest-visible directory iteration and file creation masks.
;; Files are created through real imports in an isolated kernel namespace.
;; Exact host-seeded inode values, injected timestamps and clone ownership stay C.
;; readdir_v1 returns raw negative errno; open/stat/close use -1 plus errno.
(module
  (import "env" "readdir_v1" (func $readdir (param i32 i32 i32 i32) (result i32)))
  (import "env" "mkdir" (func $mkdir (param i32 i32) (result i32)))
  (import "env" "open" (func $open (param i32 i32 i32) (result i32)))
  (import "env" "close" (func $close (param i32) (result i32)))
  (import "env" "dup" (func $dup (param i32) (result i32)))
  (import "env" "stat" (func $stat (param i32 i32) (result i32)))
  (import "env" "read" (func $read (param i32 i32 i32) (result i32)))
  (import "env" "write" (func $write (param i32 i32 i32) (result i32)))
  (import "env" "shm_open" (func $shm_open (param i32 i32 i32) (result i32)))
  (import "env" "shm_unlink" (func $shm_unlink (param i32) (result i32)))
  (import "env" "umask" (func $umask (param i32) (result i32)))
  (memory 1)
  (global $dir (mut i32) (i32.const -1))
  (global $alias (mut i32) (i32.const -1))
  (global $other (mut i32) (i32.const -1))
  (global $file (mut i32) (i32.const -1))
  ;; errno 8; name 512..543, metadata 768..815, stat 1024..1151.
  ;; Adjacent canaries surround both readdir output ranges.
  (data (i32.const 32) "/tmp/dir-mask\00")
  (data (i32.const 64) "/tmp/dir-mask/child\00")
  (data (i32.const 96) "/tmp/dir-mask/child/file\00")
  (data (i32.const 128) "/tmp/dir-mask/default\00")
  (data (i32.const 160) "/tmp/dir-mask/private\00")
  (data (i32.const 192) "/tmp/dir-mask/group\00")
  (data (i32.const 224) "/tmp/dir-mask/zero\00")
  (data (i32.const 256) "/tmp/dir-mask/exclusive\00")
  (data (i32.const 288) "/\00")
  (data (i32.const 320) "/tmp/dir-mask/missing\00")
  (data (i32.const 352) ".\00")
  (data (i32.const 360) "..\00")
  (data (i32.const 368) "file\00")
  (data (i32.const 400) "keep")
  (data (i32.const 448) "/dir-mask-exclusive-shm\00")
  (func (export "__errno_location") (result i32) (i32.const 8))
  (func (export "errno") (result i32) (i32.load (i32.const 8)))
  (func $reset_errno (i32.store (i32.const 8) (i32.const 0)))
  (func $success_fd (param i32) (result i32)
    (if (result i32) (i32.lt_s (local.get 0) (i32.const 0))
      (then (local.get 0)) (else (i32.const 0))))
  (func (export "mkdir") (param i32 i32) (result i32)
    (call $reset_errno) (call $mkdir (local.get 0) (local.get 1)))
  (func (export "open_file") (param i32 i32 i32) (result i32)
    (call $reset_errno)
    (global.set $file (call $open (local.get 0) (local.get 1) (local.get 2)))
    (call $success_fd (global.get $file)))
  (func (export "shm_open") (result i32)
    (call $reset_errno)
    (global.set $file (call $shm_open (i32.const 448) (i32.const 194) (i32.const 384)))
    (call $success_fd (global.get $file)))
  (func (export "shm_unlink") (result i32)
    (call $reset_errno) (call $shm_unlink (i32.const 448)))
  (func (export "write_file") (result i32)
    (call $write (global.get $file) (i32.const 400) (i32.const 4)))
  (func (export "read_file") (result i32)
    (call $read (global.get $file) (i32.const 1280) (i32.const 4)))
  (func (export "file_bytes") (result i32) (i32.load (i32.const 1280)))
  (func (export "close_file") (result i32)
    (call $reset_errno) (call $close (global.get $file)))
  (func (export "open_dir") (param i32) (result i32)
    (call $reset_errno) (global.set $dir (call $open (local.get 0) (i32.const 0) (i32.const 0)))
    (call $success_fd (global.get $dir)))
  (func (export "open_other") (param i32) (result i32)
    (call $reset_errno) (global.set $other (call $open (local.get 0) (i32.const 0) (i32.const 0)))
    (call $success_fd (global.get $other)))
  (func (export "dup_dir") (result i32)
    (call $reset_errno) (global.set $alias (call $dup (global.get $dir)))
    (call $success_fd (global.get $alias)))
  (func $fd (param i32) (result i32)
    (if (i32.eqz (local.get 0)) (then (return (global.get $dir))))
    (if (i32.eq (local.get 0) (i32.const 1)) (then (return (global.get $alias))))
    (if (i32.eq (local.get 0) (i32.const 2)) (then (return (global.get $other))))
    (global.get $file))
  (func (export "close_dir") (param i32) (result i32)
    (call $reset_errno) (call $close (call $fd (local.get 0))))
  (func (export "stat") (param i32) (result i32)
    (call $reset_errno) (call $stat (local.get 0) (i32.const 1024)))
  (func (export "stat_permissions") (result i32)
    (i32.and (i32.load (i32.const 1040)) (i32.const 4095)))
  (func (export "stat_type") (result i32)
    (i32.and (i32.load (i32.const 1040)) (i32.const 61440)))
  (func (export "stat_inode_nonzero") (result i32)
    (i64.ne (i64.load (i32.const 1032)) (i64.const 0)))
  (func (export "umask") (param i32) (result i32) (call $umask (local.get 0)))
  (func (export "prepare") (result i32)
    (memory.fill (i32.const 512) (i32.const 165) (i32.const 32))
    (memory.fill (i32.const 768) (i32.const 165) (i32.const 48))
    (i32.store (i32.const 508) (i32.const 0x13579bdf))
    (i32.store (i32.const 544) (i32.const 0x13579bdf))
    (i32.store (i32.const 764) (i32.const 0x13579bdf))
    (i32.store (i32.const 816) (i32.const 0x13579bdf))
    (i32.const 1))
  (func (export "canaries") (result i32)
    (i32.and
      (i32.and (i32.eq (i32.load (i32.const 508)) (i32.const 0x13579bdf))
        (i32.eq (i32.load (i32.const 544)) (i32.const 0x13579bdf)))
      (i32.and (i32.eq (i32.load (i32.const 764)) (i32.const 0x13579bdf))
        (i32.eq (i32.load (i32.const 816)) (i32.const 0x13579bdf)))))
  (func $untouched (param $address i32) (param $length i32) (result i32) (local $i i32)
    (if (i32.eqz (local.get $length)) (then (return (i32.const 1))))
    (loop $next
      (if (i32.ne (i32.load8_u (i32.add (local.get $address) (local.get $i))) (i32.const 165))
        (then (return (i32.const 0))))
      (local.set $i (i32.add (local.get $i) (i32.const 1)))
      (br_if $next (i32.lt_u (local.get $i) (local.get $length))))
    (i32.const 1))
  (func (export "name_tail") (param $capacity i32) (result i32)
    (call $untouched (i32.add (i32.const 512) (local.get $capacity))
      (i32.sub (i32.const 32) (local.get $capacity))))
  (func (export "untouched") (result i32)
    (i32.and (call $untouched (i32.const 512) (i32.const 32))
      (call $untouched (i32.const 768) (i32.const 48))))
  (func (export "next") (param i32 i32) (result i32)
    (call $reset_errno)
    (call $readdir (call $fd (local.get 0)) (i32.const 512) (local.get 1) (i32.const 768)))
  (func (export "next_fd") (param i32) (result i32)
    (call $reset_errno)
    (call $readdir (local.get 0) (i32.const 512) (i32.const 32) (i32.const 768)))
  (func (export "bad_metadata") (result i32)
    (call $reset_errno)
    (call $readdir (global.get $dir) (i32.const 512) (i32.const 32) (i32.const 65520)))
  (func (export "name") (param $expected i32) (result i32) (local $i i32) (local $byte i32)
    (loop $next
      (local.set $byte (i32.load8_u (i32.add (local.get $expected) (local.get $i))))
      (if (i32.ne (local.get $byte) (i32.load8_u (i32.add (i32.const 512) (local.get $i))))
        (then (return (i32.const 0))))
      (if (i32.eqz (local.get $byte)) (then (return (i32.const 1))))
      (local.set $i (i32.add (local.get $i) (i32.const 1)))
      (br_if $next (i32.lt_u (local.get $i) (i32.const 32))))
    (i32.const 0))
  (func (export "kind") (result i32) (i32.load (i32.const 768)))
  (func (export "inode_matches_stat") (result i32)
    (i64.eq (i64.load (i32.const 792)) (i64.load (i32.const 1032))))
  (func (export "mode_matches_stat") (result i32)
    (i32.eq (i32.load (i32.const 772))
      (i32.and (i32.load (i32.const 1040)) (i32.const 4095)))))

;; Create the directory tree and file through guest imports.
(assert_return (invoke "mkdir" (i32.const 32) (i32.const 493)) (i32.const 0))
(assert_return (invoke "mkdir" (i32.const 64) (i32.const 488)) (i32.const 0))
(assert_return (invoke "open_file" (i32.const 96) (i32.const 66) (i32.const 420)) (i32.const 0))
(assert_return (invoke "close_file") (i32.const 0))
(assert_return (invoke "open_dir" (i32.const 64)) (i32.const 0))
;; Short names and an invalid metadata range do not consume an entry.
(assert_return (invoke "prepare") (i32.const 1))
(assert_return (invoke "bad_metadata") (i32.const -14))
(assert_return (invoke "untouched") (i32.const 1))
(assert_return (invoke "canaries") (i32.const 1))
(assert_return (invoke "prepare") (i32.const 1))
(assert_return (invoke "next" (i32.const 0) (i32.const 1)) (i32.const -34))
(assert_return (invoke "errno") (i32.const 34))
(assert_return (invoke "untouched") (i32.const 1))
(assert_return (invoke "canaries") (i32.const 1))
(assert_return (invoke "stat" (i32.const 64)) (i32.const 0))
(assert_return (invoke "stat_inode_nonzero") (i32.const 1))
(assert_return (invoke "next" (i32.const 0) (i32.const 2)) (i32.const 1))
(assert_return (invoke "name" (i32.const 352)) (i32.const 1))
(assert_return (invoke "kind") (i32.const 2))
(assert_return (invoke "inode_matches_stat") (i32.const 1))
(assert_return (invoke "mode_matches_stat") (i32.const 1))
(assert_return (invoke "name_tail" (i32.const 2)) (i32.const 1))
(assert_return (invoke "canaries") (i32.const 1))
(assert_return (invoke "prepare") (i32.const 1))
(assert_return (invoke "next" (i32.const 0) (i32.const 2)) (i32.const -34))
(assert_return (invoke "errno") (i32.const 34))
(assert_return (invoke "untouched") (i32.const 1))
(assert_return (invoke "canaries") (i32.const 1))
(assert_return (invoke "stat" (i32.const 32)) (i32.const 0))
(assert_return (invoke "stat_inode_nonzero") (i32.const 1))
(assert_return (invoke "next" (i32.const 0) (i32.const 3)) (i32.const 1))
(assert_return (invoke "name" (i32.const 360)) (i32.const 1))
(assert_return (invoke "kind") (i32.const 2))
(assert_return (invoke "inode_matches_stat") (i32.const 1))
(assert_return (invoke "mode_matches_stat") (i32.const 1))
(assert_return (invoke "name_tail" (i32.const 3)) (i32.const 1))
(assert_return (invoke "canaries") (i32.const 1))
(assert_return (invoke "prepare") (i32.const 1))
(assert_return (invoke "next" (i32.const 0) (i32.const 4)) (i32.const -34))
(assert_return (invoke "errno") (i32.const 34))
(assert_return (invoke "untouched") (i32.const 1))
(assert_return (invoke "canaries") (i32.const 1))
(assert_return (invoke "stat" (i32.const 96)) (i32.const 0))
(assert_return (invoke "stat_inode_nonzero") (i32.const 1))
(assert_return (invoke "next" (i32.const 0) (i32.const 32)) (i32.const 1))
(assert_return (invoke "name" (i32.const 368)) (i32.const 1))
(assert_return (invoke "kind") (i32.const 1))
(assert_return (invoke "inode_matches_stat") (i32.const 1))
(assert_return (invoke "mode_matches_stat") (i32.const 1))
(assert_return (invoke "name_tail" (i32.const 32)) (i32.const 1))
(assert_return (invoke "canaries") (i32.const 1))
;; End-of-directory repeats without changing either output range.
(assert_return (invoke "prepare") (i32.const 1))
(assert_return (invoke "next" (i32.const 0) (i32.const 32)) (i32.const 0))
(assert_return (invoke "untouched") (i32.const 1))
(assert_return (invoke "canaries") (i32.const 1))
(assert_return (invoke "prepare") (i32.const 1))
(assert_return (invoke "next" (i32.const 0) (i32.const 32)) (i32.const 0))
(assert_return (invoke "untouched") (i32.const 1))
(assert_return (invoke "canaries") (i32.const 1))
(assert_return (invoke "close_dir" (i32.const 0)) (i32.const 0))
;; Root dot and parent dot resolve to the same root identity.
(assert_return (invoke "open_dir" (i32.const 288)) (i32.const 0))
(assert_return (invoke "prepare") (i32.const 1))
(assert_return (invoke "stat" (i32.const 288)) (i32.const 0))
(assert_return (invoke "stat_inode_nonzero") (i32.const 1))
(assert_return (invoke "next" (i32.const 0) (i32.const 32)) (i32.const 1))
(assert_return (invoke "name" (i32.const 352)) (i32.const 1))
(assert_return (invoke "kind") (i32.const 2))
(assert_return (invoke "inode_matches_stat") (i32.const 1))
(assert_return (invoke "mode_matches_stat") (i32.const 1))
(assert_return (invoke "name_tail" (i32.const 32)) (i32.const 1))
(assert_return (invoke "canaries") (i32.const 1))
(assert_return (invoke "stat" (i32.const 288)) (i32.const 0))
(assert_return (invoke "stat_inode_nonzero") (i32.const 1))
(assert_return (invoke "next" (i32.const 0) (i32.const 32)) (i32.const 1))
(assert_return (invoke "name" (i32.const 360)) (i32.const 1))
(assert_return (invoke "kind") (i32.const 2))
(assert_return (invoke "inode_matches_stat") (i32.const 1))
(assert_return (invoke "mode_matches_stat") (i32.const 1))
(assert_return (invoke "name_tail" (i32.const 32)) (i32.const 1))
(assert_return (invoke "canaries") (i32.const 1))
(assert_return (invoke "close_dir" (i32.const 0)) (i32.const 0))
;; Dup shares the iteration cursor; a separate open starts independently.
(assert_return (invoke "open_dir" (i32.const 64)) (i32.const 0))
(assert_return (invoke "dup_dir") (i32.const 0))
(assert_return (invoke "open_other" (i32.const 64)) (i32.const 0))
(assert_return (invoke "prepare") (i32.const 1))
(assert_return (invoke "stat" (i32.const 64)) (i32.const 0))
(assert_return (invoke "stat_inode_nonzero") (i32.const 1))
(assert_return (invoke "next" (i32.const 0) (i32.const 32)) (i32.const 1))
(assert_return (invoke "name" (i32.const 352)) (i32.const 1))
(assert_return (invoke "kind") (i32.const 2))
(assert_return (invoke "inode_matches_stat") (i32.const 1))
(assert_return (invoke "mode_matches_stat") (i32.const 1))
(assert_return (invoke "name_tail" (i32.const 32)) (i32.const 1))
(assert_return (invoke "canaries") (i32.const 1))
(assert_return (invoke "stat" (i32.const 32)) (i32.const 0))
(assert_return (invoke "stat_inode_nonzero") (i32.const 1))
(assert_return (invoke "next" (i32.const 1) (i32.const 32)) (i32.const 1))
(assert_return (invoke "name" (i32.const 360)) (i32.const 1))
(assert_return (invoke "kind") (i32.const 2))
(assert_return (invoke "inode_matches_stat") (i32.const 1))
(assert_return (invoke "mode_matches_stat") (i32.const 1))
(assert_return (invoke "name_tail" (i32.const 32)) (i32.const 1))
(assert_return (invoke "canaries") (i32.const 1))
(assert_return (invoke "stat" (i32.const 64)) (i32.const 0))
(assert_return (invoke "stat_inode_nonzero") (i32.const 1))
(assert_return (invoke "next" (i32.const 2) (i32.const 32)) (i32.const 1))
(assert_return (invoke "name" (i32.const 352)) (i32.const 1))
(assert_return (invoke "kind") (i32.const 2))
(assert_return (invoke "inode_matches_stat") (i32.const 1))
(assert_return (invoke "mode_matches_stat") (i32.const 1))
(assert_return (invoke "name_tail" (i32.const 32)) (i32.const 1))
(assert_return (invoke "canaries") (i32.const 1))
(assert_return (invoke "stat" (i32.const 96)) (i32.const 0))
(assert_return (invoke "stat_inode_nonzero") (i32.const 1))
(assert_return (invoke "next" (i32.const 0) (i32.const 32)) (i32.const 1))
(assert_return (invoke "name" (i32.const 368)) (i32.const 1))
(assert_return (invoke "kind") (i32.const 1))
(assert_return (invoke "inode_matches_stat") (i32.const 1))
(assert_return (invoke "mode_matches_stat") (i32.const 1))
(assert_return (invoke "name_tail" (i32.const 32)) (i32.const 1))
(assert_return (invoke "canaries") (i32.const 1))
(assert_return (invoke "prepare") (i32.const 1))
(assert_return (invoke "next" (i32.const 1) (i32.const 32)) (i32.const 0))
(assert_return (invoke "untouched") (i32.const 1))
(assert_return (invoke "canaries") (i32.const 1))
(assert_return (invoke "close_dir" (i32.const 0)) (i32.const 0))
(assert_return (invoke "stat" (i32.const 32)) (i32.const 0))
(assert_return (invoke "stat_inode_nonzero") (i32.const 1))
(assert_return (invoke "next" (i32.const 2) (i32.const 32)) (i32.const 1))
(assert_return (invoke "name" (i32.const 360)) (i32.const 1))
(assert_return (invoke "kind") (i32.const 2))
(assert_return (invoke "inode_matches_stat") (i32.const 1))
(assert_return (invoke "mode_matches_stat") (i32.const 1))
(assert_return (invoke "name_tail" (i32.const 32)) (i32.const 1))
(assert_return (invoke "canaries") (i32.const 1))
(assert_return (invoke "stat" (i32.const 96)) (i32.const 0))
(assert_return (invoke "stat_inode_nonzero") (i32.const 1))
(assert_return (invoke "next" (i32.const 2) (i32.const 32)) (i32.const 1))
(assert_return (invoke "name" (i32.const 368)) (i32.const 1))
(assert_return (invoke "kind") (i32.const 1))
(assert_return (invoke "inode_matches_stat") (i32.const 1))
(assert_return (invoke "mode_matches_stat") (i32.const 1))
(assert_return (invoke "name_tail" (i32.const 32)) (i32.const 1))
(assert_return (invoke "canaries") (i32.const 1))
(assert_return (invoke "prepare") (i32.const 1))
(assert_return (invoke "next" (i32.const 2) (i32.const 32)) (i32.const 0))
(assert_return (invoke "untouched") (i32.const 1))
(assert_return (invoke "canaries") (i32.const 1))
(assert_return (invoke "close_dir" (i32.const 1)) (i32.const 0))
(assert_return (invoke "close_dir" (i32.const 2)) (i32.const 0))
;; Wrong-kind and invalid descriptors report raw errors and preserve outputs.
(assert_return (invoke "open_file" (i32.const 96) (i32.const 0) (i32.const 0)) (i32.const 0))
(assert_return (invoke "prepare") (i32.const 1))
(assert_return (invoke "next" (i32.const 3) (i32.const 32)) (i32.const -20))
(assert_return (invoke "errno") (i32.const 20))
(assert_return (invoke "untouched") (i32.const 1))
(assert_return (invoke "canaries") (i32.const 1))
(assert_return (invoke "close_file") (i32.const 0))
(assert_return (invoke "prepare") (i32.const 1))
(assert_return (invoke "next_fd" (i32.const 50)) (i32.const -9))
(assert_return (invoke "errno") (i32.const 9))
(assert_return (invoke "untouched") (i32.const 1))
(assert_return (invoke "canaries") (i32.const 1))
(assert_return (invoke "prepare") (i32.const 1))
(assert_return (invoke "next_fd" (i32.const -1)) (i32.const -22))
(assert_return (invoke "errno") (i32.const 22))
(assert_return (invoke "untouched") (i32.const 1))
(assert_return (invoke "canaries") (i32.const 1))
;; Default and changed creation masks apply to newly created files.
(assert_return (invoke "open_file" (i32.const 128) (i32.const 66) (i32.const 438)) (i32.const 0))
(assert_return (invoke "close_file") (i32.const 0))
(assert_return (invoke "stat" (i32.const 128)) (i32.const 0))
(assert_return (invoke "stat_type") (i32.const 32768))
(assert_return (invoke "stat_permissions") (i32.const 420))
(assert_return (invoke "umask" (i32.const 63)) (i32.const 18))
(assert_return (invoke "open_file" (i32.const 160) (i32.const 66) (i32.const 438)) (i32.const 0))
(assert_return (invoke "close_file") (i32.const 0))
(assert_return (invoke "stat" (i32.const 160)) (i32.const 0))
(assert_return (invoke "stat_permissions") (i32.const 384))
(assert_return (invoke "umask" (i32.const 2)) (i32.const 63))
(assert_return (invoke "open_file" (i32.const 192) (i32.const 66) (i32.const 438)) (i32.const 0))
(assert_return (invoke "close_file") (i32.const 0))
(assert_return (invoke "stat" (i32.const 192)) (i32.const 0))
(assert_return (invoke "stat_permissions") (i32.const 436))
;; A new mode argument does not change an existing file; mask only has 9 bits.
(assert_return (invoke "open_file" (i32.const 160) (i32.const 66) (i32.const 511)) (i32.const 0))
(assert_return (invoke "close_file") (i32.const 0))
(assert_return (invoke "stat" (i32.const 160)) (i32.const 0))
(assert_return (invoke "stat_permissions") (i32.const 384))
(assert_return (invoke "umask" (i32.const 65599)) (i32.const 2))
(assert_return (invoke "umask" (i32.const 511)) (i32.const 63))
(assert_return (invoke "open_file" (i32.const 224) (i32.const 66) (i32.const 438)) (i32.const 0))
(assert_return (invoke "close_file") (i32.const 0))
(assert_return (invoke "stat" (i32.const 224)) (i32.const 0))
(assert_return (invoke "stat_permissions") (i32.const 0))
(assert_return (invoke "umask" (i32.const 0)) (i32.const 511))
(assert_return (invoke "open_file" (i32.const 256) (i32.const 194) (i32.const 438)) (i32.const 0))
(assert_return (invoke "write_file") (i32.const 4))
(assert_return (invoke "close_file") (i32.const 0))
(assert_return (invoke "stat" (i32.const 256)) (i32.const 0))
(assert_return (invoke "stat_permissions") (i32.const 438))
(assert_return (invoke "open_file" (i32.const 256) (i32.const 194) (i32.const 438)) (i32.const -1))
(assert_return (invoke "errno") (i32.const 17))
;; An exclusive collision must fail before O_TRUNC can alter the old bytes.
(assert_return (invoke "open_file" (i32.const 256) (i32.const 706) (i32.const 438)) (i32.const -1))
(assert_return (invoke "errno") (i32.const 17))
(assert_return (invoke "open_file" (i32.const 256) (i32.const 0) (i32.const 0)) (i32.const 0))
(assert_return (invoke "read_file") (i32.const 4))
(assert_return (invoke "file_bytes") (i32.const 0x7065656b))
(assert_return (invoke "close_file") (i32.const 0))
(assert_return (invoke "open_file" (i32.const 64) (i32.const 194) (i32.const 438)) (i32.const -1))
(assert_return (invoke "errno") (i32.const 17))
(assert_return (invoke "stat" (i32.const 256)) (i32.const 0))
(assert_return (invoke "stat_permissions") (i32.const 438))
(assert_return (invoke "umask" (i32.const 18)) (i32.const 0))

;; Shared memory checks exclusivity in its namespace before opening the
;; already materialized backing path; ordinary open's check must not run twice.
(assert_return (invoke "shm_open") (i32.const 0))
(assert_return (invoke "close_file") (i32.const 0))
(assert_return (invoke "shm_open") (i32.const -17))
(assert_return (invoke "errno") (i32.const 17))
(assert_return (invoke "shm_unlink") (i32.const 0))
(assert_return (invoke "shm_open") (i32.const 0))
(assert_return (invoke "close_file") (i32.const 0))
(assert_return (invoke "shm_unlink") (i32.const 0))
