;; A saved Bash jump buffer survives temporary reuse by a nested activation.
;; The evaluator token is opaque guest data and copies with the buffer.
(module $jumps
  (import "env" "sigsetjmp" (func $save (param i32 i32) (result i32)))
  (import "env" "siglongjmp" (func $jump (param i32 i32)))
  (memory 1)
  (global $sp (export "__stack_pointer") (mut i32) (i32.const 1024))
  (func $inner
    (global.set $sp (i32.const 512))
    (drop (call $save (i32.const 64) (i32.const 0)))
    (global.set $sp (i32.const 256)))
  (func (export "run") (result i32 i32) (local $result i32)
    (global.set $sp (i32.const 1024))
    (local.set $result (call $save (i32.const 64) (i32.const 0)))
    (if (i32.eqz (local.get $result))
      (then
        (memory.copy (i32.const 128) (i32.const 64) (i32.const 4))
        (call $inner)
        (memory.copy (i32.const 64) (i32.const 128) (i32.const 4))
        (call $jump (i32.const 64) (i32.const 7))
        unreachable))
    (local.get $result)
    (global.get $sp))
  (func (export "zero") (result i32) (local $result i32)
    (local.set $result (call $save (i32.const 64) (i32.const 0)))
    (if (i32.eqz (local.get $result))
      (then (call $jump (i32.const 64) (i32.const 0)) unreachable))
    (local.get $result))
  (func (export "bad_save")
    (drop (call $save (i32.const 65534) (i32.const 0))))
  (func (export "bad_jump")
    (call $jump (i32.const 65534) (i32.const 1))))
(assert_return (invoke $jumps "run") (i32.const 7) (i32.const 1024))
(assert_return (invoke $jumps "run") (i32.const 7) (i32.const 1024))
(assert_return (invoke $jumps "zero") (i32.const 1))
(assert_trap (invoke $jumps "bad_save") "invalid setjmp buffer")
(assert_trap (invoke $jumps "bad_jump") "invalid longjmp buffer")
