#!/usr/bin/env python3

import argparse
import os
import shutil
import subprocess
import tempfile
from pathlib import Path


def named_module(source: str) -> str:
    marker = "(module"
    if not source.lstrip().startswith(marker):
        raise RuntimeError("waste-libc.wat must contain one top-level module")
    offset = source.index(marker)
    return source[:offset] + "(module $waste_libc" + source[offset + len(marker) :]


def main() -> None:
    parser = argparse.ArgumentParser(description="Build the WASTE guest libc core")
    parser.add_argument("--repo-root", type=Path, default=Path(__file__).resolve().parents[1])
    parser.add_argument("--wasm-as", default="wasm-as")
    args = parser.parse_args()

    root = args.repo_root.resolve()
    source_path = root / "libc" / "waste-libc.wat"
    client_root = root / "tests" / "libc-test"
    output_path = root / "build" / "waste-libc" / "waste-libc.wasm"
    fixture_root = root / "build" / "waste-libc" / "tests"
    environment = os.environ.copy()
    local_tool_bin = root / "build" / "toolchain" / "usr" / "bin"
    local_tool_lib = root / "build" / "toolchain" / "usr" / "lib"
    if not shutil.which("wasm-ld") and (local_tool_bin / "wasm-ld").is_file():
        environment["PATH"] = str(local_tool_bin) + os.pathsep + environment.get("PATH", "")
        environment["LD_LIBRARY_PATH"] = str(local_tool_lib) + os.pathsep + environment.get("LD_LIBRARY_PATH", "")

    source = source_path.read_text(encoding="utf-8")
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory(dir=output_path.parent) as temporary_name:
        temporary = Path(temporary_name)
        core_path = temporary / "core.wasm"
        helpers_path = temporary / "helpers.wasm"
        merged_path = temporary / "waste-libc.wasm"
        wat_path = temporary / "waste-libc.wat"
        subprocess.run(
            [args.wasm_as, str(source_path), "-o", str(core_path), "--enable-bulk-memory"],
            check=True,
        )
        subprocess.run(
            [
                "clang", "--target=wasm32", "-O2", "-nostdlib", "-fno-builtin",
                str(root / "libc" / "waste-libc-helpers.c"),
                "-Wl,--no-entry", "-Wl,--import-memory", "-Wl,--initial-memory=262144",
                "-Wl,--allow-undefined", "-Wl,--export-all", "-Wl,--strip-all",
                "-o", str(helpers_path),
            ],
            check=True,
            env=environment,
        )
        subprocess.run(
            ["wasm-merge", str(core_path), "env", str(helpers_path), "helpers",
             "-o", str(merged_path), "--enable-bulk-memory"],
            check=True,
        )
        subprocess.run(["wasm-dis", str(merged_path), "-o", str(wat_path)], check=True)
        merged_path.replace(output_path)
        module_source = wat_path.read_text(encoding="utf-8")

    fixture_root.mkdir(parents=True, exist_ok=True)
    for client_path in sorted(client_root.glob("*-client.wast.inc")):
        fixture_path = fixture_root / client_path.name.replace("-client.wast.inc", ".wast")
        fixture = (
            ";; Generated by tools/build-waste-libc.py; do not edit.\n"
            + named_module(module_source)
            + "\n"
            + client_path.read_text(encoding="utf-8")
        )
        fixture_path.write_text(fixture, encoding="utf-8")
    print(f"Built {output_path}")
    print(f"Generated libc WAST fixtures in {fixture_root}")


if __name__ == "__main__":
    main()
