#!/usr/bin/env python3

import argparse
import subprocess
import tempfile
from pathlib import Path


def named_module(source: str) -> str:
    marker = "(module"
    if not source.lstrip().startswith(marker):
        raise RuntimeError("waste-libc.wat must contain one top-level module")
    offset = source.index(marker)
    return source[:offset] + "(module $waste_libc" + source[offset + len(marker) :]


def main() -> None:
    parser = argparse.ArgumentParser(description="Build the WASTE guest libc core")
    parser.add_argument("--repo-root", type=Path, default=Path(__file__).resolve().parents[1])
    parser.add_argument("--wasm-as", default="wasm-as")
    args = parser.parse_args()

    root = args.repo_root.resolve()
    source_path = root / "libc" / "waste-libc.wat"
    client_path = root / "tests" / "libc-test" / "allocator-client.wast.inc"
    fixture_path = root / "tests" / "libc-test" / "allocator.wast"
    output_path = root / "build" / "waste-libc" / "waste-libc.wasm"

    source = source_path.read_text(encoding="utf-8")
    client = client_path.read_text(encoding="utf-8")
    fixture = (
        ";; Generated by tools/build-waste-libc.py; do not edit.\n"
        + named_module(source)
        + "\n"
        + client
    )
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile(dir=output_path.parent, suffix=".wasm", delete=False) as temporary:
        temporary_path = Path(temporary.name)
    try:
        subprocess.run(
            [args.wasm_as, str(source_path), "-o", str(temporary_path), "--enable-bulk-memory"],
            check=True,
        )
        temporary_path.replace(output_path)
    finally:
        temporary_path.unlink(missing_ok=True)
    fixture_path.write_text(fixture, encoding="utf-8")
    print(f"Built {output_path}")
    print(f"Generated {fixture_path}")


if __name__ == "__main__":
    main()
