#ifndef WASTE_CONFIG_H
#define WASTE_CONFIG_H

#define VFS_MAX_ENTRIES 2048
#define VFS_MAX_BYTES (128 * 1024 * 1024)
#define VFS_RUNTIME_NODE_RESERVE 64
#define VFS_INVENTORY_MAX_BYTES (2 * 1024 * 1024)
#define VFS_PATH_MAX_BYTES 256

/* Implementation resource limits, shared by C and generated host configuration. */
#define WAST_MAX_DATA_SEGS 128
#define WAST_MAX_ELEM_SEGS 128
#define JSON_MAX_DEPTH 64
#define EXECUTION_MAX_TIMEOUT_MS 3600000
#define EXECUTION_MAX_PUMP_QUANTUM_MS 60000
#define TERMINAL_INPUT_CAPACITY 4096
#define POSIX_KERNEL_FD_MAX 64
#define SOURCE_SHEBANG_MAX_BYTES 4096

/* Batch policy. Native and production-browser controllers share deadlines. */
#define SUITE_TIMEOUT_CORE_MS 15000
#define SUITE_TIMEOUT_HEAVY_MS 10000
#define SUITE_TIMEOUT_DEFAULT_MS 5000
#define SUITE_OUTPUT_MAX_BYTES (16 * 1024 * 1024)
#define SUITE_NATIVE_MAX_JOBS 64
#define SUITE_BROWSER_MAX_JOBS 8
#define SUITE_GUEST_DEFAULT_JOBS 2
#define SUITE_BROWSER_UI_TIMEOUT_MS 60000
#define SUITE_GUEST_MAX_ARGS 64
#define SUITE_GUEST_REQUEST_MAX_BYTES 4096
#define SUITE_GUEST_REPLY_MAX_BYTES (16 * 1024 * 1024)
#define GUEST_TEST_MAX_MEMORY_BYTES (32 * 1024 * 1024)
#define RENDER_TEST_REPLY_MAX_BYTES (64 * 1024)

/* Browser assertion records: one status byte, display name, error text. */
#define BROWSER_RESULT_NAME_BYTES 63
#define BROWSER_RESULT_ERROR_BYTES 192
#define BROWSER_RESULT_ERROR_OFFSET (1 + BROWSER_RESULT_NAME_BYTES)
#define BROWSER_RESULT_BYTES (BROWSER_RESULT_ERROR_OFFSET + BROWSER_RESULT_ERROR_BYTES)
#define WAST_SETUP_ERROR_BYTES 256

/* Slower legacy worker harness budgets remain separate from batch policy. */
#define LEGACY_BROWSER_TIMEOUT_DEFAULT_MS 60000
#define LEGACY_BROWSER_TIMEOUT_CORE_MS 35000
#define LEGACY_BROWSER_TIMEOUT_SIMD_MS 50000
#define LEGACY_BROWSER_TIMEOUT_BULK_MS 60000
#define LEGACY_NATIVE_TIMEOUT_DEFAULT_MS 30000

#endif
